### ISSUE TITLE
Code generation doesn't support generic classes

### ISSUE THREAD

**Issue by arkanes** [PerfDotNet/BenchmarkDotNet#100]
When attempting to write a benchmark in a generic class, I have failures because the code generation seems to just rely on type.Name. 

trivial example:

```cs
var summary = BenchmarkRunner.Run<CsvParsingBenchmarks<TCSV>>();
```

where I'm doing independent runs to benchmark different CSV configurations

**Comment by AndreyAkinshin** [comment]
Thanks for the report. Will be fixed soon.
