### ISSUE TITLE
Strong naming?

### ISSUE THREAD

**Issue by jskeet** [PerfDotNet/BenchmarkDotNet#101]
Much as I'm not a fan of strong naming, it's a fact of life and a necessity for open source projects which want to be consumable by other projects which *are* strongly named.

Therefore, NodaTime is strongly named.

NodaTime.Benchmarks uses some internals of NodaTime, therefore NodaTime.Benchmarks is strongly named.

Therefore, BenchmarkDotNet should be strongly named so that I can consume it :)

(I don't think I'll be alone in this...)

**Comment by martincostello** [comment]
+1 - I've literally just started playing with this library and got this on first use:

```
System.IO.FileLoadException : Could not load file or assembly 'BenchmarkDotNet, Version=0.9.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
```

**Comment by ppanyukov** [comment]
I bet the moment there is a switch to strong-name-only option there will be requests to provide a not-strongly-named package :)

Is it a good idea to follow the example of `StackExchange.Redis` and provide **two** packages: one as-is now, and another with strong name, as in:

- **StackExchange.Redis**: https://www.nuget.org/packages/StackExchange.Redis/
- **StackExchange.Redis.StrongName**:  https://www.nuget.org/packages/StackExchange.Redis.StrongName/


From my own experience with these as a consumer, the approach worked well for us.

**Comment by martincostello** [comment]
That approach would work for me. Strong-naming often causes tugs-of-war among developers :)

**Comment by jskeet** [comment]
Why would there be a request for a not-strongly-named package? What can you do with a not-strongly-named package that you can't do with a strongly-named package, if the signing key is provided (which is the current recommendation)? If the signing key *isn't* provided, it means you can't fix issues yourself without waiting for another release, but I'd propose that we include the signing key.

**Comment by ppanyukov** [comment]
@jskeet I'm sure you are aware of billions of heated discussions about strong-name vs not-strong-name in the last years better than anyone else here? I had first-hand grief experiences with strong names in the past.

But things must have moved on, because you don't seem to consider this an issue anymore. What is the current recommendation about providing the signing key you are referring to? I'm not aware of the latest on this. 

If you could provide a link to read up on that, it would be most helpful.

**Comment by jskeet** [comment]
I'm aware that it's been a pain in the past for open source projects precisely because the signing key was not included. I'm not aware of any other drawback to signing, as far as the consumer is concerned.

The new guidance is at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md:

> Firstly, we would recommend that these open source projects check-in their private key (remember, strong-names are used for identity, and not for security).

Now that document also says that most libraries don't need to strong name... but I'd argue that that really only applies to libraries which are never used by other libraries or applications that are strong-named. Maybe in the dim and distant future, almost no-one will strong-name their code - but today, it's a reality. Note that "leaf node" projects using strong-naming doesn't perpetuate this - it's really apps/libraries that depend on others that need to change first.

**Comment by martincostello** [comment]
Based on the "identity-not-security" point, the key-pair file should just be included in the repo. That's what I've done with two libraries I have published on NuGet whose code is hosted here in GH.

**Comment by xoofx** [comment]
> I'm aware that it's been a pain in the past for open source projects precisely because the signing key was not included. I'm not aware of any other drawback to signing, as far as the consumer is concerned.

The main drawback of signing are for plugins (without an assembly redirect). If a library A is signed and provides a plugin infrastructure, and another library B using A to provide a plugin. If the library A is changing (even just by fixing an internal issue), the developer of the library B will have to re-compile/deliver a version of its library B, unless you specify an assembly redirect. It may not be a big deal for the BenchmarkDotNet project, as projects using it are not aimed at building redistributable libraries on top of it. Usually, I'm banning strong-name for a library that provides a plugin/callback infrastructure.

**Comment by jskeet** [comment]
Ah, I wasn't aware of that aspect. (I'd have expected it to be okay if the AssemblyVersion were the same, with only the AssemblyFileVersion changing, but I'm not an expert on that side of things.)

For that scenario, publishing a "with strong name" and "without strong name" version doesn't help either - it just means plugin developers need to build two packages as well.

In this case I strongly suspect there will be more people who need to benchmark strongly-named code than there will be plugin producers, so I'm still in favour of introducing strong naming.

**Comment by NPatch** [comment]
+1 for strong naming. 
When providing a plugin , you usually provide the libraries it uses as well. Users don't really need to have the latest version of library A(or update it as a new version gets released) since all they want to do is use the plugin with library B( that needs library A, more precisely a version compatible with library B). All they want is a working solution, most of the time.

**Comment by mgravell** [comment]
@ppanyukov in some ways, if I was doing SE.Redis from scratch, I would have strong named it from the outset. I don't *like* strong naming as such (in most cases where a reason is given, the reason is a confused one, thinking it does something that it doesn't actually do; in other cases, the reason is simply "because I need it to be strong named to work on [platform X]"). But frankly I've grown bored of having the fight!

Related: on "dapper" we have dual packages, and we are genuinely considering merging them (making one strong named package) the next time we do a "major" bump (which we consider to be a legitimate point to break identity). It is possible that we might do the same with SE.Redis.

**Comment by mgravell** [comment]
@xoofx binding redirects are built into tools like nuget now, no?

**Comment by JoshVarty** [comment]
> If a library A is signed and provides a plugin infrastructure, and another library B using A to provide a plugin. If the library A is changing (even just by fixing an internal issue), the developer of the library B will have to re-compile/deliver a version of its library B, unless you specify an assembly redirect

Are you sure this is true? The full signature isn't checked unless you're GACing the assembly (Or you disable strong name bypass on your machine). So wouldn't the short name, culture, version and public key token remain the same?

You can certainly rewrite/modify strong named DLLs and anything that referenced them will continue to work away happily.

**Comment by mgravell** [comment]
The problem there is usually the "version" part, and how people decide to label the package; if the declared version changes, then: the identity is different. One approach there is to not change the identity version for minor builds (keeping that to the nuget package, and maybe `[AssemblyFileVersion]`)

**Comment by JoshVarty** [comment]
Makes sense :+1:

**Comment by xoofx** [comment]
> @xoofx binding redirects are built into tools like nuget now, no?

Haven't checked, good if they are part of it... but some solutions are not using nuget for their project dependencies...

> The problem there is usually the "version" part, and how people decide to label the package; if the declared version changes, then: the identity is different. One approach there is to not change the identity version for minor builds (keeping that to the nuget package, and maybe [AssemblyFileVersion])

That could be actually a good workaround.. but still, a major version doesn't mean that you break existing features...

**Comment by mgravell** [comment]
> but still, a major version doesn't mean that you break existing
features...

In terms of semver 2.0 (http://semver.org/), yes, it does:


   1. MAJOR version when you make incompatible API changes,
   2. MINOR version when you add functionality in a backwards-compatible
   manner, and
   3. PATCH version when you make backwards-compatible bug fixes.


just sayin'

**Comment by mattwarren** [comment]
Is it worth trying to do this in for [**0.9.5**](https://github.com/PerfDotNet/BenchmarkDotNet/milestones/v0.9.5)?

**Comment by AndreyAkinshin** [comment]
Yes.
