### ISSUE TITLE
GCDiagnoser should create a real-time ETW session and not use logman to record to a file

### ISSUE THREAD

**Issue by goldshtn** [PerfDotNet/BenchmarkDotNet#102]
Continuing the discussion from https://github.com/PerfDotNet/BenchmarkDotNet/commit/ae71f296843b2d9bd05892477241c4193573b42e. Need to make the diagnosers project refer to the TraceEvent NuGet package (which supports .NET 3.5), and then the `TraceEventSession` class can be used for real-time event processing.

@mattwarren

**Comment by mattwarren** [comment]
merged
