### ISSUE TITLE
Params Attribute bug with float type

### ISSUE THREAD

**Issue by hiiru** [PerfDotNet/BenchmarkDotNet#105]
I noticed a bug with the Params attribute.
When it is used on a property of type float, I get a casting error when running the benchmarks:
> // Program.cs(26,35): error CS0664: Literal of type double cannot be implicitly converted to type 'float'; use an 'F' suffix to create a literal of this type
> BuildManager.DefaultBuildManager can't build this project. =(

I created a minimal example code to reproduce the bug:
https://github.com/hiiru/BenchmarkDotNet-bug-paramsfloat

generated report: https://github.com/hiiru/BenchmarkDotNet-bug-paramsfloat/blob/master/BugPoC-report-default.md

I tested it with 0.9.1 and dev.

**Comment by AndreyAkinshin** [comment]
@hiiru, thanks for the bug report. Fixed in the develop branch, will be on NuGet soon.
