### ISSUE TITLE
Specify benchmark method order

### ISSUE THREAD

**Issue by xoofx** [PerfDotNet/BenchmarkDotNet#107]
Could we have a way to specify order of benchmarks via either `DisplayAttribute.Order` or a dedicated attribute if it is relevant? (and use method name order otherwise). If both are used, display first methods with order and then methods by alphabetical order. (Not only used for reporting, but also for execution)

**Comment by mattwarren** [comment]
At the moment (in the latest GitHub code anyway) the best you can do this:

``` csharp
[Benchmark(Description = "Some Text")]
public void ABenchmark()
{  .. }
```

So the `Description` will be used instead of the method name. However this only affects the order that the results are displayed in, NOT the order that the benchmarks are executed.

Just out of interest, what's the reasons for wanting it to affect the order of execution? (I can understand wanting the order of display/reporting)

**Comment by xoofx** [comment]
> Just out of interest, what's the reasons for wanting it to affect the order of execution? (I can understand wanting the order of display/reporting)

I'm using BenchmarkDotNet to benchmark my library/method (which is in dev) against other libraries/method (which are usually stable, e.g: coming from nuget or coming from a part of my code that I don't change when I want to compare a new implem with an old implem)

So usually, once I have ran a first benchmark, I know how fast are other libraries/method. Then I usually iterate to fix performance issues and relaunch the benchmark mutlple times, I want to check only my implem first. I will break the benchmark after my first benchmark and not waiting for others, because they haven't change and I remember how well they performed.

Currently, I have to comment all other benchmark methods, and uncomment them once I wan't to recheck everything, this is quite annoying.

**Comment by xoofx** [comment]
For reporting, display order options could be a little more flexible, for example:
- Order from fastest to slowest
- Order from slowest to fastest
- Order from execution order

**Comment by redknightlois** [comment]
I can vouch of having done that too.

**Comment by AndreyAkinshin** [comment]
@xoofx, it is a really easy to implement, but it is hard to create a good API.

## Some thoughts

Let's start with order of execution. For now, a benchmark = TargetMethod + Job + Parameters. How we should combine these 3 lists? E.g. we have two methods (`A`, `B`), two jobs (`J1`, `J2`), and one parameter with two values (`x`, `y`). There are 6 following order possibilities:
* Method->Job->Params
`A-J1-x`, `A-J1-y`, `A-J2-x`, `A-J2-y`, `B-J1-x`, `B-J1-y`, `B-J2-x`, `B-J2-y`
* Method->Params->Job
`A-J1-x`, `A-J2-x`, `A-J1-y`, `A-J2-y`, `B-J1-x`, `B-J2-x`, `B-J1-y`, `B-J2-y`
* Job->Method->Params
`A-J1-x`, `A-J1-y`, `B-J1-x`, `B-J1-y`, `A-J2-x`, `A-J2-y`, `B-J2-x`, `B-J2-y`
* Job->Params->Method
`A-J1-x`, `B-J1-x`, `A-J1-y`, `B-J1-y`, `A-J2-x`, `B-J2-x`, `A-J2-y`, `B-J2-y`
* Params->Method->Job
`A-J1-x`, `A-J2-x`, `B-J1-x`, `B-J2-x`, `A-J1-y`, `A-J2-y`, `B-J1-y`, `B-J2-y`
* Params->Job->Method
`A-J1-x`, `B-J1-x`, `A-J2-x`, `B-J2-x`, `A-J1-y`, `B-J1-y`, `A-J2-y`, `B-J2-y`,

It is an easy case. But what if we want to use specific job property of specific parameter.

Next, we can sort (or not sort) values in each list:
* No sorting
* Sort descending
* Sort ascending

Finally, we should choose order for the summary table. We can use execution order or sort results some way. Suggested display order options (from fastest to slowest, from slowest to fastest, from execution order) look nice, but what if we want to sort by specific columns? Or two columns?

## Suggestion
I don't like 600 settings for each situation. So, I suggest to use some kind of general API like the following:

```cs
public interface IOrderProvider
{
  IEnumerable<Benchmark> GetExecutionOrder(Benchmark[] benchmarks);
  IEnumerable<Benchmark> GetSummaryOrder(Benchmark[] benchmarks, Summary summary);
}

public class OrderProviderExample : IOrderProvider
{
  public IEnumerable<Benchmark> GetExecutionOrder(Benchmark[] benchmarks) =>
    from benchmark in benchmarks
    orderby benchmark.Target.MethodTitle descending,
            benchmark.Job.Jit ascending,
            benchmark.Parameters.FullInfo ascending
    select benchmark;

  public IEnumerable<Benchmark> GetSummaryOrder(Benchmark[] benchmarks, Summary summary) =>
    from benchmark in benchmarks
    orderby benchmark.Target.MethodTitle descending,
            StatisticColumn.Median.GetValue(summary, benchmark) descending
    select benchmark;
}
```
Some additional thoughts:
1. We can implement string indexer for Parameters and write something like `benchmark.Parameters["A"]`
2. We also want to support natural sort order for parameters. A solution: `benchmark.Parameters["A"]` can return an object of corresponding type.
3. We also want to support natural sort order for columns. A solution: we can implement additional `double GetValue` for statistic columns.

@xoofx, what do you think?

**Comment by xoofx** [comment]
Having a common infrastructure for doing ordering, display, that's good.

But things should be easy in some particular common case. At least, I believe that my case is quite simple, I'm not using params, not using jobs (not sure what is their usage/semantic), didn't even know that they were existing.

So having to develop a class just to specify an order for methods is quite annoying, or at least, the common cases should be integrated so that we don't have to code anything. For instance, the code you show me above for custom ordering is longer than the code of the 5 methods I'm benchmarking ;)

Just specifying at the benchmark level that we want to use an ordering method would be good enough, still using the IOrderProvider API coming with a few builtin `IOrderProvider`:

```
[OrderProvider(typeof(DeclaredMethodProvider))]
public class MyBenchmark
{
}
```

**Comment by AndreyAkinshin** [comment]
@xoofx, good point. I can write a set of predefined OrderProviders (i don't sure that it is a good name; if you have a better one, let me know) for common cases.

**Comment by AndreyAkinshin** [comment]
@mattwarren, I'm ready to add `IOrderProvider` support. Any idea how I can integrate it with your recent "grouping" feature?

**Comment by AndreyAkinshin** [comment]
@mattwarren, maybe we can add an additional method that will return a group of each benchmark (e.g. a `string`)? Next, we can use this group to color output. What do you think?
