### ISSUE TITLE
Consider displaying "first call" effects in the summary table

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#109]
From a comment left on on Scott Hanselmans blog (http://www.hanselman.com/blog/CommentView.aspx?guid=31851866-03d3-4a11-90a0-a50597dca7e2#commentstart)

> I use almost entirely ETW to truly benchmark and profile code at the same time. The library looks nice for micro benchmarks. **I miss from the summary table first call effects. What if your method is only called once during startup but the JIT time is astronomically due to a JIT bug? If something is often called its performance is easy to measure.** The most annoying user aspect of waiting for the application is startup. There all the pesky one time init effects hide which can become quite complex to measure.

I know that JMH has a [SingleShotTime](http://javadox.com/org.openjdk.jmh/jmh-core/0.8/org/openjdk/jmh/annotations/Mode.html#SingleShotTime) mode for this, maybe we need something similar? I guess we can do some of this with `Jobs=Dry`, but I don't know if that's accurate?

JMH other has [other modes](http://javadox.com/org.openjdk.jmh/jmh-core/0.8/org/openjdk/jmh/annotations/Mode.html) that might be interesting to have??

**Comment by AndreyAkinshin** [comment]
We have `SingleRun` as an analogue of `SingleShotTime`.

**Comment by mattwarren** [comment]
WOW, sorry I completely forgot about that!!

Ignore this issue, I'll post a reply to the comment on Hanselmans blog.

**Comment by AndreyAkinshin** [comment]
Probably we should add more information about modes in the documentation.
