### ISSUE TITLE
Support for one-time Setup

### ISSUE THREAD

**Issue by TobiasBreuer** [PerfDotNet/BenchmarkDotNet#110]
As far as I can see in the MethodInvoker class, the setup method belonging to a job is called before every execution of a target action.

I wonder if it would be possible to have a second Setup attribute to mark a special Setup method which is called exactly one time before the execution of a new method having a the Benchmark attribute but not before every repetition of this method (as set by TargetCount).

The background of this is, to benchmark methods / classes, using a caching mechanism where I would like to analyse, how the performance behaves over time, especially when comparing different caching strategies.

Best regards,

Tobias

**Comment by AndreyAkinshin** [comment]
@TobiasBreuer, can you tell more about your situation? What exactly your do want to analyze?

**Comment by TobiasBreuer** [comment]
Hi Andrey, 
maybe code says more than I can explain - So let's have a look at a simplified example. 
```
[Config(typeof(Config))]
public class ReaderPerformance
{
    class Config : ManualConfig
    {
        public Config()
        {
            // Repeat each benchmark method 4 times
            Add(Job.Dry.WithTargetCount(4));
        }
    }

    /// <summary>
    /// The file reader instance
    /// </summary>
    private IFileReader _FileReader;

    /// <summary>
    /// Gets or sets the name of the file.
    /// </summary>
    /// <remarks>Benchmark runner will use all values for individual runs.</remarks>
    [Params("File_1", "File_2", "File_3")]
    public String FileName { get; set; }

    /// <summary>
    /// Gets or sets the size of the cache.
    /// </summary>
    /// <remarks>
    /// 0 -> Cache is disabled.
    /// -1 -> unlimited cache size
    /// 200 -> 200 MByte of cache size
    /// </remarks>
    [Params(0, -1, 200)]
    public int CacheSize { get; set; }

    //////////////////////        
    /// Here it would be great if this Setup would run
    /// before 'Benchmark' and before 'Benchmark_2'
    /// but not before each individual run of 'Benchmark' and 'Benchmark_2' 
    /// (note that it will run each 4 times as given by 'WithTargetCount(4)').
    [Setup]
    public void Setup()
    {
        // Create a new reader for the current file and cache size
        _FileReader = new FileReader(FileName, CacheSize);
    }

    [Benchmark]
    public void Benchmark()
    {
        PerformSomeOperation(_FileReader);
    }

    [Benchmark]
    public void Benchmark_2()
    {
        PerformSomeOtherOperation(_FileReader);
    }
        
    private void PerformSomeOperation(IFileReader fileReader)
    {
        // Do stuff
    }

    private void PerformSomeOtherOperation(IFileReader _FileReader)
    {
        // Do some other stuff
    }
}

Based on some internal states of my classes I could now see in the result window for every of the 4 runs how long the operation took and set this in relation with the behavior of my cache.

Best regards,

Tobias

**Comment by AndreyAkinshin** [comment]
Ok, I get it. You try to use library wrong way. There are some advises:
1. You want to know how Benchmark1 affects Benchmark2 based on cache state. So, don't split it up. Put it in one method and measure it together. One of basic BenchmarkDotNet concepts is the following: benchmarks should not affect each other.
2.  Don't set TargetCount manually. Only some specific situation requests a manual value of TargetCount. By default, BenchmarkDotNet try to choose a perfect count of target iterations that minimize noise and produce low standard error. Anyway, 4 iterations is not enough, you will not receive good accuracy. If you want to know total time of 4 iterations, put 4 iterations in the benchmark body.
3. Benchmark should not change state of your cache. Otherwise, there is no a steady state, and we just can't measure it. Put cache initialization logic in the setup method.

**Comment by TobiasBreuer** [comment]
Yes and no. 
Yes I'm somewhat missusing the library, No, Bechnmark 1 shall not influence Benchmark 2 or vice versa. The run that I would need is

- Setup
- Benchmark1
- Benchmark1
- Benchmark1
- Benchmark1
- Setup
- Benchmark2
- Benchmark2
- Benchmark2
- Benchmark2

Actually we could also completely ignore Benchmark2 I only added it for showing when the Setup should run. In the real test for this case I only have one Benchmark method.
It is correct, that my Benchmarks work against the definition of what a bechnmark should be. I actually do not expect a close to constent time with minimal fluctuation. I totally aggree, that having only 4 executions of a benchmark method gives you nothing for a 'real' benchmark but in this case its good enough. Based on the cache definition and status, the execution times for each run of Benchmark1 may vary significantly. That's what I expect and want to see.

By using the library for this scenario as well, my goal was to save me some time. Of course I could also use the good old Stopwatch class for measuring the time and a unit test framework. For this specific case that would be accurate enough. but especially the functionality of collecting information on the GC in the current development branch of the library is of much interist for me in this case. That's why I wanted to abuse the library in order to not have to collect such information by custom code. You know - don't reinvent the wheel if someone already did it - and did it quite well.

So I think we are totaly agreed that, in this case, I'm using the library for something it is not meant for. And my test is not a real benchmark test. And that said, if this missuse of the library is the only use case for a single shot Setup method (and honestly I could not think of any valid use case for it, but hoped that you would have one in mind when I triggered the idea ;-) ), I totaly aggree that the library should not support it.

Thx and best regards,

Tobias
