### ISSUE TITLE
Update NETStandard.Library dependency

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#114]
I can't publish v9.3.0 because of the NETStandard.Library dependency, see screenshot.

![nugetpackageexplorer_2016-03-10_12-19-41](https://cloud.githubusercontent.com/assets/2259237/13666518/9835296c-e6ba-11e5-8ced-05ad545f4c13.png)

**Comment by adamsitnik** [comment]
@AndreyAkinshin We need to remove NETStandard.Library dependency from project.json file (only from the main BDN project). It is required only for auto-generated project.json to have it.

Where should I push it? Directly to master? Or to coreclr and merge? Or you could remove this line and stash it with last, version-setting commit?

![image](https://cloud.githubusercontent.com/assets/6011991/13667182/7baaa1c8-e6b5-11e5-9d2f-0b9e28a8b0a4.png)

**Comment by AndreyAkinshin** [comment]
I already accept the PR, so, just push another commit directly in master.

**Comment by adamsitnik** [comment]
Hmm. I just realized that we have some other dependencies to prerelease packages.

The problem is that these are available only as prerelease:

```
"System.Console": "4.0.0-beta-23516",
"System.Threading.Thread": "4.0.0-beta-23516",
"System.Diagnostics.Process": "4.1.0-beta-23516",
"System.Runtime.InteropServices.RuntimeInformation": "4.0.0-beta-23516"
```

**Comment by AndreyAkinshin** [comment]
So, do you want to say that it is impossible to publish a stable CoreCLR package that uses `System.Console`?

**Comment by adamsitnik** [comment]
I am not sure, I am googling it at the moment.

**Comment by redknightlois** [comment]
You can't publish as stable a CoreCLR package, because dependencies are unstable.

**Comment by AndreyAkinshin** [comment]
=(
@adamsitnik, in this case, can we build two nuget packages in artifacts: a stable release (like `0.9.3`) without CoreCLR dependency, and a prerelease (like `0.9.3-beta`) with CoreCLR support?

**Comment by adamsitnik** [comment]
@redknightlois Thanks for the info!

@AndreyAkinshin I think yes. You need to go to the project.json file, remove the dnxcore50 part, build the solution in Release and publish the package. Then remove the net40, net45 and dnx451, restore dnxcore50, update the version and build in Release, grab the package and publish it.

Maybe there is cleaner way of doing it, but I have no ideas as for now.

**Comment by AndreyAkinshin** [comment]
Ok, now we have two version of the package:
* stable `0.9.3` (`net40`+`net45`+`dnx451`)
* prerelease `0.9.3-beta` (`net40`+`net45`+`dnx451`+`dnxcore50`)
