### ISSUE TITLE
Issue when ParamAttribute decorated property is double and current system culture has comma as decimal separator

### ISSUE THREAD

**Issue by henkmeulekamp** [PerfDotNet/BenchmarkDotNet#116]
Not sure if this is a known issue, or that documenting the work-around is enough, but I encountered it on my system having the Dutch regional settings by default. 

When a ParamAttribute is set on a double type and system culture is Dutch nl-NL (and any other region where decimal separator is a comma):

```csharp
   //set system culture to nl-NLif you dont want to switch regional settings to reproduce.
   Thread.CurrentThread.CurrentCulture = new CultureInfo("nl-NL");
   Thread.CurrentThread.CurrentUICulture = new CultureInfo("nl-NL");
```

```csharp
   [Params(52.3670354, 52.365036)]
   public double Lat { get; set; }
```
The tool generates the following code:

```csharp
  public static void Main(string[] args)
        {
            try
            {
				Program instance = new Program();
				instance.Lat = 52,365036;instance.Lon = 4,940312;
				instance.setupAction();
				instance.targetAction();
                System.Console.WriteLine(EnvironmentHelper.GetCurrentInfo().ToFormattedString().AddPrefixMultiline("// "));
                System.Console.WriteLine();
                instance.RunBenchmark();
            }
            catch (Exception ex)
            {
                System.Console.WriteLine(ex);
                throw;
            }
        }
```

This will fail on build:
```
// *** Build ***
// Program.cs(26,22): error CS1002: ; expected
// Program.cs(26,22): error CS1525: Invalid expression term ','
// Program.cs(26,23): error CS1002: ; expected
// Program.cs(26,46): error CS1002: ; expected
// Program.cs(26,46): error CS1525: Invalid expression term ','
// Program.cs(26,47): error CS1002: ; expected
BuildManager.DefaultBuildManager can't build this project. =(
```

For my testing code it is fixed by first setting the en-US cultureinfo, before starting up the `BenchmarkRunner.Run<Searcher>();`.
```
   Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
   Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");

   BenchmarkRunner.Run<Searcher>();
```

I do assume fixing this in the code generator would be a better solution?

**Comment by adamsitnik** [comment]
@henkmeulekamp  Goedenavond! Thanks for the detailed bug report! I will fix it right away.

**Comment by adamsitnik** [comment]
I just wrote test for that, it passed and I realized that it got already got fixed ;)

[Commit](https://github.com/PerfDotNet/BenchmarkDotNet/commit/d3f7ce6294fe94150c810bc27122d2aa927748dc?diff=unified), [code](https://github.com/PerfDotNet/BenchmarkDotNet/blob/d3f7ce6294fe94150c810bc27122d2aa927748dc/BenchmarkDotNet/Toolchains/Classic/ClassicGenerator.cs#L114-L119)

However these changes were not published yet, so please wait for the next nuget package version release.

**Comment by henkmeulekamp** [comment]
Thanks for fixing it so fast!
