### ISSUE TITLE
Can not run benchmark that references custom framework library (like WindowsBase)

### ISSUE THREAD

**Issue by JohanLarsson** [PerfDotNet/BenchmarkDotNet#123]
using System.Windows;
    using BenchmarkDotNet.Attributes;

    public class Repro
    {
        [Benchmark]
        public Point? Foo()
        {
            return new Point();
        }
    }

**Comment by adamsitnik** [comment]
Hi @JohanLarsson ! Which version of BenchmarkDotNet are you using? I can not reproduce this bug. Here is what I have tried:

```
[Benchmark]
public object ReturnNullForReferenceType()
{
	return null;
}

[Benchmark]
public object ReturnNotNullForReferenceType()
{
	return new object();
}

[Benchmark]
public DateTime? ReturnNullForNullableType()
{
	return null;
}

[Benchmark]
public DateTime? ReturnNotNullForNullableType()
{
	return DateTime.UtcNow;
}

[Benchmark]
public DateTime ReturnDefaultValueForValueType()
{
	return default(DateTime);
}

[Benchmark]
public DateTime ReturnNonDefaultValueForValueType()
{
	return DateTime.UtcNow;
}
```

**Comment by JohanLarsson** [comment]
Hello @adamsitnik I'm using BenchmarkDotNet.0.9.3
The issue has something to do with using `System.Windows.Point` because when I did:
```
[Benchmark]
public int Foo()
{
    return new Point().X;
}
```

It worked.

**Comment by adamsitnik** [comment]
I did some further investigation. It seems it is a same bug as [this](https://github.com/PerfDotNet/BenchmarkDotNet/issues/72)

BDN generates new csproj for each benchmark, compiles it and executes. We have some issues with referencing dlls that are required to compile. The NRE you see is a deffered effect of this.
