### ISSUE TITLE
Print dotnet cli version in EnvironmentInfo

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#128]
Also, it would be cool to print a warning in case when we doesn't have dotnet cli (see #127)
@adamsitnik, can we do it?

**Comment by adamsitnik** [comment]
@AndreyAkinshin sure

**Comment by adamsitnik** [comment]
@AndreyAkinshin I have implemented that and pushed the changes to develop branch.

I dediced to put it only in summary (not for each benchmark) and only for DNX/CORE benchmarks to save time (it requires to create a new process to call dotnet --version).

```
// * Summary *

BenchmarkDotNet-Dev=v0.9.4.0+
OS=Windows
Processor=?, ProcessorCount=8
Frequency=2338334 ticks, Resolution=427.6549 ns, Timer=TSC
HostCLR=CORE, Arch=64-bit RELEASE [RyuJIT]
JitModules=?
.NET Command Line Tools (1.0.0-beta-001603)
```
