### ISSUE TITLE
Improve DnxAndCoreTests

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#129]
I have the following concerns:
* For now, it is hard to understand which tests are failed. E.g., here is my result of `runDnxAndCoreTests.cmd`:
```
  Finished:    BenchmarkDotNet.IntegrationTests
=== TEST EXECUTION SUMMARY ===
   BenchmarkDotNet.IntegrationTests  Total: 19, Errors: 0, Failed: 1, Skipped: 0, Time: 193.977s
CORE tests has failed
```
Can we improve the console output?

* `runDnxAndCoreTests.cmd` creates a lot of benchmark folders in the root directory. Can we delete it or move to another folder (which will be ignored by git).

**Comment by adamsitnik** [comment]
I am glad that you use it! The failing test is ProcessorArchitectureTest which fails for Core because dotnet cli does not support x86 compilation.

I will improve the output. 

> creates a lot of benchmark folders in the root directory. Can we delete it or move to another folder (which will be ignored by git).

I will try to find some good solution and perhaps combine it with #94

**Comment by mattwarren** [comment]
I came across this just yesterday, one really easy fix is to change the "command" section in the `project.json` to this:

```
"commands": {
    "test": "xunit.runner.dnx -verbose"
  },
```

There's probably more that can be done, but that's a good start

**Comment by adamsitnik** [comment]
@AndreyAkinshin I have updated both scripts:

1. Clean everything to avoid any caching
2. Build
3. Run tests for Dnx/Core || 4.5/4.6
4. Display failed tests at the end
5. Cleanup
