### ISSUE TITLE
Add JIT benchmarks for struct promotion

### ISSUE THREAD

**Issue by damageboy** [PerfDotNet/BenchmarkDotNet#14]
I'm actually thiking of doing this myself, but I thought I'd put it up here until I get to actually do it.

I'd like to verify the RyuJIT does indeed provide the optimization describes here:
[Lies, damn lies, and benchmarks...](http://blogs.msdn.com/b/clrcodegeneration/archive/2014/02/26/lies-damn-lies-and-benchmarks.aspx)

I'm referring namely to struct-promotion.

There's even a link to some code that should demonstrate this in RyuJIT [here](https://kscdg.codeplex.com/SourceControl/latest#JIT-Benchmarks/FractalPerf.cs)

It would be nice to actually verify this in reality... hence this issue

**Comment by AndreyAkinshin** [comment]
Hi @damageboy,
we don't collect benchmark samples anymore (I also think about to move it to a separated repo). So, it's not an issue related to BenchmarkDotNet.
