### ISSUE TITLE
[Request for comments] Assembly-level config attribute?

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#141]
Hi!

I want to add an ability to specify benchmark config at assembly level.
Use case is pretty obvious: I have project with dozens of performance tests and I want to be able to switch the config for all of them at once.

Technically I can store the config in static field and pass the field like this: `BenchmarkRunner.Run(config: SomeClass.MyConfig, ...)`.

However, there's one moment I do not like: the config will replace default one so it should have all colums, exporters, loggers etc declared. For example, this one
```
			var config = new ManualConfig();
			config.Add(Job.Dry);
			BenchmarkRunner.Run<SomeBenchmark>(config);
```
prints nothing.

### The proposal:

1. Modify the `BenchmarkConverter.GetFullConfig()` - it should check config attribute on assembly if the benchmark type have no `IConfigSource` attribute applied.

2. Use `[AttributeUsage(AttributeTargets.Class | AttributeTargets.Assembly)]` on all attributes that implement `IConfigSource`.

Should I do a PR?

**Comment by adamsitnik** [comment]
Another good idea @ig-sinicyn! @AndreyAkinshin @mattwarren  what do you think?

**Comment by ig-sinicyn** [comment]
@adamsitnik  also, what about #140?

Will be happy to get some comments on it:)

**Comment by adamsitnik** [comment]
I think that we could also add overload of Run method for BenchmarkRunner that accepts assembly.

As for #140 I am sorry for my lack of response, I will get back to you soon. I just don't have perfect solution yet ;p
