### ISSUE TITLE
[Suggestion] BenchmarkDotNet.Analyzers.IAnalyser - use same spelling for namespace and type?

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#142]
Hi!

The `IAnalyser` interface belongs to `BenchmarkDotNet.Analyzers` namespace. The first one uses British English spelling, and the second one - American English.

There can be only one, I think:)

**Comment by adamsitnik** [comment]
thanks for the suggestion!
