### ISSUE TITLE
Running against dnx/dnvm/dnu toolchain

### ISSUE THREAD

**Issue by russcam** [PerfDotNet/BenchmarkDotNet#143]
I see that `DnxToolchain` type uses the `DotNetCliBuilder`

https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Toolchains/Dnx/DnxToolchain.cs#L19

that runs against the `dotnet` cli toolchain

https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliBuilder.cs#L81

Did anyone try to build a version against the RC1 dnx/dnu/dnvm toolchain?

**Comment by adamsitnik** [comment]
We used dnx/dnu/dnvm for a while, but it got deprecated before we shipped new version so we have [replaced dnx with dotnet cli](https://github.com/PerfDotNet/BenchmarkDotNet/commit/3402f012cc59d50491d29322c06c4e8c0a52ddde). The advantage is that we can build dnx451 with dotnet cli as well so we use single tool instead of two.

**Comment by russcam** [comment]
Thanks for the commit link :+1:  

Contemplating now whether to update our source to use dotnet cli or checkout the dnx version in the commit...

**Comment by adamsitnik** [comment]
I am not sure if it is possible to update VS solutions to build with dotnet cli. I know that MS has finished moving to it internally last week. Most probably you could just use both: stay with dnx to work with projects on a daily basis (integration with VS) and install dotnet cli on the machines that you want to run benchmarks. Dotnet cli should be able to build your dnx projects as well. When I migrated some problejects from dnx to dotnet cli I had only few issues:
* cli does not support empty version strings in project.json file ("dependencies": { "BenchmarkDotNet": "" }) will throw
* when referencing wraps the root directory for relative paths is not solution's dir, but project's dir. I had to update these paths
* cli seems to ignore Nuget.config file placed in $YourSolutionFolder$\\.nuget\NuGet.Config. It uses only your global nuget config file

**Comment by adamsitnik** [comment]
@russcam Btw for BenchmarkDotNet Runtime.Dnx means dnx451, Runtime.Core means dnxcore50. You most probably look for our [CoreToolchain](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Toolchains/Core/CoreToolchain.cs)

**Comment by russcam** [comment]
> Btw for BenchmarkDotNet Runtime.Dnx means dnx451, Runtime.Core means dnxcore50. You most probably look for our CoreToolchain

Awesome, I didn't clock that one, thanks! Was there a specific reason for splitting them out? I mean, I understand that `dnx451` and `dnxcore50` have separate framework dependencies and target different runtimes, but both of them are built with the the `dotnet cli` toolchain. That's a question to better understand dotnet cli as much as anything :smile:

**Comment by adamsitnik** [comment]
In general dotnet cli allows you to build and run .NET applications for any target framework monikers (net20, net35, net40, net45, net451, net452, net46, net461 as well as dnx451, dnx452, dnx46 and dnxcore50, dotnetstandard13 and all other  aliases for .NET Core). It is also cross-platform, so we can do it on Mac, Unix and Windows.

DNX451 itself is a DNX SDK running on .Net 4.5.1 (Desktop CLR / Full BCL and FCL). So it is not Cross-Platform yet, which NETCORE aka DNXCORE50 is.

We have separate Runtimes/Toolchains to allow users to specify which one they would like to target. Also when Runtime is not specified, we [take the host's Runtime](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Toolchains/Toolchain.cs#L31-L49). Reusing dotnet cli and having separate Toolchains allows us to implement such features as [Executing single Benchmark for multiple Runtimes with Diagnoser attached](https://github.com/PerfDotNet/BenchmarkDotNet/pull/117)
