### ISSUE TITLE
Crash during benchmark with baseline

### ISSUE THREAD

**Issue by kayanme** [PerfDotNet/BenchmarkDotNet#151]
At the the end of test.

  в BenchmarkDotNet.Columns.BaselineDiffColumn.GetValue(Summary summary, Benchmark benchmark)
   в BenchmarkDotNet.Reports.SummaryTable.<>c__DisplayClass21_2.<.ctor>b__11(IColumn c)
   в System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   в System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   в BenchmarkDotNet.Reports.SummaryTable.<>c__DisplayClass21_1.<.ctor>b__10(BenchmarkReport r)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   в System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   в BenchmarkDotNet.Reports.SummaryTable..ctor(Summary summary)
   в BenchmarkDotNet.Reports.Summary..ctor(String title, IList`1 reports, EnvironmentHelper hostEnvironmentHelper, IConfig config, String currentDirectory, TimeSpan totalTime)
   в BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, ILogger logger, String title, IConfig config)
   в BenchmarkDotNet.Running.BenchmarkRunner.Run(IList`1 benchmarks, IConfig config)
   в BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
...

**Comment by adamsitnik** [comment]
Could you provide a minimum failing example?

**Comment by kayanme** [comment]
```

    public class E
    {
        public E[] _arr = new E[2];
        public E _p;
    }

   public  class ArrayBench
   {
       private E _e;

        [Setup]
       public void Init()

        {
            var i = new E();
            _e = Enumerable.Range(0, 3000).Aggregate(i, (a, s) =>
                                                             {
                                                                 var e = new E();
                                                                 e._arr[0] = a;
                                                                 e._p = a;
                                                                 return e;
                                                             });
            i._arr[0] = _e;
            i._p = _e;
        }

       [Benchmark(Baseline = true)]
       public void Array()
        {
            _e = _e._arr[0];
        }

        [Benchmark]
        public void Field()
        {
            _e = _e._p;
        }
    }

```

Then BenchmarkRunner.Run<ArrayBench>();

**Comment by mattwarren** [comment]
@kayanme what version of BenchmarkDotNet are you using? 

I tried your code out with [0.9.4.0](https://www.nuget.org/packages/BenchmarkDotNet/0.9.4) and I don't get that error.

**Comment by kayanme** [comment]
Actually now it works fine for me too.
Unfortunately I didn't collect logs for that run.
I'll try a bit more, if I got that error again - I'll post an update.

**Comment by mattwarren** [comment]
This might be the same as #158, so there's definitely a problem here.
