### ISSUE TITLE
MarkdownExporter.Default.ExportToLog fails with NRE for Summary with Critical Validation Errors

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#152]
Bench.Net 0.9.5, summary obtained from run with critical errors (e.g. run with `Validators.JitOptimizationsValidator.FailOnError` on debug build).

Call to the `MarkdownExporter.Default.ExportToLog()` fails at `MarkdownExporter.PrintTable()`, as the SummaryTable passed is null.

**Comment by adamsitnik** [comment]
Honestly I am not sure if it was a bug, because BenchmarkRunner would not call any export if summary has some critical validation errors but I have fixed it anyway ;)
