### ISSUE TITLE
ManualConfig.Add(IConfig config) does not add the validators.

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#153]
Bench.Net 0.9.5.

I've a benchmark test where some parameters are set via [Config()] attribute and some are passed as a  parameter of the benchmark runner.

This setup does not allow to pass any validators into the benchmark. The `BenchmarkConverter.GetFullConfig()` method uses `ManualConfig.Union()` to merge the configs and it does not copies the validators at all.

Looks like a bug : )

**Comment by adamsitnik** [comment]
@ig-sinicyn And yet again, thank you for very well described bug reports!

**Comment by ig-sinicyn** [comment]
@adamsitnik , de nada:)
