### ISSUE TITLE
PathTooLong exception on custom config

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#154]
Bench.Net 0.9.5.
Config:
```
	public class FastRunConfig : ManualConfig
	{
		public static readonly IConfig Instance = new FastRunConfig();

		public FastRunConfig()
		{
			Add(
				new Job
				{
					IterationTime = 100,
					LaunchCount = 1,
					WarmupCount = 3,
					TargetCount = 10,
					Jit = Jit.RyuJit
				});
		}
	}
```

Benchmark fails with path too long exception, log:
[JitOptimizedDispatchPerfTests.zip](https://github.com/PerfDotNet/BenchmarkDotNet/files/246505/JitOptimizedDispatchPerfTests.zip)

As a suggestion: why not pass the args (including the method to run) via command line? That way you can emit only one binary for each job in the benchmark instead of dozens of projects with names like
`JitOptimizedDispatchPerfTests_Test02SwitchOverMutableField_Jit-RyuJit_Warmup3_Target10_Process1_IterationTime100`.

P.S. Any workaround, if possible?

**Comment by mattwarren** [comment]
This is the same as #91

**Comment by ig-sinicyn** [comment]
@mattwarren, almost the same. My proposal is slightly broader as I suggest to emit a single binary for all benchmarks in run (when it's possible, of course). There's obviously no need to emit a separate exe for each benchmark method.

**Comment by mattwarren** [comment]
@ig-sinicyn Yeah good point, I'll close my old issue and all work done against this can be associated with this one.

**Comment by adamsitnik** [comment]
Recently this bug caused me a lot of troubles. For example I was implementing .NET Core RC2 support and was getting some really crazy exceptions from dotnet cli and after some debugging it turned out that it was the TooLong path ex.

I have one idea how we can approach it:
If the benchmarks are configured to KeepBenchmarkFiles (not the default value) then use current naming which can cause troubles. Otherwise (default) I will use some short, constant name like "BDN.Auto". If user do not want to keep the auto generated files then he or she should not care for the names.

@AndreyAkinshin is this ok for you?

**Comment by ig-sinicyn** [comment]
@adamsitnik, @AndreyAkinshin 
I'd propose to change the entire way the benchmarks are built and run. The current approach has too match technical debt to leave it as is.

At first, the generated part of benchmark should be replaced with exe that contains something [like this](https://github.com/rsdn/CodeJam/blob/master/PerfTests/src/%5BL1_InProcess%5D/Toolchains/RunnableBenchmark.cs).
Of course, the parameters of the benchmark (job, target parameters and the target itself) should be passed via command line args and the factory class for the runnable benchmark should be able to deserialize them.

This allow you to remove the build step at all for all environments. And even if not, the code generation will be much simpler as it the generated code can reuse same logic that precompiled exe uses.


And the second, the code of the runnable benchmark should provide hooks for common events (before run, after run, after warmup etc). This will ease fixing #177 and #133.

**Comment by adamsitnik** [comment]
@ig-sinicyn Your proposal sounds very reasonable. The other thing that we need is to support non-console apps to get the UWP support. So we need come up with some nice, flexible architecture for all of the scenarios:
* compilation with multiple toolchains
* multiple operating systems
* multiple runtimes (Dekstop Clr, Mono, .NET Core)
* diagnosers 
* non-console apps (UWP and more?)
* anything else that shows up later

For now I have committed the proposed changes to get the most common scenario working.

**Comment by AndreyAkinshin** [comment]
The current state:
* By default, all the benchmark files are generating in the `BDN.Generated` folder.
* If you specify `KeepBenchmarkFiles = true`, short random name will be generated for each job.
* You also can set own Id for each job (which will be used for folder name).
