### ISSUE TITLE
Cleanup benchmark folders

### ISSUE THREAD

**Issue by JimBobSquarePants** [PerfDotNet/BenchmarkDotNet#156]
Hi there,

I'm running version 0.9.5 in an xproj and whenever I run the tests there are folders created for each benchmark in the solution. This doesn't get cleaned up and becomes an issue for my source control. Oddly at the same level as my benchmark test project.

![benchmark](https://cloud.githubusercontent.com/assets/385879/15008136/7628c936-1221-11e6-9b82-b98c53e091db.png)

Is there a way to configure where these tests are created or a way to automatically cleanup afterward?

I'm initialising the tests as follows. (Taken from your samples)

```
//Use reflection for a more maintainable way of creating the benchmark switcher,
Type[] benchmarks = typeof(Program).Assembly.GetTypes()
    .Where(t => t.GetMethods(BindingFlags.Instance | BindingFlags.Public)
                    .Any(m => m.GetCustomAttributes(typeof(BenchmarkAttribute), false).Any()))
    .OrderBy(t => t.Namespace)
    .ThenBy(t => t.Name)
    .ToArray();

BenchmarkSwitcher benchmarkSwitcher = new BenchmarkSwitcher(benchmarks);
benchmarkSwitcher.Run(args);
```

Many thanks!

**Comment by adamsitnik** [comment]
> Oddly at the same level as my benchmark test project.

We do this because of some xproj/dotnet cli limitations. I know that it sucks but I could not find better way to solve few problems (being compatibile with VS, dnx, dotnet cli and xunit test runner with single config)

I will implement benchmark folder cleanup for 0.9.6.

@AndreyAkinshin do you think that cleanup should be enabled by default or optional?

**Comment by AndreyAkinshin** [comment]
Let's do it by default. But we should also have an easy way to disable cleanup.

**Comment by JimBobSquarePants** [comment]
Thanks both of you, really appreciate it. Loving playing round with this tool :+1:

**Comment by adamsitnik** [comment]
I have extended IConfig with new boolean flag KeepBenchmarkFiles. It determines if all auto-generated files should be kept or removed after running benchmarks. Default for booleans is false, so by default all   files are not kept = they are removed.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, don't forget to use `KeepBenchmarkFiles` during config merge. (I think, we should `or` all the flags).
