### ISSUE TITLE
Reporting: better number display

### ISSUE THREAD

**Issue by ppanyukov** [PerfDotNet/BenchmarkDotNet#16]
Probably minor.

This threw me off a little:

```
 Method |  AvrTime |    StdDev |        op/s |
------- |--------- |---------- |------------ |
 Sqrt13 | 63.43 ns |  0.768 ns | 15764394.26 |
 Sqrt14 | 68.17 ns | 0.0794 ns |  14669862.3 |
```

and then I realised the numbers are not aligned.

To make it easier to inspect the results, we can do a couple of things:

1. **Ops/sec**: thousand separators and fixed decimals (say 2).

    Effect of this:

	```
	 Method |  AvrTime |    StdDev |           op/s |
	------- |--------- |---------- |--------------- |
	 Sqrt13 | 63.43 ns |  0.768 ns |  15,764,394.26 |
	 Sqrt14 | 68.17 ns | 0.0794 ns |  14,669,862.30 |
	```

2. **AvrTime** and **StdDev** is trickier, because I can see you use variable decimal precision depending on how small the value is. Nevertheless, several options here too:

  - **Same precision**. Just use the same precision for everything (say 3 or 4). The simplest but may not work if the numbers are really small.

    So the effect of this would be:

    ```
     Method |  AvrTime   |    StdDev |           op/s |
    ------- |----------- |---------- |--------------- |
     Sqrt13 | 63.4300 ns | 2.1000 ns |  15,764,394.26 |
     Sqrt13 | 63.4300 ns | 0.7680 ns |  15,764,394.26 |
     Sqrt14 | 68.1700 ns | 0.0794 ns |  14,669,862.30 |

    ```

  - **Decimal point alignment**. More tricky but will work in all cases. The result may look unusual and may throw off people :)

    This may look like this (with minor variations):

    ```
              0.753  ns
              0.0335 ns
          23535.1     s
      614119772.34     
    614,119,772.34     
       16496828.35     
     16,496,828.35     
              0.0      
    ```

------------

I have a pull request for ops/sec format (hopefully not a controversial one), and a bit of code to do decimal point alignment which I can plug in.

Let me know what you think.

**Comment by AndreyAkinshin** [comment]
@ppanyukov, I totally agree, it is a good point.

**Comment by AndreyAkinshin** [comment]
@ppanyukov, Can you make a PR with all formating improvements?

**Comment by ppanyukov** [comment]
@AndreyAkinshin sure. Which approach for AvrTime and StdDev do you think would suite best? Obviously using the same precision is the quickest to do and also the most orthodox.

**Comment by AndreyAkinshin** [comment]
@ppanyukov, yes, the same precision is a good choice.

**Comment by AndreyAkinshin** [comment]
What are you think about the following idea: set the same time unit for AvrTime and StdDev?

**Comment by ppanyukov** [comment]
Do you mean so that we ensure that each column always has the same time unit ? E.g.

Instead of potentially having something like this (mixed `ms` and `ns`):


```
 Method |    AvrTime |
------- |----------- |
 Sqrt13 | 60.7802 ns |
 Sqrt14 |  1.6146 ms | 
``` 

To instead have this:

```
 Method |       AvrTime |
------- |-------------- |
 Sqrt13 |    60.7802 ns |
 Sqrt14 | 1,614.6000 ns | 
``` 

If this is what you mean, would be nice. Anything which makes it easier to understand the results and harder to misinterpret is a good thing in my book.

The whole reporting is a large area -- some people built entire careers on that! You could get quite deep into that quite quickly :)

It might be worth to review overall reporting at some point, and perhaps even split the benchmarker into the Engine and Reporting parts altogether. 

But on the other hand -- there is `dnx` and friends.  Is it more important to have support for `dnx` instead?

**Comment by AndreyAkinshin** [comment]
> If this is what you mean, would be nice.

Yep. In addition I want something like this

```
 Method |    AvrTime | StdDev |
------- |----------- |--------|
 Sqrt13 |        6ms |  0.6ms |
```
instead of
```
 Method |    AvrTime | StdDev |
------- |----------- |--------|
 Sqrt13 |        6ms |  600us |
```

What do you think?

> It might be worth to review overall reporting at some point, and perhaps even split the benchmarker into the Engine and Reporting parts altogether. 

It is a good point. I think, the reporting part is very important. BenchmarkDotNet users should easily understand benchmarks results.

>  Is it more important to have support for dnx instead?

It is a good point too. I will do it in the nearest future.

**Comment by ppanyukov** [comment]
Oh yes, across columns too of course.

OK, let me play around with BenchmarkDotNet a bit more.  I wanted to incorporate some of the my own benchmarks I have into this and see which tool reports what.

I will probably have a deeper look into the reporting after this.  I have some ideas what might be of interest and useful on the reporting side.

**Comment by AndreyAkinshin** [comment]
@ppanyukov, It would be great. PRs are welcome!

**Comment by ppanyukov** [comment]
And I had a question. What's all this logic around `areSame`? Not entirely very obvious to me.

![screen shot 2015-07-30 at 17 01 30](https://cloud.githubusercontent.com/assets/300031/8988467/312a7934-36de-11e5-998a-c0da36b2852d.png)

**Comment by AndreyAkinshin** [comment]
It code needs some refactoring =)

We have big amount of different parameters for each benchmark: Platform, Jit, Framework, and so on. However, some parameters have the same value for each benchmark. For example, if all of our benchmark have the same value of Jit, I mark the corresponded column with `areSame[colIndex] = true` (here `colIndex` is the index of the Jit column), print it once before the table, and skip it in the table. The first row of the table is the parameters titles. Last three columns are `AvrTime`, `StdDev`, `op/sec`, we always print it. Some additional comment to the picture

Red rectangle 1. Initializing all values of `areSame` with `true` except last 3 columns. If we have a single benchmark (`rowCount == 2`), we should to initialize all with `false` (we will print all of the columns).
Red rectangle 2. If there are two different values in the column, `areSame[colIndex] = false`.
Red rectangles 3, 4: print values of the `areSame` column before the table.

It would be cool, if you make the code more readable.

**Comment by ppanyukov** [comment]
Makes perfect sense now. I will definitely refactor as part of "look into reporting". Leave it with me. I may need to ask you more questions, hope not too many.

**Comment by AndreyAkinshin** [comment]
Feel free to ask any questions and thank you for your contribution.

**Comment by mattwarren** [comment]
> Instead of potentially having something like this (mixed ms and ns):

> Method |    AvrTime |
 ------- |----------- |
 Sqrt13 | 60.7802 ns |
 Sqrt14 |  1.6146 ms | 
To instead have this:

> Method |       AvrTime |
------- |-------------- |
 Sqrt13 |    60.7802 ns |
 Sqrt14 | 1,614.6000 ns | 

This has caught me out a few times and I agree that it needs to be consistent, i.e. all "ms" or all "ns".

But maybe there could also be a command line switch to control it, i.e. you could specify `-scale=ns` or `-scale=ms` and have that used across all results (but maybe `scale` isn't the best name for it?)

**Comment by AndreyAkinshin** [comment]
@mattwarren, I think, the consistent measure units should be the default option. However, I have no objection against the use of some additional command line arguments for customization.

**Comment by mattwarren** [comment]
@AndreyAkinshin yeah I wasn't clear, I agree that consistent measure units should be the default, but having a switch that allows **all** results to be in another (single) unit would be nice.

The only issue with *consistent measure units* is what unit to choose? Probably `ns` (considering the type of micro-benchmarks most people do), but it might need to be a bit more intelligent than that.

**Comment by AndreyAkinshin** [comment]
@mattwarren, I think, that we should automatically choose the best measure unit which is the best for maximum measure time across all benchmarks.

**Comment by ppanyukov** [comment]
Current idea for implementation:

- go through all measurements
- pick the smallest measurement
- see which unit to report this smallest measurement as per current logic
- use that unit for all other measurements.

This way we pick the largest unit which can still report the smallest measurement reliably without loss of precision.

Hope this makes sense?

Perhaps there are other ideas too.

**Comment by AndreyAkinshin** [comment]
@ppanyukov, yes, it makes sense, let's try.

**Comment by ppanyukov** [comment]
So I did this in a quick and dirty-ish way just to see how this is going to look if we used the same time unit across both `AvrTime` and `StdDev`.   And results are:

```
               Method |         AvrTime |      StdDev | op/s |
--------------------- |---------------- |------------ |----- |
                Sleep | 100,639.5678 us | 106.0010 us | 9.94 |
 SleepWithDescription | 100,590.0777 us |  84.4005 us | 9.94 |
```

I'm not convinced :)

The fact that `StdDev` can in fact be very small may really ruin the usefulness of the `AvrTime`.

Perhaps just making sure it's the same time unit within one column would work better.

Thoughts?

**Comment by AndreyAkinshin** [comment]
@ppanyukov, I think, in this case, we should print something like the following:
```
               Method |     AvrTime |    StdDev | op/s |
--------------------- |------------ |---------- |----- |
                Sleep | 100.6395 ms | 0.1060 ms | 9.94 |
 SleepWithDescription | 100.5900 ms | 0.0844 ms | 9.94 |
```
You should use only the `AvtTime` column for choosing primary time unit.

**Comment by ppanyukov** [comment]
Makes sense.

And if the StdDev happens to be smaller that 1/1000 of the primary unit (and displays 0.0000), we probably don't care much. Correct?

**Comment by AndreyAkinshin** [comment]
@ppanyukov, Yep, because we assume that the minimum `AvrTime` is greater than one primary unit.

**Comment by ppanyukov** [comment]
Almost done.  Running a special formatting benchmark gives me this:

```
  Method |        AvrTime |      StdDev |       op/s |
-------- |--------------- |------------ |----------- |
 Slower1 |      1.8112 us |   0.2015 us | 552,120.14 |
 Slower2 |      2.4149 us |   0.2425 us | 414,095.82 |
 Slower3 |      9.0558 us |   0.3052 us | 110,426.47 |
 Slower4 |     81.2006 us |   1.2585 us |  12,315.18 |
 Slower5 |  4,148.1727 us | 740.3897 us |     241.07 |
 Slower6 | 15,047.0119 us |  99.5290 us |      66.46 |
```

Looks pretty good to me.

If everyone is happy, PR will be on the way shortly.

**Comment by AndreyAkinshin** [comment]
LGTM

**Comment by mattwarren** [comment]
LGTM
