### ISSUE TITLE
Build warnings after update to 0.9.5

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#161]
Real-world repro: https://ci.appveyor.com/project/andrewvk/codejam/build/1.0.514#L28

Steps to reproduce:
 1. Create a new project that targets 4.6 or higher
 2. Install BenchmarkDotNet 0.9.5. packages.
 3. Rebuild the project. There will be a warning:

 ```
 Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed
 ```
 4. Check the versions of the Microsoft.Build and the Microsoft.Build.Framework assemblies in the project references. These are resolved as v4.0. 
To fix the warnings the references should include exact versions of the assemby, [like this](https://github.com/rsdn/CodeJam/commit/4a31cf2c6b254e19f7709795c75cff420a5b2252).

**Comment by AndreyAkinshin** [comment]
@ig-sinicyn, thanks for the report.

@adamsitnik, can you take a look?

**Comment by adamsitnik** [comment]
It is really weird. The project references [14.0.0.0 dlls](https://github.com/PerfDotNet/BenchmarkDotNet/blob/develop/BenchmarkDotNet/project.json#L58-L60). But if you rebuild the solution and go to `artifacts\bin\BenchmarkDotNet\Release\BenchmarkDotNet.0.9.5-develop.nupkg` extract it and open nuspec file, then you can see that versions are not set!!


```xml
<frameworkAssemblies>
            <frameworkAssembly assemblyName="Microsoft.Build" targetFramework=".NETFramework4.0" />
            <frameworkAssembly assemblyName="Microsoft.Build.Framework" targetFramework=".NETFramework4.0" />
            <frameworkAssembly assemblyName="Microsoft.Build.Utilities.v4.0" targetFramework=".NETFramework4.0" />
            <frameworkAssembly assemblyName="System.Management" targetFramework=".NETFramework4.0" />
            <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.0" />
            <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.0" />
            <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.0" />
            <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.0" />
            <frameworkAssembly assemblyName="Microsoft.Build" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="Microsoft.Build.Framework" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="Microsoft.Build.Utilities.v12.0" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="System.Management" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.5" />
            <frameworkAssembly assemblyName="Microsoft.Build" targetFramework=".NETFramework4.6" />
            <frameworkAssembly assemblyName="Microsoft.Build.Framework" targetFramework=".NETFramework4.6" />
            <frameworkAssembly assemblyName="Microsoft.Build.Utilities.Core" targetFramework=".NETFramework4.6" />
            <frameworkAssembly assemblyName="System.Management" targetFramework=".NETFramework4.6" />
            <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.6" />
            <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.6" />
            <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.6" />
            <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.6" />
            <frameworkAssembly assemblyName="System" targetFramework="DNX4.5.1" />
            <frameworkAssembly assemblyName="System.Runtime" targetFramework="DNX4.5.1" />
            <frameworkAssembly assemblyName="System.Management" targetFramework="DNX4.5.1" />
            <frameworkAssembly assemblyName="mscorlib" targetFramework="DNX4.5.1" />
            <frameworkAssembly assemblyName="System" targetFramework="DNX4.5.1" />
            <frameworkAssembly assemblyName="System.Core" targetFramework="DNX4.5.1" />
            <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework="DNX4.5.1" />
        </frameworkAssemblies>
```

I will google further

**Comment by adamsitnik** [comment]
@AndreyAkinshin 

Ok, I have removed the dependencies to MSBuild from BenchmarkDotNet package by setting "type": "build".

How does it work now:
1. User installs BenchmarkDotNet. VS does not add any references to MSBuild dlls as it used to do since 0.9.2, when we switched to project.json and generated nuspec file had changed.
2. Users runs some benchmarks: CLR is loading the mehod that references MSBuild and starts looking for all required dlls. For  the explicit version of MSBuild files: 4 or 12 or 15. GAC is the first place to search. If MSBuild is installed, which was so far mandatory, then these dlls are loaded from GAC. 
3. If user has no required MSBuild installed (let's say VS 2015 and .NET 4.5 target when we want MSBuild 12 but only MSBuild 14 is installed) then ClassicBuilder try block executes, fails to catch block with FileLoadException/FileNotFoundException and falls back to the bat-file.

It is still not perfect but should cover 99% windows cases. I tested it with local nuget feed and our development package and it works (see below).

![image](https://cloud.githubusercontent.com/assets/6011991/15100921/53b10be4-1581-11e6-997a-050588b6c100.png)


Does anybody know how does it work for Mono?

**Comment by AndreyAkinshin** [comment]
I think, we should migrate to Roslyn asap (see https://github.com/PerfDotNet/BenchmarkDotNet/issues/149). There are too many problems with MSBuild.

P.S. Develop version (with my [recent](https://github.com/PerfDotNet/BenchmarkDotNet/commit/c280565c88e330688e2ea0c37c06317ff1e22926) magic commit) works fine with Mono on my machine.

**Comment by adamsitnik** [comment]
> I think, we should migrate to Roslyn asap (see #149). There are too many problems with MSBuild.

@AndreyAkinshin I totally agree. If I only had some time to dig in the roslyn package..

> P.S. Develop version (with my recent magic commit) works fine with Mono on my machine.

I saw it! Impressive fix for a crazy runtime bug!

**Comment by AndreyAkinshin** [comment]
> If I only had some time to dig in the roslyn package..

It should be a simple issue. We should just execute `csc.exe` with correct arguments. =)
