### ISSUE TITLE
[Bug] Platform.AnyCpu builds as x86.

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#163]
**UPD** My fault. Platform was set to host, and the studio was configured to run tests as x86.

Sorry :)

Old text:

The project emitted for the benchmark misses the
```
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
```
tag. Without this the project is compiled as `// Architecture: x86`, can be easily checked with ilspy.

Also, there should be warning for "x86, RyuJit" combo as there's no RyuJit for x86.

**Comment by adamsitnik** [comment]
>  there should be warning for "x86, RyuJit" combo as there's no RyuJit for x86.

but this is still valid ;)
