### ISSUE TITLE
Suggestion: Attribute Config style

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#166]
### Current situation

Today we have two main ways to create a config: object style and command style. The object style is great, it is a very flexible way to create any config you want. The command style is also great, it allows to use the config the command line format.

However, there is no simple way to create a simple config. For example, I just want to add a single diagnoser or exporter or job. For now I should create a separated config class or try to remember special command line values.

### Suggestion

There is a cool ability to create several config attributes which will be merged. We already use this feature in order providers. An example:

```cs
[OrderProvider(SummaryOrderPolicy.FastestToSlowest, MethodOrderPolicy.Declared)]
[DryConfig]
public class IntroOrderAttr
```

Here both `DryConfig` and `OrderProvider` are `IConfigSource`s. I think it would be cool to add some predefined config sources for common scenarios. And it is really easy to implement right now, the infrastructure is ready. We should just add new attributes.

### Possible implementations
* **Implementation 1**
```cs
[RPlotExporter]
[GcDiagnoser]
[DryJob]
public class MyBenchmark
```

*Advantages:* It is super-easy to implement.

*Disadvantages:* It is hard to discover available attributes for user.

* **Implementation 2**
```cs
// Here MyExporters, MyDiagnosers, MyJobs are enums
[Exporter(MyExporters.RPlot)]
[Diagnoser(MyDiagnosers.Gc)]
[Job(MyJobs.Dry)]
public class MyBenchmark
```

*Advantages:* It is easy to discover available attributes, code completion will help you. Also it would be cool to map enum values to our predefined values from command line style.

*Disadvantages:* I don't know a nice name for these enums. Obviously `MyExporters`, `MyDiagnosers`, `MyJobs` are ugly names (I use only as an example). We also can't use names like `Job` because `Job` is a class name. I thought about `PredefinedJob` or `BenchJob` but it also looks ugly. Any ideas?

### Discussion

@mattwarren, @adamsitnik, what do you think?

**Comment by GiorgiStoynev** [comment]
Hi, I am not familiar with the intrinsics of the project and specifically with those relating to example and proposed attributes, but just from looking at your comments, it looks like it might be possible to perhaps call your "Implementation 2" methods "ConfigureXYZ" and then use "Exporter", "Diagnoser", "Job" for the enum names.

**Comment by adamsitnik** [comment]
Personally I don't like creating new type every time so I always use our fluent api.

Sample:
```
BenchmarkRunner
    .Run<Algo_Md5VsSha256>(
        ManualConfig
            .Create(DefaultConfig.Instance)
            .With(Job.RyuJitX64)
            .With(Job.Core)
            .With(ExecutionValidator.FailOnError));
```

I find it very flexible and easy to use. What I have noticed is  that people tend to have single Config class and reuse it amongst all benchmarks they have.

**Comment by AndreyAkinshin** [comment]
I have implemented "Implementation 1". Looks nice. =)
