### ISSUE TITLE
NRE in Summary indexer property.

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#174]
Bench.Net 0.9.6

**Use case:**  benchmark with failed validation (e.g. debug build run with `JitOptimizationsValidator.FailOnError`).
The code tries to get a report for the benchmark calling `summary[benchmark]`. The call is failed with null reference exception as `summary.reportMap` field is null.

**Expected behavior:**
`summary[benchmark]` should return null if there's no report for a benchmark.
-or-
the indexer should throw an ArgumentException AND there should be a way to check for case 'there's no report for the benchmark'.

**Workaround:** just select the report using the `Summary.Reports` property.

**Comment by AndreyAkinshin** [comment]
@ig-sinicyn, fixed, now it returns `null`. Also you have a new useful method: `Summary.HasReport(Benchmark benchmark)`.
