### ISSUE TITLE
Job.GetAllProperties(): old property names are used

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#179]
in  `JobExtensions.cs`:
```
                new Property("Warmup", job.WarmupCount.ToString()),
                new Property("Target", job.TargetCount.ToString()),
                new Property("Process", job.LaunchCount.ToString()),
```

Should be `nameof(IJob.WarmupCount)`, `nameof(IJob.TargetCount)` and `nameof(IJob.LaunchCount)`, I guess.

**Comment by mattwarren** [comment]
cheers to noticing this, yeah using `nameof(..)` would be nicer. 

I'll take a look and if it doesn't break anything I'll make the change
