### ISSUE TITLE
Ability to have custom output column

### ISSUE THREAD

**Issue by Bobris** [PerfDotNet/BenchmarkDotNet#180]
Usecase would be benchmark of serialization so column could contain serialized size in bytes.
It could be set already from Setup method or return value from benchmark method itself (both options would work for me).

**Comment by AndreyAkinshin** [comment]
We already support custom columns. (E.g. see https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet.Samples/Intro/IntroTags.cs, https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Columns/Column.cs). It it ok for you or you want to have a predefined column which shows the return value?

**Comment by Bobris** [comment]
Custom columns are nice and could be solution though manual, or is there way somehow pass value from benchmark or setup method back to Benchmark instance?

**Comment by AndreyAkinshin** [comment]
There is only one way: you should use reflection. `Benchmark.Target` contains the following information:
```cs
public Type Type { get; }
public MethodInfo Method { get; }
public MethodInfo SetupMethod { get; }
```

**Comment by Bobris** [comment]
Thanks, will think about it...

**Comment by Bobris** [comment]
This is what I created - It looks like huge hack, but I was not able to come up with anything easier.
https://github.com/Bobris/BTDB/blob/bd1cd1ecc825e74c156fbe23c126fd582dd505c9/SimpleTester/EventSerializationBenchmark.cs#L86
