### ISSUE TITLE
[Suggestion] Make ValidationError public

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#183]
Bench.Net 0.9.6,  `BenchmarkDotNet.Validators.ValidationError` is declared as internal. 
As a result, custom validators had to reimplement the `IValidationError` to report validation errors.

**Comment by adamsitnik** [comment]
There was no need for the interface, sorry for that. I have removed it and make the class public.

**Comment by ig-sinicyn** [comment]
@adamsitnik 

>There was no need for the interface, sorry for that. I have removed it.

Will not be better to maintain same style across all messages (validation errors, analyser warnings etc)?

As for me all of them should be either an interface or a class.

**Comment by adamsitnik** [comment]
@ig-sinicyn Sure. I plan some refactoring for what is public/internal for next version, will take care of this too.
