### ISSUE TITLE
Report if difference between 2 benchmarks is statistically significance

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#185]
I just came across [tinystat](https://github.com/codahale/tinystat), which is a nice go tool. Basically it  that tells you if the difference between 2 benchmarks is statistically different/significant, from the README: 

> A Go library and command for evaluating whether two or more sets of measurements are statistically different. It does this by performing a Student's t-test at a particular confidence level, making it suitable for small sets of measurements (e.g., multiple runs of a benchmark). It's inspired largely by FreeBSD's ministat (written by Poul-Henning Kamp).

There's also some more info in the [godoc](https://godoc.org/github.com/codahale/tinystat/cmd/tinystat) for the command:

```
$ tinystat iguana chameleon leopard

 1.5 k  +
        |
        |
        |
        |
        |
  1000  +                                             |
        |                              |              |
        |                        +-----------+  +-----------+
        |              |         |           |  |           |
        |              |         |           |  +-----*-----+
        |              |         |     *     |  |           |
   500  +              |         +-----------+  +-----------+
        |        +-----------+   |           |        |
        |        |     *     |   +-----------+
        |        +-----------+         |
        |        +-----------+         |
     0  +--------------|-----------------------------------------------
                    iguana         chameleon       leopard

Experiment  Results
chameleon   No difference proven at 95% confidence.
leopard     Difference at 95% confidence!
              343.5 +/- 292.63453863922877
              114.5% +/- 97.54484621307626%
              (Student's t, pooled s = 238.9799344943192)
```

@AndreyAkinshin do you think that it's worth having something like this in BenchmarkDotNet? I guess it could be implemented as an `IColumn` that could be added to the output.

**Comment by AndreyAkinshin** [comment]
LGTM.

**Comment by AndreyAkinshin** [comment]
@mattwarren, ok, now we have the `RankColumn` which is based on [Welch's t-test](https://en.wikipedia.org/wiki/Welch%27s_t-test).
