### ISSUE TITLE
Ability to manage GC mode: turn on/off the Server/Concurrent GC modes and extend to CPU groups

### ISSUE THREAD

**Issue by alexandrnikitin** [PerfDotNet/BenchmarkDotNet#188]
About GC modes: https://msdn.microsoft.com/en-us/library/ee787088(v=vs.110).aspx#Anchor_9

The Concurrent GC flag: https://msdn.microsoft.com/en-us/library/yhwwzef8(v=vs.110).aspx
The Server GC flag: https://msdn.microsoft.com/en-us/library/ms229357(v=vs.110).aspx
The GC CPU Groups flag: https://msdn.microsoft.com/en-us/library/hh925566(v=vs.110).aspx

Also printing current GC mode will be useful too.

**Comment by adamsitnik** [comment]
The only thing I need to know is how to expose the configuration in the api. [IJob interface](https://github.com/PerfDotNet/BenchmarkDotNet/blob/5191bc98e19d97dce83fd944172d9fe491d7f8de/BenchmarkDotNet/Jobs/IJob.cs) is already big.

What do you say for a new property, called RuntimeSetting, which would be an `[Flag]`enum and would contain [all performance-related the features](https://msdn.microsoft.com/en-us/library/0kk0kk35(v=vs.110).aspx) of `<runtime>`node?

Sample usage would be
`job.RuntimeSettings = RuntimeSettings.ServerGC | RuntimeSettings.ConcurrentGC`

**Comment by alexandrnikitin** [comment]
Yeah, that stopped me too. We need input from @AndreyAkinshin, @mattwarren here.

**Comment by mattwarren** [comment]
Quick question, can this issue be handled by #108? 

I.e. if you want a particular setting you just specify it in the `app.config` of your benchmark project and then when #108 is done, it'll be copied across by BenchmarkDotNet and used when the Benchmark is actually run?

**Comment by adamsitnik** [comment]
> Quick question, can this issue be handled by #108?

@mattwarren Yes and no. The scenario where somebody would like to compare two different GC modes would not be supported.

**Comment by mattwarren** [comment]
> Yes and no. The scenario where somebody would like to compare two different GC modes would not be supported.

Ahh good point, I forgot about the scenario where you want to use compare multiple modes.

> What do you say for a new property, called RuntimeSetting, which would be an `[Flag]` enum and would contain all performance-related the features of `<runtime>` node?
> Sample usage would be `job.RuntimeSettings = RuntimeSettings.ServerGC | RuntimeSettings.ConcurrentGC`

Agree, this is a nice way of doing it, adding lots more fields to `IJob` would make it messy.

The other option is to make `RuntimeSettings` a simple class, like so:

``` csharp
public class RuntimeSettings
{
    public bool ServerGC { get; set; }
    public bool ConcurrentGC { get; set; }
    ....
}
```

Then you can write code like this:

``` csharp
Job.Default.With(new RuntimeSettings { ServerGC = true, ConcurrentGC = true, ...});
```

Would that work? (although after writing it, I'm not sure if it's nicer or not!?)

**Comment by Zoxive** [comment]
Is there anyway to make RuntimeSettings extendable so inside my Benchmark Class -> Setup i can access the properties on it?

Ex
```csharp
public class MyRuntimeSettings : RuntimeSettings
{
    public bool MySpecialSetting { get; set; }
    ....
}

public class DeserializeRules
{
    [Setup]
    public void Setup()
    {
        //do something with runtime settings
        _runtimeSettings.MySpecialSetting
    }
}

**Comment by adamsitnik** [comment]
Ok, implemented, also with .NET Core support ;) [API](https://github.com/PerfDotNet/BenchmarkDotNet/blob/Roslyn/BenchmarkDotNet/Jobs/GC.cs)

Sample usage:
```cs
var config = ManualConfig.CreateEmpty().With(Job.Dry.With(new Jobs.GC { Server = true }));
```

**Comment by adamsitnik** [comment]
@Zoxive Sorry, this scenario is not supported. Maybe [Params](https://github.com/PerfDotNet/BenchmarkDotNet/tree/Roslyn#params) is what you need?

**Comment by alexandrnikitin** [comment]
I'm happy to close the issue. Thank you @adamsitnik

**Comment by adamsitnik** [comment]
@alexandrnikitin you  welcome! Please take a lookg at #211 You might want to try it as well.

How to use:

```cs
Job.Default.With(
    new GarbageCollection
    {
        Server = true,
        Concurrent = true,
        CpuGroups = true,
        Force = false
    });
```

**Comment by adamsitnik** [comment]
We keep issues open with "fixed in develop" tag as long as the new version with the change is not released to Nuget. So I will reopen this one ;)
