### ISSUE TITLE
Framework settings in Jobs

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#194]
I'm not sure what the expected behaviour is supposed to be, but I don't think we're handling the `Framework` setting in the right way.

For instance, if you write a `Config` like so, would you expect it to run your benchmarks twice, once under `.NET 4.5.2` and once under `.NET 4.6`?

``` csharp
private class Config : ManualConfig
{
	public Config()
	{
		Add(new Job { Framework = Framework.V452 });
		Add(new Job { Framework = Framework.V46 });
                ....
	}
}
```

Well it doesn't and I'm not sure if it's even possible? Since .NET 4.0 all the [updates have been in-place](http://weblog.west-wind.com/posts/2012/Mar/13/NET-45-is-an-inplace-replacement-for-NET-40), i.e they install on-top of each other. AFAIK I know if you have .NET 4.6 installed, there's not a way to tell it behave like .NET 4.5 at runtime. The only setting you seem to have is [`<supportedRuntime version="<version>"/>`](https://msdn.microsoft.com/en-us/library/jj152935(v=vs.110).aspx), but that doesn't seem to offer what we'd need.

What we do change is the `<TargetFrameworkVersion>` setting in the `Program.csproj` we generate. This affects what happens at compile-time, but only effects the compilation of the scaffolding code that BenchmarkDotNet generates, not any of the user code that is annotated with `[Benchmark]` as that has already been compiled. To really change the users benchmark code, they would have to change their project settings, which BenchmarkDotNet can't do:

![image](https://cloud.githubusercontent.com/assets/157298/15675199/9e5ee3be-2738-11e6-8476-62e609f14c4c.png)

I came across this because I wanted to check out the [`Array.Empty<T>` optimisation](https://github.com/dotnet/roslyn/pull/1117) that the Roslyn compiler added in .NET 4.6 (see [some of it's perils](https://github.com/dotnet/roslyn/issues/4889) and more info [here](https://github.com/dotnet/roslyn/issues/1103#issuecomment-136125635)). So I wanted to write some code and then see the difference between the old `.NET 4.5.2` behaviour and the optimised `.NET 4.6` version.

Thoughts, idea? Am I doing it wrong?

Is this something we even want to support? If not, why do we allow specifying the `Framework` value, does it even make sense? Especially if we plan to [remove .NET 3.5](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Jobs/Framework.cs#L5-L9) and only allow .NET 4.0 and upwards.

What's a valid reason for specifying the `Framework` value in a job?

**Comment by ig-sinicyn** [comment]
@mattwarren Actually, there is, however it's almost undocumented and it changes not so much.

I'm talking about `<supportedRuntime>`'s [SKU attribute](http://stackoverflow.com/questions/17148496/what-does-sku-attribute-mean-in-c).
It's [per-appdomain setting](https://msdn.microsoft.com/en-us/library/system.appdomainsetup.targetframeworkname(v=vs.110).aspx) and [there's list](https://msdn.microsoft.com/en-US/library/dn458358(v=vs.110).aspx) of what it changes (look for retargeting changes sections).

Bad news: there're some compile-time retargeting changes (to be honest I can remember only the one with `Array.Empty<T>`). And there're runtime changes you cannot toggle at all. 

So, I'm second here. Don't see any reason to keep the Framework option at all.
 
As a sidenote. I'd propose to enable validators that can be run in same process the benchmark is run. It will allow to detect cases when environment does not match job settings.
Something [like this](https://github.com/rsdn/CodeJam/blob/master/PerfTests/src/%5BL1_InProcess%5D/Validators/InProcessValidator.cs#L22), I guess.

**Offtopic:** what about [#190](https://github.com/PerfDotNet/BenchmarkDotNet/issues/190#issuecomment-222147413)? Still waiting for comments before doing PR (there were minor changes but [the code](https://github.com/rsdn/CodeJam/blob/master/PerfTests/src/%5BL3_CompetitionsCore%5D/Loggers/HostLogger.cs) is pretty much the same):)

**Comment by mattwarren** [comment]
> I'm talking about <supportedRuntime>'s SKU attribute.
It's per-appdomain setting and there's list of what it changes (look for retargeting changes sections).

Hmm, seems I misunderstood what `<supportedRuntime>` actually does. Although as you say, it's still limited, i.e it only changes the behaviour of "Retargeting changes" (am I understanding correctly?)

> As a sidenote. I'd propose to enable validators that can be run in same process the benchmark is run. It will allow to detect cases when environment does not match job settings.

Yeah that would be nice, the more validators the merrier!! I've been saved from producing bad benchmark results several times, thanks to `JitOptimizationsValidator.FailOnError`

> **Offtopic:** what about #190? Still waiting for comments before doing PR (there were minor changes but the code is pretty much the same):)

Sorry, I completely forgot about that, I'll take a look now.

**Comment by ig-sinicyn** [comment]
> i.e it only changes the behaviour of "Retargeting changes" (am I understanding correctly?)

Yep. At least as far as I know. [Here's example](http://referencesource.microsoft.com/#mscorlib/system/compatibilityswitches.cs,31) of settable compatibility switches.

>Yeah that would be nice, the more validators the merrier!! 
Ok. Will fill an issue.

**Comment by mattwarren** [comment]
> Yep. At least as far as I know. Here's example of settable compatibility switches.

Oh I see, so it's not a runtime-wide settings, i.e. "Enable all 4.5.1 comparability switches" (when running under 4.5.1 for example), it's per feature, i.e. "NetFx40_TimeSpanLegacyFormatMode" or "NetFx40_LegacySecurityPolicy".

**Comment by ig-sinicyn** [comment]
@mattwarren as far as I can remember these switches are also toggled on or off depending on SKU. Could not find a good proof as I've looked at the code a year or two ago.

**Comment by mattwarren** [comment]
@AndreyAkinshin @adamsitnik have you got any objections to the `Framework` setting being removed? (see the top of this thread for the reasons)

**Comment by AndreyAkinshin** [comment]
No objections.

**Comment by adamsitnik** [comment]
> No objections.

Same here. The less settings the better! I think that we should make it [Obsolete] first to not break people's code.

**Comment by mattwarren** [comment]
thanks, I'll go ahead and make the changes

**Comment by adamsitnik** [comment]
@mattwarren I have removed it just to make sure we don't release new version with settings that can affect nothing (after moving to Roslyn it's irrelevant)

**Comment by mattwarren** [comment]
@adamsitnik thanks for doing that

I tried to do it myself the other week but found that `Framework` was being used by the `Toolchain` code and so I left it till the Roslyn work was done.

**Comment by Tornhoof** [comment]
You should probably remove it from documentation too: https://perfdotnet.github.io/BenchmarkDotNet/Configuration/Jobs.htm

**Comment by AndreyAkinshin** [comment]
@Tornhoof, Thanks for the notice. However, in the next version of BenchmarkDotNet, we have a lot of improvements in the API and we have completely rewritten documentations for Jobs: https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/docs/guide/Configs/Jobs.md
