### ISSUE TITLE
"Dotnet restore has failed" exception during dotnet run

### ISSUE THREAD

**Issue by lukasz-pyrzyk** [PerfDotNet/BenchmarkDotNet#195]
I have a problem with running simple benchmark. After typing "dotnet run" or starting from VS, exception occurs. 

> // *** Build ***
> Errors in C:\Users\lpyrz\Source\Repos\Kronos\BDN.Auto\project.json
>     Unable to resolve 'Kronos.Benchmark (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
> // Result = Failure
> // Exception: dotnet restore has failed
> 

What is wrong?
Platform: .NET Core RC2 (1.0.0-preview1-002702)

```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

namespace Kronos.Benchmark
{
    public class Program
    {
        public static void Main(string[] args)
        {
            BenchmarkRunner.Run<StoragePerformance>();
        }
    }

    public class StoragePerformance
    {
        [Benchmark]
        public void DoWork()
        {
            // TODO
        }
    }
}

```

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "BenchmarkDotNet": "0.9.7-beta"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002702"
        },
        "System.ComponentModel.EventBasedAsync": "4.0.11-rc2-24027"
      }
    }
  }
}
```

**Comment by adamsitnik** [comment]
Hej!

Thanks for trying our RC2 bits!

Could you please try running with:
`BenchmarkRunner.Run<StoragePerformance>(DefaultConfig.Instance.KeepBenchmarkFiles());`

then find the auto-generated folder (it should appear in solution's root folder) with project.json,  Program.cs files and run the `BuildBenchmark.bat` and paste the output + the generated project.json file content here?

**Comment by lukasz-pyrzyk** [comment]
Here you go:

> 
> C:\Users\lpyrz\Source\Repos\Kronos\StoragePerformance_DoWork>call dotnet restore --fallbacksource https://dotnet.myget.org/F/dotnet-core/api/v3/index.json 
> log  : Restoring packages for C:\Users\lpyrz\Source\Repos\Kronos\StoragePerformance_DoWork\project.json...
> info :   GET https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.netcore.dotnethostresolver/index.json
> info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.netcore.dotnethostresolver/index.json
> info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json
> info :   CACHE https://ci.appveyor.com/nuget/xgain/FindPackagesById()?id='Microsoft.NETCore.DotNetHostResolver'
> info :   CACHE https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.dotnethostresolver/index.json
> info :   GET https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/kronos.benchmark/index.json
> info :   GET https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/kronos.benchmark/index.json
> info :   GET https://api.nuget.org/v3-flatcontainer/kronos.benchmark/index.json
> info :   CACHE https://ci.appveyor.com/nuget/xgain/FindPackagesById()?id='Kronos.Benchmark'
> info :   GET https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/kronos.benchmark/index.json
> info :   NotFound https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.netcore.dotnethostresolver/index.json 787ms
> info :   GET https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.netcore.dotnethost/index.json
> info :   CACHE https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/microsoft.netcore.dotnethost/index.json
> info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json
> info :   CACHE https://ci.appveyor.com/nuget/xgain/FindPackagesById()?id='Microsoft.NETCore.DotNetHost'
> info :   CACHE https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/microsoft.netcore.dotnethost/index.json
> info :   NotFound https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/microsoft.netcore.dotnethost/index.json 210ms
> info :   NotFound https://myget-2e16.kxcdn.com/artifacts/xunit/nuget/v3/flatcontainer/kronos.benchmark/index.json 968ms
> info :   NotFound https://myget-2e16.kxcdn.com/artifacts/aspnetcidev/nuget/v3/flatcontainer/kronos.benchmark/index.json 966ms
> info :   NotFound https://api.nuget.org/v3-flatcontainer/kronos.benchmark/index.json 1274ms
> info :   NotFound https://dotnetmyget.blob.core.windows.net/artifacts/dotnet-core/nuget/v3/flatcontainer/kronos.benchmark/index.json 1571ms
> error: Unable to resolve 'Kronos.Benchmark (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
> info : Committing restore...
> log  : Lock file has not changed. Skipping lock file write. Path: C:\Users\lpyrz\Source\Repos\Kronos\StoragePerformance_DoWork\project.lock.json
> log  : C:\Users\lpyrz\Source\Repos\Kronos\StoragePerformance_DoWork\project.json
> log  : Restore failed in 2438ms.
> 
> Errors in C:\Users\lpyrz\Source\Repos\Kronos\StoragePerformance_DoWork\project.json
>     Unable to resolve 'Kronos.Benchmark (>= 1.0.0)' for '.NETCoreApp,Version=v1.0'.
> 
> NuGet Config files used:
>     C:\Users\lpyrz\Source\Repos\Kronos\NuGet.Config
>     C:\Users\lpyrz\AppData\Roaming\NuGet\NuGet.Config
>     C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
> 
> Feeds used:
>     https://www.myget.org/F/xunit/api/v3/index.json
>     https://www.myget.org/F/aspnetcidev/api/v3/index.json
>     https://api.nuget.org/v3/index.json
>     https://ci.appveyor.com/nuget/xgain
>     C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
>     https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
> 
> C:\Users\lpyrz\Source\Repos\Kronos\StoragePerformance_DoWork>call dotnet build --framework netcoreapp1.0 --configuration Release --output binaries 
> Can not find runtime target for framework '.NETCoreApp,Version=v1.0' compatible with one of the target runtimes: 'win10-x64, win81-x64, win8-x64, win7-x64'. Possible causes:
> 1. The project has not been restored or restore failed - run `dotnet restore`
> 2. The project does not list one of 'win10-x64, win81-x64, win8-x64, win7-x64' in the 'runtimes' section.
> 

```
{
  "title": "BenchmarkDotNet.Autogenerated",
  "version": "1.0.0-*",

  "compilationOptions": {
    "optimize": true,
    "allowUnsafe": true,
    "emitEntryPoint": true,
    "platform": "x64",
    "debugSymbols": "pdbOnly",
    "comment": "both platform key and debugSymbols seems to be not documented, found at https://github.com/aspnet/dnx/blob/e874201acc19854caff9236b420b2864152659c0/test/Microsoft.Dnx.Compilation.CSharp.Tests/ProjectExtensionsFacts.cs"
  },

  "compile": "Program.notcs",

  "commands": {
    "run": "BenchmarkDotNet.Autogenerated"
  },

  "dependencies": { "Microsoft.NETCore.App": { "version": "1.0.0-rc2-3002702" } },
  "runtimes": { "win10-x64": { } },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [ "dnxcore50", "portable-net45+win8", "dotnet5.6", "netcore50" ],
      "dependencies": {
        "Kronos.Benchmark": {
          "version": "1.0.0-*",
          "importantComment": "you must not set the target, otherwise restore will fail!!!",
          "dependenciesComment": "restore adds all of them in recursive way, so we only need this single one"
        }
      }
    }
  }
}
```

**Comment by lukasz-pyrzyk** [comment]
Hello @adamsitnik.

During last week I've decided to cleanup and reinstall all .NET Core components and benchmark works fine. I think we can close this issue because I am not able to reproduce this error. 

Thanks for your time and help. I'm going to use DotNetCorePerformance with .NET Core often, so I will try to give you a feedback.

Best
