### ISSUE TITLE
Allow specifying a gist url to RunUrl

### ISSUE THREAD

**Issue by hmemcpy** [PerfDotNet/BenchmarkDotNet#196]
It would be great if BDN could figure out the raw url itself, and download the content from a specified gist url, e.g.

    var url = "https://gist.github.com/mattwarren/d202a4cd3b62635b5220d6cb8c9eeac9"

or maybe even without the `https://gist.github.com/` part, just `mattwarren/d202a4cd3b62635b5220d6cb8c9eeac9`

**Comment by ig-sinicyn** [comment]
Just a sidenote: [here's](https://github.com/rsdn/CodeJam/blob/master/PerfTests/src/%5BL0_Core%5D/Helpers/BenchmarkHelpers.cs#L270) a helper that allows to retrieve text from url, absolute or relative path. Not tested well yet, hope to do it soon.

**Comment by AndreyAkinshin** [comment]
@hmemcpy, done: https://github.com/PerfDotNet/BenchmarkDotNet/commit/d448b4bfe44a886998134d71fc13548f83377e34
Now we are also support non-raw github url (not only gists).
