### ISSUE TITLE
Поддержка Roslyn Analysis ?

### ISSUE THREAD

**Issue by anykeysas** [PerfDotNet/BenchmarkDotNet#20]
А есть ли возможность использовав анализатор  выражений Roslyn автоматом обвязывать код тестируемого приложения бенчмарками? 
Вообще насколько была бы полезной такая фича?

**Comment by AndreyAkinshin** [comment]
Не совсем понял вашу идею. Можете привести пример?

**Comment by anykeysas** [comment]
Пример :
Хочу провести бенчмарк по методу во всех имплементирующих классах в проекте(более 20). С помощью Roslyn можно найти все такие методы. Но в разное время приходиться тестировать разные классы и интерфейсы поэтому написание такого кода начинает становиться рутиной. Или логичнее это все уносить в Unit Test'ы ?

**Comment by AndreyAkinshin** [comment]
Мне думается, что вы описываете очень частный случай, не очень представляю, как тут можно сделать универсальное решение. Скоро в BenchmarkDotNet появится параметризация (#8), на её основе с помощью рефлексии вашу идею можно будет реализовать в несколько строк.
По поводу запихивания бенчмарков в юнит-тесты тоже смысла не вижу: что в таких тестах будет проверяться?

**Comment by anykeysas** [comment]
Ждем параметризацию)))
В тестах будет проверяться скорость приложения в динамике разработки. т.е. обычно при первой реализации фич быстродействие куска кода проверяется, но затем после многочисленных фиксов и улучшений может получиться что производительность упала по сравнению с первоначальной реализацией, хотелось бы наверное наблюдать такие провалы производительности в ходе развития проекта.

**Comment by AndreyAkinshin** [comment]
Ваше желание понятно, но хочу сразу предостеречь, что к такому подходу нужно относиться очень аккуратно. Подобный анализ стоит проводить только в рамках одной машины (очевидно, что на разных машинах результаты могут значительно отличаться) + при отсутствии сторонних процессов. Скажем, если у вас на билд-сервере параллельно бенчмарку запуститься какая-нибудь другая задача, то результаты могут исказиться.
Кроме того, важно определить понятие «провал производительности».  BenchmarkDotNet рассчитан в первую очередь на микробенчмарки. Я его начал разрабатывать для своих задач, в которых счёт шёл на милисекунды. Если у вас аналогичная ситуация, то можно попробовать BenchmarkDotNet использовать, а если под провалом вы понимаете секунды, то, возможно, стоит поискать менее хардкорный инструмент.
Ещё один важный момент: для получения хорошей точности целевой метод нужно запускать очень много раз, бенчмаркинг одного метода может вполне занять несколько минут. Т.е. если вы хотите массово бенчмаркать сотни методов, то один такой запуск может вполне занять сутки.
Плюс к каждому бенчмарку нужно подходить крайне вдумчиво: крайне легко написать его криво и вместо производительности целевой логики померить производительность тысячи сайд-эффектов.
Резюмирую: бенчмаркинг — дело тонкое. Если подходить к делу с умом, то можно получить хорошее средство регрессионного анализа. Увы, история знает множество примеров того, как люди писали программы, которые кушали процессорное время и выдавали какие-то циферки.

**Comment by mattwarren** [comment]
@AndreyAkinshin any chance of a rough translation of this thread? I've done some work with Roslyn and this looks interesting, but Google Translate does do a great job

Or is it all solved by #8, which I *will* get round to soon, promise!

**Comment by AndreyAkinshin** [comment]
@mattwarren,
@anykeysas describes a BenchmarkDotNet use case and suggests to use Roslyn Analysis for that. But I think that he can solve his issue with help of parametrization without any dependencies to the Roslyn Analysis in the library.

**Comment by mattwarren** [comment]
That's cool, thanks for the info. Yeah, as we discussed before using Roslyn has some benefits, but it's also a limitation because you need .NET 4.5 installed
