### ISSUE TITLE
Third-party libraries must be explicitly included in test context to be loaded by runner

### ISSUE THREAD

**Issue by sergiorykov** [PerfDotNet/BenchmarkDotNet#203]
I wrote a benchmark in unittests.dll. It tests method from class A from a.dll. But A uses internally class B from b.dll. unittests.dll has link to b.dll.

Runner can't execute test because it can't load b.dll. When I add direct reference in test (in ctor or Setup) to any class from b.dll then it successfully completes.

To be able to test A from unittests I have to add reference to a third-party b.dll - without it test fails and cries about it. 

In case of running benchmarks it's not clear why I must add direct reference to b.dll (in test class or maybe somewhere in unittests.dll). I think it should be at least included in ValidationErrors. To prevent such kind of errors you can run sample for each benchmark in the same AppDomain where BenchmarkRunner.Run is being called and use list of dependencies from executing assembly (in this case from unittests.dll).

**Comment by adamsitnik** [comment]
Hello @sergiorykov 

I did not know about this limitation, thanks for pointing it out! 

I will try to fix it for 0.9.8

**Comment by sergiorykov** [comment]
Thanks!
