### ISSUE TITLE
Allow a [Cleanup] method to be specified

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#215]
To mirror the invocations of the `[Setup]` method, i.e.

- `[Setup]`
- Run and measure Benchmarks iterations
- `[Cleanup]`

This is useful when there is a resource that needs cleaning up after each set of iterations

**Comment by adamsitnik** [comment]
Good idea! I would also Dispose the object if it is IDisposable (at the end)

**Comment by mattwarren** [comment]
@adamsitnik I'm not following, which object do you mean?

**Comment by adamsitnik** [comment]
@mattwarren  the one that is implementing Benchmark method(s)

**Comment by AndreyAkinshin** [comment]
@mattwarren, can you write an example of benchmark where we need a cleanup method?

**Comment by mattwarren** [comment]
This idea came from [this tweet](https://twitter.com/Aaronontheweb/status/746085821359362048), but I'm not really sure of the exact scenario, I'll try and find out.

**Comment by DenisIstomin** [comment]
I think that Aaronontheweb (as a contributor to NBench) at [his tweet](https://twitter.com/Aaronontheweb/status/746085821359362048) said about "Cleanup" logic after **each** iteration. But BenchmarkDotNet uses "Setup" attribute for set of iterations called "Launch" (I hope so). That's why I think that "Cleanup" attribute could be used at benchmarks that do some work with "out of the process" resources - filesystem, for example.

**Comment by AndreyAkinshin** [comment]
It makes sense, but I still want to have a real use-case for cleanup.

**Comment by nblumhardt** [comment]
Hi all - thanks for the great project!

We're using BenchmarkDotNet to profile a [new Serilog "async" sink](https://github.com/serilog/serilog-sinks-async), and we need to:

 * Gracefully shut down worker threads
 * Delete temporary files (in a PR I'm working on)

...after running a benchmark. Without `[Cleanup]` it's hard to do this properly.

Does this cover the scenario information you need to consider including this feature?

Thanks!

**Comment by nblumhardt** [comment]
Ah, now I see the commit above - great! Sorry about the noise :-)

**Comment by adamsitnik** [comment]
@nblumhardt If you don't want to wait for 0.9.9 release you can download the pre-release package from our development feed `<add key="appveyor-bdn" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />`

If that's not an option you can add a finalizer to your benchmark class. But personally I don't like this workaround.
