### ISSUE TITLE
Update to .NET Core RTM

### ISSUE THREAD

**Issue by adamsitnik** [PerfDotNet/BenchmarkDotNet#216]
FYI I am working on that, will update nuget packages and drop dnxcore50/dnx451 support.

**Comment by adamsitnik** [comment]
Ok, it's done. 

@mattwarren @AndreyAkinshin @ig-sinicyn  You need to upgrade your tools, full description [here](https://github.com/PerfDotNet/BenchmarkDotNet/blob/Roslyn/DEVELOPING.md#building)

Breaking change: 

- I have dropped dnx451 and dnxcore50 support. (nobody should use it anymore)
- We will no longer need separate nuget package because of the beta dependencies

**Comment by niemyjski** [comment]
When will it be on nuget?

**Comment by adamsitnik** [comment]
> When will it be on nuget?

@niemyjski only @AndreyAkinshin can tell ;)

**Comment by AndreyAkinshin** [comment]
As soon as possible. I still have some troubles with the roslyn toolchain. =( Hopefully, end of this week.

**Comment by jdom** [comment]
:+1:

**Comment by niemyjski** [comment]
@AndreyAkinshin what issues are you running into?

**Comment by AndreyAkinshin** [comment]
@niemyjski, https://github.com/PerfDotNet/BenchmarkDotNet/issues/149#issuecomment-230132359
