### ISSUE TITLE
Errors in BenchmarkDotNet.Samples.FSharp.Core/projects.json

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#218]
Right now I have the following error when I'm trying to manage NuGet packages for BenchmarkDotNet.Samples.FSharp.Core (or whole solution) in VisualStudio 2015 Update 3:
![devenv_2016-07-03_03-37-56](https://cloud.githubusercontent.com/assets/2259237/16543146/bd3079aa-40cf-11e6-83c7-c8df0a78f98a.png)

**Comment by adamsitnik** [comment]
It's [nuget's bug](https://github.com/NuGet/Home/issues/3070). I just specified it in explicit way to workaround it.
