### ISSUE TITLE
Displaying MSBuild output

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#22]
A few times I've run into issues where the MSBuild task doesn't work and `// OveralResult = Failure` is printed. I'll post a separate issue for the exact problem, but I wondered if having a cut-down version of the MSBuild output is valuable? This would help diagnose why the build is failing, otherwise it's not obvious.

With a bit of playing around I've been able to get something like this working, note that all the text between `// Build:` and `// OveralResult = Failure` is coming from MSBuild.

![image](https://cloud.githubusercontent.com/assets/157298/9066557/5bcbc918-3ad0-11e5-8a82-5d9873f2434b.png)

What do you think? I can get it to display build errors and/or warnings if needed.

For comparison, this is a successful compile with only the warning(s) shown (but these could be hidden if desired, so that only errors are printed):

![image](https://cloud.githubusercontent.com/assets/157298/9066783/735ff21a-3ad1-11e5-8355-e8edcb120f82.png)

**Comment by AndreyAkinshin** [comment]
I think, we should print only build errors by default. Also we can print warnings in a special detail mode (see https://github.com/PerfDotNet/BenchmarkDotNet/issues/23#issuecomment-128143734).
