### ISSUE TITLE
A problem with System.Threading.Tasks

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#222]
I can't install the BenchmarkDotNet package from the local folder because of the following error:

> Error		Failed to add reference. The package 'BenchmarkDotNet' tried to add a framework reference to 'System.Threading.Tasks' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, you can use our develop NuGet feed for repro:
```xml
<add key="appveyor-bdn" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
```

**Comment by adamsitnik** [comment]
Ok, I can reproduce it on my machine, will fix asap

**Comment by adamsitnik** [comment]
@AndreyAkinshin I have make this dependency a nuget dependency, tested with local feed, will test again as soon as appveyor builds the new package

**Comment by niemyjski** [comment]
https://github.com/NuGet/Home/issues/3103 I'm seeing this in my own projects but it doesn't make any sense. I don't have any full framework dependencies.
