### ISSUE TITLE
[Breaking change] BenchmarkAttribute become sealed.

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#224]
Please, remove the sealed modifier from the `BenchmarkDotNet.Attributes.BenchmarkAttribute`. 

It's blocker for us as we're using custom attributes derived from the BenchmarkAttribute to annotate benchmarks with competition limits. For exampe:
```cs
	[Category("PerfTests: examples")]
	public class SimplePerfTest
	{
		private const int Count = 10 * 1000;

		[Test]
		public void RunSimplePerfTest() => Competition.Run(this, CompetitionHelpers.DefaultConfig);

		[CompetitionBaseline]
		public void Baseline() => Thread.SpinWait(Count);

		[CompetitionBenchmark(2.92, 3.05)]
		public void SlowerX3() => Thread.SpinWait(3 * Count);

		[CompetitionBenchmark(4.87, 5.07)]
		public void SlowerX5() => Thread.SpinWait(5 * Count);

		[CompetitionBenchmark(6.77, 7.05)]
		public void SlowerX7() => Thread.SpinWait(7 * Count);
	}
```

**Comment by adamsitnik** [comment]
@ig-sinicyn sorry for that, I will revert it today so you will be able to download nuget package from our dev feed with latest changes

**Comment by adamsitnik** [comment]
@ig-sinicyn Ok, I have restored it. I have also added test to prevent others from making the same mistake I did  with #57.

If you don't want to wait for 0.9.9 you can download 0.9.8.55 from our dev feed:

`<add key="appveyor-bdn" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />`
