### ISSUE TITLE
[Suggestion] Please, refactor the roslyn dependency into another package

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#225]
The BDN 0.9.8 includes a dependency on roslyn compiler package. This results in 42 additional nuget packages, 300+ mb of binaries in the packages folder and 17 (or so) additional assembly references. 

As for me it's too big overhead for the single library:)
And our perf tests project uses custom toolchain and therefore do not depend on roslyn at all. 

Can the dependency be refactored into separate opt-in package?

**Comment by adamsitnik** [comment]
All options are posted here: https://github.com/PerfDotNet/BenchmarkDotNet/issues/149#issuecomment-230132359

What it gives us is managed, type safe  api that allows us to compile C# apps not only on Windows but also also Unix and MacOC with Mono. So great gain, but not for free.

We could make it a package, but then it would complicate the usage for the end-users.

As for now I can's see a good solution. But I understand your point @ig-sinicyn

**Comment by AndreyAkinshin** [comment]
@adamsitnik, we can do the following:
* Add a package `BenchmarkDotNet.Core` which will include all infrastructure stuff.
* Add a package `BenchmarkDotNet.Toolchains.Roslyn` which will include all Roslyn stuff + dependencies.
* Add reference from `BenchmarkDotNet` to these two packages.

So, @ig-sinicyn will be able to use `BenchmarkDotNet.Core` with own custom toolchain, other end-users will be able to use `BenchmarkDotNet` (with two new dependencies) without any additional troubles.

**Comment by adamsitnik** [comment]
Ok, done. The disadvantage is that BenchmarkRunner and Switcher had to stay as part of BechmarkDotNet (not .Core) due to dependency to RoslynToolchain (unknown in BenchmarkDotNet.Core). Maybe there is some better solution, but I could not find it for this moment ;.

![image](https://cloud.githubusercontent.com/assets/6011991/16904084/6ca1f560-4c8f-11e6-9ac9-c377b0b1656d.png)

![image](https://cloud.githubusercontent.com/assets/6011991/16904087/81eee540-4c8f-11e6-98db-056e4a8d3736.png)

**Comment by ig-sinicyn** [comment]
@adamsitnik, as proposal:

What if the core logic of the BenchmarkRunner will be placed in .Core project in separate class and the BenchmarkRunner will just call its methods passing default toolchain as a call arg?

I've did something like this as we have [nUnit](https://github.com/rsdn/CodeJam/blob/3d09a525f92c071c6db16d0d567c2e5f3a63ec1d/PerfTests/src-NUnit/Competition.cs#L14)/[xUnit](https://github.com/rsdn/CodeJam/blob/3d09a525f92c071c6db16d0d567c2e5f3a63ec1d/PerfTests/src-xUnit/Competition.cs#L14)/[MsTest](https://github.com/rsdn/CodeJam/blob/3d09a525f92c071c6db16d0d567c2e5f3a63ec1d/PerfTests/src-MSTest/Competition.cs#L14) support, [console runner](https://github.com/rsdn/CodeJam/blob/3d09a525f92c071c6db16d0d567c2e5f3a63ec1d/PerfTests/src/[L6_AllTogether]/Running.Console/ConsoleCompetition.cs#L16) and also [self-testing runner](https://github.com/rsdn/CodeJam/blob/3d09a525f92c071c6db16d0d567c2e5f3a63ec1d/PerfTests/tests-nUnit/SelfTestingApi/SelfTestCompetition.cs#L13).

**Comment by adamsitnik** [comment]
@ig-sinicyn Good idea! I have implemented it right away, now you have `BenchmarkRunnerCore` that has single method exposed to `BenchmarkRunner` which can be also reused by you.

The definition:
`internal static Summary Run(Benchmark[] benchmarks, IConfig config, Func<IJob, IToolchain> toolchainProvider)`

Sample usage can be following:
`BenchmarkRunnerCore.Run(benchmarks, config, job => job.Toolchain);`
