### ISSUE TITLE
Suggestion: change default branch

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#227]
Now we use the `master` branch as a default branch which corresponds to the last stable release on NuGet.

**Advantages**
* If user open https://github.com/PerfDotNet/BenchmarkDotNet, he see actual documentation for the latest version.

**Disadvantages**
* We should mark fixed issues with the `fixed-in-develop` branch instead of closing
* It's hard to track milestone progress
* Sometimes we have PRs against the `master` branch instead of `develop`.

**Suggestion**
Make a new branch: `stable`, mark it as the default branch (so, it will be shown by default on https://github.com/PerfDotNet/BenchmarkDotNet/), move develop changes from `develop` to `master`, get rid of `fixed-in-develop` and close issues as soon as it will be fixed.

@mattwarren, @adamsitnik, what do you think?

**Comment by adamsitnik** [comment]
@AndreyAkinshin It would simplify our development process, I like it!

**Comment by AndreyAkinshin** [comment]
@mattwarren, are you ok with the suggested changes?

**Comment by mattwarren** [comment]
yeah I'm fine with that, it's a good idea

**Comment by AndreyAkinshin** [comment]
@adamsitnik, @mattwarren, done. Be careful, we don't have the `develop` branch anymore.

**Comment by mattwarren** [comment]
@adamsitnik @AndreyAkinshin I've finally getting round to doing some work on BenchmarkDotNet, what's the current situation with the branches? I can't see a `stable` branch as mentioned above, only a `master` one, should I commit against `master`?

**Comment by AndreyAkinshin** [comment]
@mattwarren, the stable branch is obsolete, we don't use it anymore. Push your changes in the master branch.

**Comment by mattwarren** [comment]
ah, that's cool, glad I wasn't going crazy
