### ISSUE TITLE
Suggestion: clean up the root folder

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#228]
Now we have a lot of directories in the root folder. I suggest to transform current layout to the following:
* `Sources` for `BenchmarkDotNet` and `BenchmarkDotNet.Diagnostics.Windows`
* `Tests` for all the test projects
* `Samples` for all the samples projects

@adamsitnik, @mattwarren, what do you think?

**Comment by adamsitnik** [comment]
@AndreyAkinshin  Good idea! It would help people understand our code faster. 
Maybe we should follow existing naming convention? I mean "src" and "tests". 

@ig-sinicyn would that make your merge with #155 much harder?

**Comment by AndreyAkinshin** [comment]
> I mean "src" and "tests". 

LGTM

**Comment by ig-sinicyn** [comment]
@adamsitnik
>@ig-sinicyn would that make your merge with #155 much harder?

Definitely no. I currently have no dependency on source level, only on Bench.Net binaries.

As a sidenote - the code for #155 works and I'm all in finshing the public API, xUnit test runner and the documentation for the project. I don't wont to do any backporting untill all this will be complete.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I can take this one, I will update all xprojs/csprojs and scripts

**Comment by AndreyAkinshin** [comment]
@adamsitnik, great, thanks!

**Comment by AndreyAkinshin** [comment]
@adamsitnik, can you also do the following:
* move `runCoreTests.cmd` and `runClassicTests.cmd` to `tests` (should be sync with appveyor)
* move `strongNameKey.snk` to `src` (should be sync with `project.json` files)

P.S. Do we really need two `NuGet.config` files (in the root folder and in the `.nuget` folder). Can we keep only one of them?

**Comment by AndreyAkinshin** [comment]
@adamsitnik, what do you think about my last comment?

**Comment by adamsitnik** [comment]
@AndreyAkinshin Sorry for lack of response for so long~

> move strongNameKey.snk to src (should be sync with project.json files)

this is currently impossible because we also sign some of our test projects in order to let them use some of our internals (internalsvisibleto)

> move runCoreTests.cmd and runClassicTests.cmd to tests (should be sync with appveyor)

will check, should be possible

> Do we really need two NuGet.config files (in the root folder and in the .nuget folder). Can we keep only one of them?

this is another tricky thing. dotnet restore looks for the nuget.config in the root folder, while VS while restoring packages for the our classic projects (csproj based) looks for the Nuget folder ;) I can try to investigate that

**Comment by AndreyAkinshin** [comment]
> this is currently impossible because we also sign some of our test projects in order to let them use some of our internals (internalsvisibleto)

Why we can't change the path in the corresponded project.json files? Like `"keyFile": "../../src/strongNameKey.snk"` instead of `"keyFile": "../../strongNameKey.snk"`?

> this is another tricky thing. dotnet restore looks for the nuget.config in the root folder, while VS while restoring packages for the our classic projects (csproj based) looks for the Nuget folder ;) I can try to investigate that

VS should also use NuGet.config from the root solution directory. By the way, it seems that we don't need `NuGet.targets` anymore. What do you think?

**Comment by adamsitnik** [comment]
> VS should also use NuGet.config from the root solution directory. 

@AndreyAkinshin Sorry, I did not know that! I have just pushed the update. 3/3 cahnges were possible ;)
