### ISSUE TITLE
Can not install NuGet package in VS 2013

### ISSUE THREAD

**Issue by gabisandor** [PerfDotNet/BenchmarkDotNet#229]
I'm trying to install BenchmarkDotNet in a .NET 4.5 class library project in Visual Studio 2013, but i get the following error:

![image](https://cloud.githubusercontent.com/assets/5681263/16771941/f5ea0be8-485a-11e6-87a0-7f0d8d89ff45.png)

NuGet 3.0 and later is only available for VS 2015. Is it possible to get around this issue in VS 2013?

**Comment by AndreyAkinshin** [comment]
@gabisandor, could you try to install BenchmarkDotNet `v0.9.7`?

**Comment by gabisandor** [comment]
@AndreyAkinshin - i only tried with the latest version initially. I tried now to install version 0.9.7 explicitly and it succeeded. Thanks!

Hopefully i'm not missing much in terms of benchmark functionality by using a previous version.

**Comment by AndreyAkinshin** [comment]
In `v0.9.8`, we introduced CoreCLR RTM support and netstandart targeting. As it appears, it requires NuGet 3. I don't think, that we can do anything here.
A suggestion: you can try to use `nuget.exe` and install the latest version of BenchmarkDotNet from the command line.
