### ISSUE TITLE
Integration Tests

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#23]
@AndreyAkinshin as part of the work I'm doing on #7 and #8, I've been thinking about how best to port of the Integration Tests that I did in my own library (before we collaborated).

You can see [an example here](https://github.com/minibench/minibench.warren/blob/master/IntegrationTests/Features/SetupTest.cs#L17-L49), but the basic idea is that they do the following: 
- Run as a regular unit test, using Xunit (for instance)
- But test out the full end-to-end process, i.e. project creation, MSBuild code-gen, etc
- Exercise a benchmark that has an [observable side-effect](https://github.com/minibench/minibench.warren/blob/master/IntegrationTests/Features/SetupTest.cs#L46-L47)
- Assert that the *feature* was [really exercised](https://github.com/minibench/minibench.warren/blob/master/IntegrationTests/Features/SetupTest.cs#L30=L32)

What do you think, is it worth me putting something in place so that we can have some *integration* tests against the whole benchmark process? 

If so do you have any bright ideas about who to observe the side-effects? In my previous tests I was running the Benchmark in-process, so I could just use static variables and then inspect them afterwards. That doesn't work if the benchmark runs out-of-process.

**Comment by AndreyAkinshin** [comment]
@mattwarren, integration tests for out-of-main-process logic is a hard issue. My suggestion is the following: as you can see, the target benchmark process prints some comment line (`// `) to the console. You can print here any useful information and parse it in your integration tests. Be careful: non-comment lines are intended only for target runs, it should be parsed from the main process.
If you don't want to clutter up console output, you can make a special detailed mode with extra-information just for testing.

Also it would be cool to add a project with regular unit tests. Xunit is a good option.

**Comment by mattwarren** [comment]
@AndreyAkinshin one question, at the moment the integration tests take ~30 secs, due to the different warn-up runs, see sample output below.

Is it a bad idea to allow the integration tests to skip `pre-warmup` and `warmup` runs? I know that they should be enforced for real benchmarks, so I don't want to expose any options that could break correctness. 

But it would be better if the integration tests could run a bit quicker, especially as more are added.

##### Sample output:
```
Test Name:	BenchmarkDotNet.IntegrationTests.SetupAttributeTest.Test
Test Outcome:	Passed
Result StandardOutput:	
// ***** Competition: Start   *****
// Found benchmarks:
//   SetupAttributeTest_Benchmark_Throughput_HostPlatform_HostJit_NET-HostFramework -w=1 -t=1

// **************************
// Benchmark: SetupAttributeTest_Benchmark (Throughput_HostPlatform_HostJit_NET-HostFramework) [-w=1 -t=1]
// Generated project: C:\Users\warma11\Downloads\__GitHub__\BenchmarkDotNet\BenchmarkDotNet.IntegrationTests\bin\Debug\SetupAttributeTest_Benchmark_Throughput_HostPlatform_HostJit_NET-HostFramework

// Build:
// OverallResult = Success

// Run, Process: 1 / 1
// BenchmarkDotNet=v0.7.7.0
// OS=Microsoft Windows NT 6.1.7601 Service Pack 1
// Processor=Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz, ProcessorCount=8
// CLR=MS.NET 4.0.30319.0, Arch=32-bit DEBUG
// ### Setup called ###
// ### Setup called ###
// Pre-Warmup: 1 op, 8.5 ms, 8485312.9 ns, 22323 ticks, 8485312.9166 ns/op, 117.9 op/s
// ### Setup called ###
// Pre-Warmup: 118 op, 1165.1 ms, 1165087857.9 ns, 3065091 ticks, 9873625.9147 ns/op, 101.3 op/s
// ### Setup called ###
// Warmup (idle): 118 op, 0 ms, 9122.8 ns, 24 ticks, 77.3116 ns/op, 12934673.3 op/s
// IterationCount = 118
// ### Setup called ###
// Target (idle): 118 op, 0 ms, 2280.7 ns, 6 ticks, 19.3279 ns/op, 51738693 op/s
// ### Setup called ###
// Warmup 1: 118 op, 1167.8 ms, 1167771091.6 ns, 3072150 ticks, 9896365.1826 ns/op, 101 op/s
// ### Setup called ###
Target 1: 118 op, 1161.7 ms, 1161720416.9 ns, 3056232 ticks, 9845088.2785 ns/op, 101.6 op/s
// Benchmark finished

AverageTime (ns/op): Median = 9845088.27881; StdDev = 0; Min = 9845088.27881; Max = 9845088.27881;
OperationsPerSecond: Median = 0.10157; StdDev = 0; Min = 0.10157; Max = 0.10157;

// ***** Competition: Finish  *****

```ini
BenchmarkDotNet=v0.7.7.0
OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz, ProcessorCount=8
HostCLR=MS.NET 4.0.30319.0, Arch=32-bit DEBUG
               Type |    Method |       Mode |     Platform |     Jit |          .NET |   AvrTime |    StdDev | op/s |
------------------- |---------- |----------- |------------- |-------- |-------------- |---------- |---------- |----- |
 SetupAttributeTest | Benchmark | Throughput | HostPlatform | HostJit | HostFramework | 9.8451 ms | 0.0000 ms | 0.10 |

// ***** Competition: End *****
```

**Comment by AndreyAkinshin** [comment]
> Is it a bad idea to allow the integration tests to skip pre-warmup and warmup runs?

It is a good idea. In fact, you don't need warmups unless you test warmups or you test some specific benchmark effects that requires warmup.

**Comment by mattwarren** [comment]
Actually I realised that I can do it with the existing functionality, now all integration tests have this on them (before I wasn't setting the mode, so it was defaulting to `BenchmarkMode.Throughput`):

``` csharp
[BenchmarkTask(mode: BenchmarkMode.SingleRun, processCount: 1, warmupIterationCount: 1, targetIterationCount: 1)]
```
and they all run pretty quick

The output is now the following
```
Test Name:	BenchmarkDotNet.IntegrationTests.SetupAttributeTest.Test
Test Outcome:	Passed
Result StandardOutput:	
// ***** Competition: Start   *****
// Found benchmarks:
//   SetupAttributeTest_Benchmark_SingleRun_HostPlatform_HostJit_NET-HostFramework -w=1 -t=1

// **************************
// Benchmark: SetupAttributeTest_Benchmark (SingleRun_HostPlatform_HostJit_NET-HostFramework) [-w=1 -t=1]
// Generated project: C:\Users\warma11\Downloads\__GitHub__\BenchmarkDotNet\BenchmarkDotNet.IntegrationTests\bin\Debug\SetupAttributeTest_Benchmark_SingleRun_HostPlatform_HostJit_NET-HostFramework

// Build:
// OverallResult = Success

// Run, Process: 1 / 1
// BenchmarkDotNet=v0.7.7.0
// OS=Microsoft Windows NT 6.1.7601 Service Pack 1
// Processor=Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz, ProcessorCount=8
// CLR=MS.NET 4.0.30319.0, Arch=32-bit DEBUG
// ### Setup called ###
// ### Benchmark called ###
// Warmup 1: 1 op, 4.4 ms, 4438986 ns, 11678 ticks, 4438985.9893 ns/op, 225.3 op/s
// ### Setup called ###
// ### Benchmark called ###
Target 1: 1 op, 4.7 ms, 4713429.2 ns, 12400 ticks, 4713429.206 ns/op, 212.2 op/s
// Benchmark finished

AverageTime (ns/op): Median = 4713429.2; StdDev = 0; Min = 4713429.2; Max = 4713429.2;
OperationsPerSecond: Median = 212.15976; StdDev = 0; Min = 212.15976; Max = 212.15976;

// ***** Competition: Finish  *****

```ini
BenchmarkDotNet=v0.7.7.0
OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz, ProcessorCount=8
HostCLR=MS.NET 4.0.30319.0, Arch=32-bit DEBUG
               Type |    Method |      Mode |     Platform |     Jit |          .NET |   AvrTime |    StdDev |   op/s |
------------------- |---------- |---------- |------------- |-------- |-------------- |---------- |---------- |------- |
 SetupAttributeTest | Benchmark | SingleRun | HostPlatform | HostJit | HostFramework | 4.7134 ms | 0.0000 ms | 212.16 |

// ***** Competition: End *****
```
