### ISSUE TITLE
[Minor] RoslynGenerator should include transitive assembly references.

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#234]
[This method](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Toolchains.Roslyn/Toolchains/Classic/RoslynGenerator.cs#L46):
```cs
return benchmark.Target.Type.GetTypeInfo().Assembly 
                 .GetReferencedAssemblies() 
                 .Select(Assembly.Load) 
                 .Concat(new[] { benchmark.Target.Type.GetTypeInfo().Assembly }); 
```
there's hidden gotcha :)

The compiler do not include unused references into assembly references list (that's undocumented behavior but can be easily checked via ilspy / any other decompiler). 

So, if there's a benchmark assembly A that uses type from assembly B that's derived from type from assembly C, the C will not be listed in A references as there's no direct dependency.
 
However, csc compiler need the C assembly to be listed in `/reference` or build will fail. Well, this one is [documented](https://msdn.microsoft.com/en-us/library/yabyz3h4.aspx):)

> If you reference an assembly (Assembly A) that references another assembly (Assembly B), you will need to reference Assembly B if: 
* A type you use from Assembly A inherits from a type or implements an interface from Assembly B.
* You invoke a field, property, event, or method that has a return type or parameter type from Assembly B.

Proposed solutions:
* easy one: include references from assemblies that are referenced by `benchmark.Target`'s assembly.
* bulletproof: traverse entire reference graph (skipping framework assemblies and visited ones, of course).

**Comment by adamsitnik** [comment]
You are right! However, we are ready for that ;) We save the compiled dlls to the output folder of the [A assembly](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Toolchains.Roslyn/Toolchains/Classic/RoslynGenerator.cs#L14). So somebody else (MSBuild?) puts these dlls (A, B, C) to the bin folder, we simply reference one of them (A), the rest will be loaded at runtime from this folder.
