### ISSUE TITLE
Unable to install on VS Professional 2013 (12.0.40629.0 update 5)

### ISSUE THREAD

**Issue by MithunChopda** [PerfDotNet/BenchmarkDotNet#237]
With lot of excitement I fired the first command Install-Package BenchmarkDotNet and boom.

I got the following error.

PM> Install-Package BenchmarkDotNet
Attempting to resolve dependency 'Microsoft.CodeAnalysis.CSharp (≥ 1.3.2)'.
Attempting to resolve dependency 'Microsoft.CodeAnalysis.Common (= 1.3.2)'.
Attempting to resolve dependency 'System.Collections.Immutable (≥ 1.1.37)'.
Attempting to resolve dependency 'System.Reflection.Metadata (≥ 1.2.0)'.
Install-Package : 'System.Reflection.Metadata' already has a dependency defined for 'System.Collections.Immutable'.
At line:1 char:16
+ Install-Package <<<<  BenchmarkDotNet
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

What must me wrong?

**Comment by adamsitnik** [comment]
@MithunChopda Thans for the bug! I was able to reproduce it, it's proably Roslyn fault. I have reported it in [Roslyn's repo](https://github.com/dotnet/roslyn/issues/12780)

What I can offer you right now is to use our `0.9.7` version (we did not use Roslyn then)

**Comment by MithunChopda** [comment]
I am able to install 0.9.7. Thank you.

**Comment by adamsitnik** [comment]
> "you will need to use Visual Studio 2015 for that package."

The issue [got rejected by Microsoft](https://github.com/dotnet/roslyn/issues/12780), which means that we can not support VS 2013 now. I don't like it, but I will close this one as well.
