### ISSUE TITLE
Total Time reports hour rounded up

### ISSUE THREAD

**Issue by LeeCampbell** [PerfDotNet/BenchmarkDotNet#240]
I have noticed that the _Total Time_ formatting is wrong.
Here the 2362s run is reported to have taken 1h 39min and 22 sec.
However 2362s is just 39min 22 sec.

```
Total time: 01:39:22 (2362.03 sec)

// * Summary *

Host Process Environment Information:
BenchmarkDotNet=v0.9.8.0
OS=Microsoft Windows NT 6.2.9200.0
```

It appears to be the formatting in this method https://github.com/PerfDotNet/BenchmarkDotNet/blob/c6405a91bee90de6a12aee24755fbb783c2d9052/BenchmarkDotNet/Running/BenchmarkRunner.cs#L159

I would have thought that this line 

    var hhMmSs = $"{time.TotalHours:00}:{time:mm\\:ss}";

could just simply be 

    var hhMmSs = $"{time:hh:\\mm\\:ss}";

Or is this intended to cater for >24hr benchmark runs?
If so then, perhaps truncate the total hours first - http://stackoverflow.com/questions/2820141/stringformat-double-without-rounding

**Comment by AndreyAkinshin** [comment]
@LeeCampbell, thanks for the bugreport. Will be fixed in the next version.
