### ISSUE TITLE
DefaultConfig StatisticColumn values

### ISSUE THREAD

**Issue by billboga** [PerfDotNet/BenchmarkDotNet#244]
Related to https://github.com/PerfDotNet/BenchmarkDotNet/commit/da2e3f059fff878a8e88b2e1dc756b909ce9631d, since `StdDev` is related to `Mean`, why is `Median` a default column? Is there an additional relationship between the current columns that can be determined?

**Comment by AndreyAkinshin** [comment]
Hi, @billboga, thank you for the question. There are some historical reasons for that: we had some troubles with outliers, so, I have decided to print `Median`, it works better for most cases. It's a temporary decision (unfortunately, we use this approach for a long time; typical situation for temporary decisions).
This logic will be changes (hopefully) in v0.9.10. Right now I'm working on new MeasureEngine. In short, it will include the following changes:
* We will have special parameters which allow you to control the situation with outliers (you can include or exclude it)
* Default time column will be `Mean`.
* In case of big difference between `Mean` and `Median`, the summary table will also include the `Median` column.
* In case of big `StdError`, the corresponded column also be printed.

**Comment by billboga** [comment]
Great. Thanks for the update.

**Comment by Grauenwolf** [comment]
I'm looking forward to it.
