### ISSUE TITLE
No namespace information?

### ISSUE THREAD

**Issue by jskeet** [PerfDotNet/BenchmarkDotNet#246]
I've just noticed that in the brief JSON export format at least, there's no namespace information - just the type's short name and the methods. While in many cases that will be enough, I definitely think it would be useful to include the namespace of the test.

**Comment by AndreyAkinshin** [comment]
Done.
* Now all the json exporters include information about namespaces.
* Also I made some refactoring of the json exporters, see https://github.com/PerfDotNet/BenchmarkDotNet/commit/a8b4e7bdd4618c93827ea6be139f5bf290a80da3 and [docs/guide/Configuration/Exporters.md#json](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/docs/guide/Configuration/Exporters.md#json)
* Also now you can mark your assembly with `NamespaceColumnAttribute`, it will add information about namespace in the summary table.
