### ISSUE TITLE
Something isn't right with metrics

### ISSUE THREAD

**Issue by ppanyukov** [PerfDotNet/BenchmarkDotNet#25]
So I've been running the `Math_DoubleSqrtAvx` as a matter of course and I noticed something very strange started to happen on my machine -- the metrics are completely wrong.

I think this was introduced in https://github.com/PerfDotNet/BenchmarkDotNet/commit/66cce477d016979cde3203d5f7125710cffdf4a4.

Example:

Running with https://github.com/PerfDotNet/BenchmarkDotNet/commit/52acca1c5cc0cf7eb408c8ccb4223c2973ba8fe2 (previous commit):

```
// BenchmarkDotNet=v0.7.6.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, ProcessorCount=4
// CLR=MS.NET 4.0.30319.42000, Arch=64-bit  [RyuJIT]
Common:  Type=Math_DoubleSqrtAvx  Mode=Throughput  Platform=X64  Jit=RyuJit  .NET=Current

 Method |  AvrTime |     StdDev |           op/s |
------- |--------- |----------- |--------------- |
 Sqrt13 | 58.23 ns | 0.11300 ns |  17,171,847.17 |
 Sqrt14 |  1.56 ns | 0.00402 ns | 641,502,698.72 |
```

Running with https://github.com/PerfDotNet/BenchmarkDotNet/commit/66cce477d016979cde3203d5f7125710cffdf4a4 (potential bad commit):

```
// BenchmarkDotNet=v0.7.6.0
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz, ProcessorCount=4
// Host CLR=MS.NET 4.0.30319.42000, Arch=64-bit  [RyuJIT]
Common:  Type=Math_DoubleSqrtAvx  Mode=Throughput  Platform=X64  Jit=RyuJit  .NET=Current


 Method |     AvrTime |     StdDev |                   op/s |
------- |------------ |----------- |----------------------- |
 Sqrt13 |    58.08 ns |   0.111 ns |          17,216,262.42 |
 Sqrt14 | 0.000000 ns | 0.00712 ns | 27,161,311,692,613,400 |
```

Clearly there is something wrong here.

Another observation: benchmarks take absolutely ages to run after this commit.

I haven't looked into this in detail, but where it seems to go wrong, we get lines like this:

```
Target 1: 8200000000 op, 237.3 ms, 237279581.2 ns, 786056 ticks, 0.0289 ns/op, 34558388715.3 op/s
Target 2: 8200000000 op, 29.7 ms, 29687115.1 ns, 98347 ticks, 0.0036 ns/op, 276214107191.9 op/s
Target 3: 8200000000 op, 0 ms, 301.9 ns, 1 ticks, 0 ns/op, 27164828800000000 op/s
Target 4: 8200000000 op, 59.2 ms, 59171077.9 ns, 196021 ticks, 0.0072 ns/op, 138581217318.6 op/s
Target 5: 8200000000 op, 0 ms, 301.9 ns, 1 ticks, 0 ns/op, 27164828800000000 op/s
Target 6: 8200000000 op, 0 ms, 301.9 ns, 1 ticks, 0 ns/op, 27164828800000000 op/s
Target 7: 8200000000 op, 0 ms, 301.9 ns, 1 ticks, 0 ns/op, 27164828800000000 op/s
Target 8: 8200000000 op, 0 ms, 301.9 ns, 1 ticks, 0 ns/op, 27164828800000000 op/s
Target 9: 8200000000 op, 0 ms, 301.9 ns, 1 ticks, 0 ns/op, 27164828800000000 op/s
Target 10: 8200000000 op, 0 ms, 301.9 ns, 1 ticks, 0 ns/op, 27164828800000000 op/s
```

I have captured the logs in a separate gist to keep this short:

- good commit: https://gist.github.com/ppanyukov/c8af3e75700f0e77b8ad#file-good-txt
- bad commit: https://gist.github.com/ppanyukov/c8af3e75700f0e77b8ad#file-bad-txt

**Comment by AndreyAkinshin** [comment]
It is a good commit. BenchmarkDotNet assumes that time of a method like `int Foo() { return const; }` is equal to zero (you don't need a time to compute a const). In fact, `Sqrt14` is a method of such kind (see this post: [RyuJIT RC and constant folding](http://aakinshin.net/en/blog/dotnet/ryujit-rc-and-constant-folding/)). Thus, `0 ns` is the right answer for `Sqrt14`.
I have another question: what should we do with such methods? What kind of result should we show?

**Comment by ppanyukov** [comment]
Ah yes, I didn't read that post carefully enough. So basically the jitter calculated those sqrt's at jit time and reduced everything to returning a constant expression, and thus what we have here is effectively noop, correct?

It looks very strange though.

Don't know what to do with things like that.  Perhaps if it's just one isolated case then leave it be.

**Comment by ppanyukov** [comment]
And a quick question. What exactly do you do to generate the ASM listing?

**Comment by AndreyAkinshin** [comment]
VisualStudio Debugger + Disassembly Window; WinDbg; CoreCLR + COMPLUS_JitDisasm=*

**Comment by ppanyukov** [comment]
I know about all of these except the Core CLR one and that's the one I'm interested in :)

When you say "CoreCLR + COMPLUS_JitDisasm=*" what exactly does this mean?

**Comment by AndreyAkinshin** [comment]
1. Build [CoreCLR](https://github.com/dotnet/coreclr) in Debug mode (command `build clean`).
2. Set environment variable `COMPLUS_JitDump`={method-list} (see [ryujit-overview.md](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/ryujit-overview.md))
3. Run your exe file with help of `CoreRun.exe`, asm listing will be printed to the console.

**Comment by ppanyukov** [comment]
Awesome. Thanks for this. You should write a blog post about it. I'm serious.

**Comment by AndreyAkinshin** [comment]
Ok =)
