### ISSUE TITLE
Quartile

### ISSUE THREAD

**Issue by wojtpl2** [PerfDotNet/BenchmarkDotNet#264]
Would you like add [quartile](https://en.wikipedia.org/wiki/Quartile)? This is very useful information.

**Comment by AndreyAkinshin** [comment]
@wojtpl2, we already have quartiles and percentiles, see https://perfdotnet.github.io/BenchmarkDotNet/Configuration/Columns.htm

**Comment by wojtpl2** [comment]
Ok Thanks.
