### ISSUE TITLE
Add ability to specify that benchmark requires STAThread

### ISSUE THREAD

**Issue by vladadada** [PerfDotNet/BenchmarkDotNet#265]
Something similar to how Nunit has [RequiresSTA] attribute. It could be useful for benchmarking code whose performance depends on some internal logic of WPF elements.

**Comment by adamsitnik** [comment]
@vladadada I just added the support for that. In order to use it you need to mark your benchmark with `[System.STAThread]` attribute. Sample:

```cs
public class RequiresSTA
{
    [Benchmark, System.STAThread]
    public void CheckForSTA()
    {
        if (Thread.CurrentThread.GetApartmentState() != ApartmentState.STA)
        {
            throw new ThreadStateException("The current threads apartment state is not STA");
        }
    }
}
```

**Comment by vladadada** [comment]
@adamsitnik Awesome!

**Comment by dotMorten** [comment]
@adamsitnik Do I understand this change correctly that it'll only works on an individual test, and doesn't apply to GlobalSetup and GlobalCleanup? (which is where I need it)

**Comment by adamsitnik** [comment]
@dotmorten I can't see your comment here that I got via email today, but the `[STAThread]` attribute will be applied to the `Main` method of the auto-generated code so it's gonna work for both setup and benchmark.

https://github.com/dotnet/BenchmarkDotNet/blob/87d281d7dbf52036819efff52e6661e436648b73/src/BenchmarkDotNet/Templates/BenchmarkProgram.txt#L12-L13

**Comment by dotMorten** [comment]
Thanks. Sorry I deleted it when I shortly after realized this 😁
