### ISSUE TITLE
Don't assume that TargetType has reference to BenchmarkDotNet

### ISSUE THREAD

**Issue by adamsitnik** [PerfDotNet/BenchmarkDotNet#266]
> "On RoslynGenerator, method GetAllReferences, it seems to assume that the target type has a reference to Benchmark assemblies. When it doesnt, everything fails. I built a fx to run perf tests on our infrastructure. It uses benchmarkdotnet, but that doesnt get exposed to the devs, they use a different api so the target assembly doesnt have references." @hammett

**Comment by hammett** [comment]
thanks guys!
