### ISSUE TITLE
Print runtime of child processes in summary

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#268]
An example: we have a coreclr host process with `CoreJob`, `ClrJob`, `MonoJob`. In this case, only information about `CoreJob` will be printed in the summary. It would be also nice to have information about versions of installed .NET Framework and Mono.

**Comment by adamsitnik** [comment]
@AndreyAkinshin I added this as a last line in the summary.

Sample output:
```
BenchmarkDotNet=v0.9.9-develop
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4700MQ CPU 2.40GHz, ProcessorCount=8
Frequency=2338332 Hz, Resolution=427.6553 ns, Timer=TSC
CLR=Clr 4.0.30319.42000, Arch=64-bit  [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1055.0
Runtime(s): Clr 4.0.30319.42000, Core
```

**Comment by AndreyAkinshin** [comment]
I have some suggestions here:
1. Instead of `CLR=` we probably should use `Runtime=` because we already use term `Clr` for the Full .NET Framework. Maybe we should write `HostRuntime` here.
2. Instead of `Runtime(s): ` we could write something like `JobRuntimes=`.
3. `Arch` (`x86` or `x64`) and Jit version (e.g. `[RyuJIT]`) is also part of the runtime. For example, on my Windows machine I often run benchmarks against full framework and mono. Here we have the following situation:
* The host process is `x86`  because by default I have enabled "Prefer 32-bit mode"
* ClrJob process is `x64`
* MonoJob is `x86` because I don't have `x64` Mono for Windows.

I think, we should provide enough information for user about all the runtimes for target jobs.

**Comment by adamsitnik** [comment]
@AndreyAkinshin  I agree with your ideas.

So would something like this be ok?

```
Host Runtime=Clr 4.0.30319.42000, Arch=64-bit  [RyuJIT]
Job Runtime(s): 
  Clr 4.0.30319.42000, Arch=64-bit  [RyuJIT]
  Clr 4.0.30319.42000, Arch=32-bit
  Core, Arch=64-bit
  Mono, Arch=64-bit
```

**Comment by AndreyAkinshin** [comment]
It looks much better.
What do you think, could we also print version of Mono and Core?

**Comment by adamsitnik** [comment]
> What do you think, could we also print version of Mono and Core?

We can do this for Mono, I need to check it for Core

**Comment by AndreyAkinshin** [comment]
Am I right that we can run Core jobs only if the host process if Core? In this case, we could just take information about Core version from the host process.

**Comment by adamsitnik** [comment]
@AndreyAkinshin Ok, I updated the code.

Sample output:
```
BenchmarkDotNet=v0.9.9-develop
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4700MQ CPU 2.40GHz, ProcessorCount=8
Frequency=2338332 Hz, Resolution=427.6553 ns, Timer=TSC
Host Runtime=Clr 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
GC=Concurrent Workstation
JitModules=clrjit-v4.6.1055.0
Job Runtime(s):
        Clr 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
        .NET Core 4.0.0.0, Arch=64-bit  [RyuJIT]
        Mono 4.4.1 (Visual Studio built mono), Arch=64-bit RELEASE
```
