### ISSUE TITLE
Command line argument handling

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#27]
@AndreyAkinshin 

I imagine that over time we're going to need more and more command line switches for different modes. 

So that everything is handled in a clean way I propose that we use [Mono.Options](http://tirania.org/blog/archive/2008/Oct-14.html), it's main advantage is that it's a [single file](https://github.com/mono/mono/blob/master/mcs/class/Mono.Options/Mono.Options/Options.cs) that can easily be embedded in BenchmarkDotNet.

I've used it before and it's easy to work with, you end up with a [single class](https://github.com/minibench/minibench.warren/blob/master/MiniBench.Core/Infrastructure/CommandLineArgs.cs) that contains all the options as properties and then you can use that throughout the rest of the code.

Unless there are any objections or alternative suggestions I'll go ahead and integrate it over the next week or so.

**Comment by AndreyAkinshin** [comment]
I suggest to use [CommandLineParser](https://www.nuget.org/packages/CommandLineParser). It is a very popular library, it is easy to use, and it is actively developed.

**Comment by mattwarren** [comment]
Okay, I'll take a look at CommandLineParser. 

Do you know if it can be *embedded* in BenchmarkDotNet.dll, so that we can keep out 3rd party dll dependencies to a minimum, or are you not so worried about that?

**Comment by AndreyAkinshin** [comment]
I am not worried about that. I think, it is ok, if we will have some references to useful NuGet packages.

**Comment by mattwarren** [comment]
Okay maybe I'm mis-understanding the expected usage/flow.

Do you think there is a case for people who want a self-contained .exe that has all their Benchmarks compiled into it (similar to BenchmarkDotNet.Samples.exe). They would then put this on another machine and run several different command lines as part of an automated build (for instance).

> I think, it is ok, if we will have some references to useful NuGet packages.

Do you mean that CommandLineParser becomes a dependency of BenchmarkDotNet, so when you pull down our NuGet package you also have to have CommandLineParser?

**Comment by AndreyAkinshin** [comment]
> Do you think there is a case for people who want a self-contained .exe 

Why do you need a self-contained .exe? I think, it is ok to copy an .exe file with some additional dlls.

> They would then put this on another machine and run several different command lines as part of an automated build

They can do it, no problem. However, there is one restriction: we should target BenchmarkDotNet.Samples.exe to .NET 4.0 (WinXP requires it). CommandLineParser works with .NET 4.0, so, it is not a problem.

> Do you mean that CommandLineParser becomes a dependency of BenchmarkDotNet, so when you pull down our NuGet package you also have to have CommandLineParser?

The default behavior is the following: if we install CommandLineParser via Nuget for BenchmarkDotNet, then installation of the BenchmarkDotNet NuGet packages will lead to installation of the all dependencies (include CommandLineParser).

**Comment by mattwarren** [comment]
So that we can support the CoreCLR stack, add .NET Native support, run it on Linux, MacOS, FreeBSD, etc we won't be relying on any 3rd party dlls inside the Core of BenchmarkDotNet.

So this will now be done with [Mono.Options](http://tirania.org/blog/archive/2008/Oct-14.html) embedded as a [single-file in the BenchmarkDotNet source](https://github.com/mono/mono/blob/master/mcs/class/Mono.Options/Mono.Options/Options.cs) (assuming that there are not licensing issues)

**Comment by AndreyAkinshin** [comment]
LGTM

**Comment by smudge202** [comment]
Just wanted to fly the DNX flag here and mention this package: https://www.nuget.org/packages/microsoft.extensions.optionsmodel

I've been using OptionsModel extensively for the last year or so (previously under [this package](https://www.nuget.org/packages/microsoft.framework.optionsmodel)). Sadly, no support for `net40` on any of the new stuff yet. But for consideration at a later stage. :)

**Comment by mattwarren** [comment]
We are just doing this manually and it [seems to be simple enough for our use-case](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Configs/ConfigParser.cs), so closing this issue
