### ISSUE TITLE
[Setup] error when doing inheritance

### ISSUE THREAD

**Issue by jbayardo** [PerfDotNet/BenchmarkDotNet#272]
If you have something like:

```
class A {
    [Setup]
    public virtual void Setup() {
        DoStuff();
    }
}

class B : A {
    [Setup]
    public override void Setup() {
        base.Setup();
        DoSomeMoreStuff();
    }
}
```

This triggers an error saying that you have more than one Setup. This is strictly untrue, as there is a single one (Setup). Removing the [Setup] marker means that no method is called afterwards (not even the inherited one). If you do set it with [Setup], however, everything seems to run fine anyways. This only happens when using ExecutionValidator.FailOnError.

**Comment by AndreyAkinshin** [comment]
@adamsitnik, could you take a look?

**Comment by adamsitnik** [comment]
@jbayardo Thanks for detailed bug report! Fixed ;)
