### ISSUE TITLE
[Suggestion]: Simplify the configuration API

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#279]
All of following is not a strong opinion, just fresh impressions on trying to use the current codebase.
1. How much settings do we need to alter N of iterations?
   Here they are:
   
   ```
   RunMode.Default.InvocationCount / IterationTime
   AccuracyMode.Default.MinInvokeCount / AccuracyMode.Default.MinIterationTime
   RunMode.Default.LaunchCount
   RunMode.Default.TargetCount
   RunMode.Default.WarmupCount
   RunMode.Default.UnrollFactor
   OperationsPerInvoke attribute
   ```
   
   can these be simplified down to
   
   ```
   RunMode.Default.TargetCount / TargetTime
   RunMode.Default.WarmupCount / WarmupTime
   RunMode.Default.UnrollFactor => OperationsPerInvoke
   ```
   
   :scrathes_head:?
2. Please, consider to use human-oriented API. The creation of a new job should not look like this:
   
   ```
             var job = Job.Default
                 .WithLaunchCount(1)
                 .WithWarmupCount(100)
                 .WithTargetCount(300)
                 .WithUnrollFactor(1)
                 .Mutate(
                     new JobMutator("have no idea what")
                         .Add(RunMode.Default.RunStrategy.Mutate(RunStrategy.Throughput))
                         .Add(RunMode.Default.InvocationCount.Mutate(1))
                         .Add(GcMode.Default.Force.Mutate(false))
                         .Add(InfrastructureMode.Default.Toolchain.Mutate(InProcessToolchain.Instance)))
   ```
   
   Can freezable objects be used instead? [Fast prototype](https://gist.github.com/ig-sinicyn/b4cc36175a002f6c08f2eeb9f35faea2) to show what I'm talking about.

**Comment by AndreyAkinshin** [comment]
1. We can't do this simplification, all the listed characteristics are very important
a) When you are working with `RunMode`, you specify exact values. For example, if you set `RunMode.IterationTime` = `100ms`, you say: "Single iteration should take 100ms". When you set `AccuracyMode.MinIterationTime` = `100ms`, you say: "Magic algorithm should choose ideal iteration time automatically, however it should be at least 100ms".
b) As I understand, you suggest to drop some of characteristics. But each of them is needed for some specific task. E.g. `RunMode.Launch` specifies how many times we have to run generated program. `UnrollFactor` is not `OperationsPerInvoke`: `OperationsPerInvoke` specifies how many operations we have in a method, `UnrollFactor` specifies how many times we have to invoke this method in the loop body (it's extremely important for nanosecond benchmark, a blog post with explanation are coming).
2. Probably, we just have to add more examples in documentation. For example, you could write:
```cs
var job = Job.Default
    .WithLaunchCount(1)
    .WithWarmupCount(100)
    .WithTargetCount(300)
    .WithUnrollFactor(1)
    .With(RunStrategy.Throughput)
    .WithInvocationCount(1)
    .WithGcForce(true)
    .With(InProcessToolchain.Instance);
```
`JobMutators` is another mechanism which allows to mutate all the jobs at the same time. For example, if you have 5 jobs (defined inside a benchmark) and you want to make all of them dry (just for checking that everything is ok), `RunMode.Dry` is your friend (it mutates only some of the RunMode characteristics and leaves the rest of them (like toolchain or platform) untouched).

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin 

1 - Ok, got it. Lets forget about `unroll factor` and `ops per invoke` for now. Why do we need both `InvocationCount` and `TargetCount` at the same time? Shouldn't these be refactored into
```
WarmupStage:
  * IterationTime
  * MinIterationTime
  * IterationCount
  * MinIterationCount

TargetStage:
  * IterationTime
  * MinIterationTime
  * IterationCount
  * MinIterationCount
```
?
Yep, there's more properties than before but at least these are a bit more obvious.

2 - Err, I'm still not sure that we do need immutable objects here.
The rest of config props uses much more friendlier POCO approach. Advanced features such as mutators / resolvers etc can be implemented behind the scenes. All we need is an Apply method  that will traverse both template and target object properties and update target's props with non-default values from the template. From user's point of view it will look something like
```cs
var job = new Job
{
  Run = 
  { 
    TargetCount = 123,
    WarmupCount = 10
  }
}

var mutator = new Job
{
  Run = 
  { 
    WarmupCount = 321
  }
}

var resultJob  = job.Apply(mutator);
Assert.AreEqual(resultJob.Run.TargetCount, 123); // value not changed
Assert.AreEqual(resultJob.Run.WarmupCount, 321); // value from mutator

mutator = new Job
{
  Run = new RunMode(overrideEntireNode: true)
  { 
    WarmupCount = 321
  }
}

var resultJob2  = job.Apply(mutator); // the entire Run node will be replaced.
Assert.AreEqual(resultJob2.Run.TargetCount, 0);  // from the mutator (default value)
Assert.AreEqual(resultJob2.Run.WarmupCount, 321); // from the mutator (new value)
```

**Comment by AndreyAkinshin** [comment]
1. `InvocationCount` specifies how many times we should invoke the benchmark method in an iteration. `TargetCount` specifies how may iteration we want to make. Probably, we need another titles (more obvious for new users) but we definitely need two characteristics here.
2. Hmm. POCO approach makes sense, let me think about it.
What we should do with default values in this case? Right now we could mark any characteristics as the default, in this case actual value will be calculated by 3rdParty logic from resolver.

**Comment by ig-sinicyn** [comment]
> InvocationCount specifies how many times we should invoke the benchmark method in an iteration. TargetCount specifies how may iteration we want to make. 

Ouch, finally got it. There're three levels with similar naming:
* setting for entire run- only `LaunchCount` for now
* setting for N of iterations (`TargetCount`/ `WarmupCount`)
* settings for what to do per each iteration: iteration time / invocation count  / unroll factor / ops per invoke etc. 

Don't know how I managed to forget the things (I've remember that I was digging it some month ago). Damn. Thanks :)

>2 What we should do with default values in this case?

 I'd prefer to do two things:
1. Add an default fallback value parameter into DepProperty .ctor
2. In case we need dynamic override of defaults: just check the properties of a parent object. In WPF that's called [property value inheritance](https://msdn.microsoft.com/en-us/library/ms753197(v=vs.110).aspx)

if 2 is not an option we can add an explicit resolve method ala
```
resolver.Resolve(SomeClass.SomePropertyKey, instance)
```

I'll do proof code for both and will post here.

**Comment by AndreyAkinshin** [comment]
> Don't know how I managed to forget the things

I think, we need better naming here. However, I don't know how to rename these things.

> I'll do proof code for both and will post here.

Great, thanks.

**Comment by ig-sinicyn** [comment]
> However, I don't know how to rename these things.

Same here : )

>I'll do proof code for both and will post here.

[done](https://gist.github.com/ig-sinicyn/b4cc36175a002f6c08f2eeb9f35faea2)

The code is not feature complete yet and it's internals are ugly, I know:)

Before finishing it: does the current approach looks good enough for you? If no, can you provide some use case code to give an idea how it should look like?

**Comment by AndreyAkinshin** [comment]
I like it in general, but could we keep the resolving feature? Sometimes we don't have a specific value in advance, it should be calculated in runtime with help of a resolver. If some property has "default" value, it means that the actual value could be calculated dynamically (e.g. based on other properties or current environment or based on collected data from the pilot stage...).

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin 

Should we close this one as #286 is merged?

**Comment by AndreyAkinshin** [comment]
@ig-sinicyn, yep.
