### ISSUE TITLE
Support Benchmarks running under .NET 3.5

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#28]
From email conversation:
> I suggest to use an approach that is similar to your approach in minibench: we can create a separate .NET 2.0 library and make reference from a generated benchmark project to this .NET 2.0 library. 
In this case, we can use .NET 4.5 for main BenchmarkDotNet assembly and for unit tests (if somebody wants to run benchmark on WinXP, he can generate that benchmark on Win7+ and copy it to WinXP).

**Comment by redknightlois** [comment]
@mattwarren Support for .Net 2.0 has ended already. The only support provided is Extended Support which is a paid only support usually provided to governments or very large corporations and will also end by end of 2016. Does it makes sense to devote effort to .Net 2.0?

**Comment by AndreyAkinshin** [comment]
@redknightlois, sounds like a good point. What do you think about supporting of .NET 3.5?

**Comment by redknightlois** [comment]
@AndreyAkinshin That is a tough one, because unlike .NET 2.0 the 3.5 framework is supported alongside a wide array of OS. However, nowhere were 3.5 is supported 4.0 is unsupported, so in the end it is a matter of how many 3.5 projects are there out-there and how many will use BenchmarkDotNet. I haven't come across a 3.5 project in like ages, but that is just me.

**Comment by mattwarren** [comment]
Okay, I've changed this to ".NET 3.5 support", rather that .NET 2.0.

But I'll hold of implementing it until someone actually asks for it.

**Comment by AndreyAkinshin** [comment]
@mattwarren, @adamsitnik, am I right that we will not support .NET 3.5 ever? Can I close the issue?

**Comment by adamsitnik** [comment]
@AndreyAkinshin I think that you should close it (It would be hard to implement and would increase code complexity)

**Comment by mattwarren** [comment]
@adamsitnik @AndreyAkinshin I agree (plus no one has ever asked for .NET 3.5 support)
