### ISSUE TITLE
Results are exported twice for single run

### ISSUE THREAD

**Issue by kvarv** [PerfDotNet/BenchmarkDotNet#281]
https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs

Line 44 and 93 both do `config.GetCompositeExporter().ExportToFiles(summary)`

Is there a reason for this?

**Comment by AndreyAkinshin** [comment]
Looks like a bug. @adamsitnik, could you take a look?

**Comment by kvarv** [comment]
Thank you! I created an elasticsearch exporter and the data kept coming in twice. Looking forward to the fix.
