### ISSUE TITLE
Add Dispose/ShutdownAttribute (SetupAttibute symmetry)

### ISSUE THREAD

**Issue by benaadams** [PerfDotNet/BenchmarkDotNet#282]
If using `[Setup]` to set things up for a run that are `IDisposable`+finalizer it would be good to have a similar method attribute that can be used for cleanup.

**Comment by adamsitnik** [comment]
We already have one, it's called `[Cleanup]`.

**Comment by benaadams** [comment]
Beautiful! 💯
