### ISSUE TITLE
MarkdownExporter.Console.ExportToLog(summary, logger);

### ISSUE THREAD

**Issue by kvarv** [PerfDotNet/BenchmarkDotNet#283]
https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs

Line 113 `MarkdownExporter.Console.ExportToLog(summary, logger);`

Is there a reason for hardcoding a call to the MarkdownExporter?

**Comment by AndreyAkinshin** [comment]
We are using MarkdownExporter here for printing the summary table in the console. The Markdown format looks really nice in the terminal, so it is used by default.

**Comment by kvarv** [comment]
Thanks for your answer!
