### ISSUE TITLE
IdleWarmup running off forever

### ISSUE THREAD

**Issue by cdrnet** [PerfDotNet/BenchmarkDotNet#288]
I suddenly have issues where the IdleWarmup seems to run off forever (with the default configuration):

![benchmarkdotnet-idlewarmup exe](https://cloud.githubusercontent.com/assets/47147/19549768/7be353e6-96a6-11e6-8f0c-b9c7456e756e.png)

I see that there are outliers reported, roughly once per 20-50 iterations, which I suspect is the reason for this. Can I control the idle warmup separately from the other warmup?

**Comment by AndreyAkinshin** [comment]
Hi, @cdrnet, thank you for the report. I already fix this issue, it will be a part of v.0.10.0.

**Comment by cdrnet** [comment]
Great, thanks a lot!
