### ISSUE TITLE
Change layout of the BenchmarkDotNet.Samples

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#29]
I just wanted to check there was no objections before I went ahead and did this.

As the amount of samples have grown, they have got a bit unwieldy to work with in VS, I propose the layout be changed to :

![image](https://cloud.githubusercontent.com/assets/157298/9629517/211d25b2-516b-11e5-9759-b6a78716bf54.png)

So that samples are grouped into categories. 

No files names will be changed, just location and namespaces, is that okay?

**Comment by AndreyAkinshin** [comment]
Yes, it is ok. Don't forget to change reference to the samples from BenchmarkDotNet.Visualizer (and it will be cool if you add some csproj magic that will automatically add all the samples to Visualizer).

**Comment by mattwarren** [comment]
Okay, done and pushed, you might want to pull down the changes sooner rather than later, to stop you having merge headaches. I tried to make sure that the changes show up as renames (rather than delete/add), but still.

> and it will be cool if you add some csproj magic that will automatically add all the samples to Visualizer

I'll have a think about it. But you've already used the only trick I know for this type of thing, i.e. adding files as "links".

**Comment by AndreyAkinshin** [comment]
> But you've already used the only trick I know for this type of thing, i.e. adding files as "links".

Ok, I will do it myself. There is a special wildcards magic, but it is very hard to use it.

**Comment by mattwarren** [comment]
> Ok, I will do it myself. There is a special wildcards magic, but it is very hard to use it.

Do you mean being able to use `**\*.cs` in `.csproj` files? 

(I just saw this tweet and it made me think about this issue, see https://twitter.com/marcgravell/status/668952145622798336)
