### ISSUE TITLE
[BUG] NRE in OutliersAnalyser

### ISSUE THREAD

**Issue by ig-sinicyn** [PerfDotNet/BenchmarkDotNet#296]
BDN, master branch, OutliersAnalyser.cs
```cs
            var actual = report.AllMeasurements.Where(m => m.IterationMode == IterationMode.MainTarget).ToArray();
            var result = report.AllMeasurements.Where(m => m.IterationMode == IterationMode.Result).ToArray();
            var actualOutliers = actual.GetStatistics().Outliers;
```
the report contains _only_ measurements with m.IterationMode == IterationMode.Result
(dont know why, will investigate and update the issue).

the line
```
var actualOutliers = actual.GetStatistics().Outliers;
 ```
fails with NRE as `.GetStatistics()` returns null. 

I'd never return null from any `.GetSomeComplexObject()` method. These should either return empty value or be prefixed with `Try` and marked with `[CanBeNull]`, this issue shows why :)

**Comment by ig-sinicyn** [comment]
UPD: missing reports was my fault, sorry :)

Forgot to dump the Target/Warmup times from my custom Engine.

**Comment by AndreyAkinshin** [comment]
Ok, but it's still a bug, I will fix it today.

**Comment by ig-sinicyn** [comment]
UPD2 Okay, it's kinda complicated now.:)

My code uses same approach as in `BenchmarkProgram.txt`.
results are reported via  RunResults.Print();

and (RunResults.cs)
```
       // TODO: rewrite without allocations
        public IEnumerable<Measurement> GetMeasurements()
        {
            foreach (var measurement in Main)
            {
...
                yield return new Measurement(
                    measurement.LaunchIndex,
                    IterationMode.Result,
                    ++resultIndex,
                    measurement.Operations,
                    value);
            }
        }

        public void Print()
        {
            foreach (var measurement in GetMeasurements())
                WriteLine(measurement.ToOutputLine());
            WriteLine();
        }
```
So it turns out the `Print()` does only a half of work.

Rest of timings are dumped at `Engine.RunIteration()`:
```
            if (!IsDiagnoserAttached) WriteLine(measurement.ToOutputLine());
```

Summary:
1. bug is still there, with IsDiagnoserAttached it'll reproduce on standard engine too.
2. engine should not take responsibility of submitting the results as it's the thing very easy to break and very hard to debug.

**Comment by adamsitnik** [comment]
> So it turns out the Print() does only a half of work.
> Rest of timings are dumped at Engine.RunIteration():

I am not sure about that. IMHO this:

` if (!IsDiagnoserAttached) WriteLine(measurement.ToOutputLine());`

prints the results during execution to show that Engine is working. This is ommited when Diagnoser is attached in order to avoid heap allocations with creating string and printing.

`results.Print()` prints all results one more time at the end. The diagnoser is not catching this allocations because it's already detached

**Comment by ig-sinicyn** [comment]
@adamsitnik 
As it is for now, results.Print() do not print anything but `IterationMode.Result` timings. [Proof](https://github.com/PerfDotNet/BenchmarkDotNet/blob/4b6ea91b95f79dd0214839e495a351222da92e46/src/BenchmarkDotNet.Core/Engines/RunResults.cs#L42).

If the measurements will be printed twice it'll screw the results as the Executor parses console output and fills the Summary.Reports from it. Proofs: [capture from console](https://github.com/PerfDotNet/BenchmarkDotNet/blob/af6f8ab92e5388afc5e138ac123eebfaf3b5caf6/src/BenchmarkDotNet.Core/Loggers/SynchronousProcessOutputLoggerWithDiagnoser.cs#L49), [Parsing](https://github.com/PerfDotNet/BenchmarkDotNet/blob/b11935a7da9253f4b3d35705a59f3275e59dd9ae/src/BenchmarkDotNet.Core/Running/BenchmarkRunnerCore.cs#L166).

I'll create separate issue for that.
