### ISSUE TITLE
Better information when we haven't got a valid measurement

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#30]
From an email exchange:

>Here is the situation: it is very hard to measure a very quick operation. Frequency of your computer is 2.70GHz. It means that you can run 2,700,000,000 CPU cycles per second or 0.37 nanoseconds per cycle. The latency of the Stopwatch is about 15ns and the granularity is 400ns.
If you have an operation that takes 400ns, we can measure it with good precision. If an operation takes 15–40ns, we also can measure it thanks to a large amount of iterations. However, if operation takes 1–2ns (a few CPU cycles), it is almost impossible to measure it.

>You can have a look to Jit_BoolToInt.cs. In this benchmark, it is very hard to measure a single operation. Because of that, I perform six operations and use the `OperationsPerInvoke` attribute.

>Anyway, I think that such benchmarks is a big problem, we have to warn a user that he tries to measure too small effect. For example, if `AvrTime` < 10ns, we can print `?` instead of numbers and print a warning after that table (`? means that AvrTime is too small`). What do you think?

Currently the best approach seems to be:
- print `?` instead of numbers if `AvtTime` is < 10 ns
- print a warning at the end explaining why there are no numbers
- maybe point them in the direction of a sample benchmark that uses `OperationsPerInvoke`

**Comment by mattwarren** [comment]
If it helps, this is the benchmark I was using when I ran into the issue. I guess it could be used as a test-case or sample if you want?

``` csharp
// Inspired by https://www.reddit.com/r/csharp/comments/3jj3ub/my_eyes/cuq500n
public class BitwiseAndVsRemainderOperator
{
	private static long counter;

	[Benchmark]
	public long BitwiseAnd()
	{
		counter++;
		return counter & 1;
	}

	[Benchmark]
	public long BitwiseAndConstantFolding()
	{
		return 5 & 1;
	}

	[Benchmark]
	public long Remainder()
	{
		counter++;
		return counter % 1;
	}

	[Benchmark]
	public long RemainderConstantFolding()
	{
		return 5 % 1;
	}
}
```

**Comment by AndreyAkinshin** [comment]
Yes, thanks.

**Comment by AndreyAkinshin** [comment]
Related to #121

**Comment by AndreyAkinshin** [comment]
It looks that now BenchmarkDotNet can measure methods which takes nanoseconds.

**Comment by adamsitnik** [comment]
> It looks that now BenchmarkDotNet can measure methods which takes nanoseconds.

impressive!!

**Comment by AndreyAkinshin** [comment]
Yeah, sometimes we had incorrect measurements because of the the retirement unit (a blog post is coming). Now we manually unroll the generated loop (see https://github.com/PerfDotNet/BenchmarkDotNet/commit/03fb04c7a0804f20581dea4c71ac1c6a8838d670), it solves the problem. I want also upgrade `Consumer` (it looks solvable) and `v0.10.0` will be ready.
