### ISSUE TITLE
Inject helper classes into the [Benchmark] method

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#31]
Several times when writing a benchmark I've needed to have access to a different value/counter each time it's executed. So that I can ensure I'm accessing different array locations (to prevent caching) or as an attempt to defeat [constant folding](http://aakinshin.net/en/blog/dotnet/ryujit-rc-and-constant-folding/).

For instance rather than writing:

``` csharp
[Benchmark]        
public long BitwiseAndConstantFolding()
{
    return 5 & 1;
}
```

I do:

``` csharp
private static long counter;

[Benchmark]        
public long BitwiseAnd()
{
    counter++;
    return counter & 1;
}
```

I wonder if instead of requiring the Benchmark author to do this every time, we could provide a way of making it easier, for instance:

``` csharp
[Benchmark]        
public long BitwiseAnd(BenchmarkInfo info)
{
    return info.Counter & 1;
}
```

So the idea is that we *inject* the contents of the `BenchmarkInfo` class/struct (it can have a different name if you want). In addition we can just use the existing [`invocationCount` counter](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/BenchmarkMethodInvoker.cs#L174-L194) that we have in the generated scaffolding code.

`BenchmarkInfo` (or whatever it's called), could initially look *something* like this:

``` csharp
public class BenchmarkInfo
{
    public long Counter { get; }
    public long BatchSize { get; }
}
```

**What do you think?**

BTW I can't claim I made this idea up, I originally saw it in JMH, where it's called  [InfraParams](http://hg.openjdk.java.net/code-tools/jmh/file/0879b862a1a3/jmh-samples/src/main/java/org/openjdk/jmh/samples/JMHSample_31_InfraParams.java) and lets you access a class called [IterationParams](http://hg.openjdk.java.net/code-tools/jmh/file/0879b862a1a3/jmh-core/src/main/java/org/openjdk/jmh/infra/IterationParams.java) ([JavaDoc](http://javadox.com/org.openjdk.jmh/jmh-core/0.9/org/openjdk/jmh/infra/IterationParams.html)).

**Comment by AndreyAkinshin** [comment]
I like this idea. Moreover, we can combine `BenchmarkInfo` with `BlackHole` from JMH and write an universal helper for our benchmark methods. I just have a few of important notes:
1. It should be a struct, `Counter` should be a public field of this struct.
2. If a target method has our magical argument, the corresponding `Idle` method also should has this argument.
3. We should carefully check that this argument doesn't have any side effects.

**Comment by mattwarren** [comment]
Sound good, I especially agree on 3), have you seen what magic tricks JMH does in [IterationParams](http://hg.openjdk.java.net/code-tools/jmh/file/0879b862a1a3/jmh-core/src/main/java/org/openjdk/jmh/infra/IterationParams.java)? I know a lot of it is due to false-sharing, so it only needed by multi-threaded benchmarks, but still!

Do you want them all in one class and have a general struct that contains everything, for instance `InfrastructureParams`?

Or should they be seperate and then you can just ask for what you want, i.e:

``` csharp
[Benchmark]        
public long BitwiseAnd(BenchmarkInfo info, Blackhole blackhole)
{
    blackHole.Consume(info.Counter & 1);
}
```

**Comment by AndreyAkinshin** [comment]
I want a single struct for all tasks. Also we can implement `Consume` as an extension method for .NET3.5+ projects (see https://github.com/minibench/minibench.skeet/blob/master/src/Minibench.Demo/MathBenchmarks.cs).

**Comment by mattwarren** [comment]
Okay, I'll start with (or do you want another name?)

``` csharp
public struct InfrastructureParams
{
    public long Counter;
    public long BatchSize;
}
```

However if I use fields, what's to stop the user of it changing the values and messing up the benchmarks, i.e

``` csharp
[Benchmark]        
public long BitwiseAnd(InfrastructureParams infrastructure)
{
    infrastructure.Counter = 0; // oh-dear!!!!
    .....
}
```

**Comment by AndreyAkinshin** [comment]
Don't worry about it, we will reset the value for each iteration.

P. S. Yes, I want another name, but I don't know a good one. =)

**Comment by mattwarren** [comment]
> Don't worry about it, we will reset the value for each iteration.
oh yeah, good point

> P. S. Yes, I want another name, but I don't know a good one. =)
I'll keep thinking :-)

**Comment by AndreyAkinshin** [comment]
It turns out that such approach can affect benchmark results. So, I removed all the related code. If someone need a counter, he should implement it manually.
