### ISSUE TITLE
Params results should be grouped together

### ISSUE THREAD

**Issue by redknightlois** [PerfDotNet/BenchmarkDotNet#36]
Currently when using Params will group the results first by benchmark function, and then by size. Given that the usage of Params is usually to benchmark the same implementation along the size axis, it would make more sense to group by size first and then by benchmark function to allow better comparisons.

**Comment by mattwarren** [comment]
I've just pushed a change that fixes this, now when you are using `Params` you get the output shown below:

![image](https://cloud.githubusercontent.com/assets/157298/11147520/53746224-8a0e-11e5-9611-12a63f1551b9.png)

**Comment by benaadams** [comment]
:+1:
