### ISSUE TITLE
Support for initialization of parameter size. 

### ISSUE THREAD

**Issue by redknightlois** [PerfDotNet/BenchmarkDotNet#38]
Currently this pattern is not supported. 

```csharp
[Params(8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 4096 * 10, 4096 * 100, 4096 * 1000)]
public int Size = 1;

private byte[] src;
private byte[] dest;

public MemoryPerf(int size)
{
    src = new byte[size];
    dest = new byte[size];
    new Random(42).NextBytes(src);

    Console.WriteLine(size);
}
```

**Comment by mattwarren** [comment]
Not sure I'm following this one, why not just write:

```
[Params(1, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 4096 * 10, 4096 * 100, 4096 * 1000)]
public int Size = 0;
```

**Comment by redknightlois** [comment]
The problem is this:

```csharp
private byte[] src;
private byte[] dest;
```

Because then the code for the test will look like:
```
[Benchmark]
public void CopyNaive ()
{
   if ( !IsInitialized ) Initialize();

   for( int i = 0; i < src.Lenght; i++ )
      dest[i] = src[i];  
}
```
Therefore, we are adding the benchmark a comparison and a jump that are not part of the function but a requirement for the infrastructure.

**Comment by AndreyAkinshin** [comment]
@redknightlois, we have the [Setup](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/SetupAttribute.cs) attribute for initializing. It should run once before the main benchmark iterations.
@mattwarren, does `Setup` works correctly with `Params`?

**Comment by mattwarren** [comment]
You can use the `[Setup]` method to do this, i.e.

``` csharp
[Setup]
public void Setup()
{
    src = new byte[1];
    new Random(42).NextBytes(src);
    dest = new byte[1];
}

[Benchmark]
public void Benchmark()
{
    // Benchmark goes here
}
```

Or am I mis-understanding what you are trying to do?

**Comment by mattwarren** [comment]
> .. does Setup works correctly with Params?

Good question, I'll try it out

**Comment by redknightlois** [comment]
Didn't know that. That would be what we need if the initialization of params happens before setup. Probably making it more visible in the docs?

**Comment by mattwarren** [comment]
I just checked the code and `[Params]` and `[Setup]` should play nicely together. 

The `[Params]` field/property is set before the `[Setup]` and `[Benchmark]` method are run, so they both get the same value.

**Comment by mattwarren** [comment]
@redknightlois 

> Probably making it more visible in the docs?

Finally done, see the new section in the docs [**Advanced Features**](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/README.md#advanced-features)
