### ISSUE TITLE
Seems, not supported "sub-folder"

### ISSUE THREAD

**Issue by constructor-igor** [PerfDotNet/BenchmarkDotNet#41]
My binaries folder has next structure:
```
folder        Compilation
folder       Compilation\Common\
tesproject TestProject.dll
```

I added test in TestProject 
```c#
    [TestFixture]
    public class BenchmarkTests
    {
        public BenchmarkTests()
        {
        }
        [Benchmark]
        public void ByDoubleReader()
        {
            <code>
        }

        [Test]
        public void BenchMark()
        {
            new BenchmarkRunner().RunCompetition(new BenchmarkTests());
        }
    }
```
and found next problem:
folder <root>\Compilation\BenchmarkTests_ByDoubleReader_Throughput_HostPlatform_HostJit_NET-HostFramework
doesn't contain subfolder Common and "benchmark" cannot be loaded

**Comment by AndreyAkinshin** [comment]
@constructor-igor, I'm not completely understand your situation. Can you share a minimal reproducible example?

**Comment by constructor-igor** [comment]
@AndreyAkinshin I'll try to prepare the sample.
Main idea: binary folder contains subfolder and test project has reference to other binaries from the subfolder.

**Comment by constructor-igor** [comment]
https://github.com/constructor-igor/TechSugar/tree/master/BenchmarkingLab/BenchmarkDotNet
working sample: BenchmarkWorkingSample
problem sample: BenchmarkProblemSample

**Comment by mattwarren** [comment]
I'll take a look at this, I think it's similar to #42

**Comment by mattwarren** [comment]
Okay, I've looked at this a bit more and I've been able to reproduce it outside of your test.

However I'm not entirely sure that we want to support this.

Let me explain, to make this happen you have to do **all** of the following steps:
  1. Add a reference to a 3rd party dll **directly** (**not** as a [project reference](https://msdn.microsoft.com/en-us/library/f3st0d45.aspx#Anchor_1)), i.e. in VS you do "Add Reference" -> "Browse..".
  1. You have to build your 3rd party dll into a separate folder "..\Binaries\Common", compared to you main dll "..\Binaries"
  1. For the dll you've just added, you need to set Copy Local = **false**, which ends up a `<Private>True</Private>` in [your .csproj file](https://github.com/constructor-igor/TechSugar/blob/master/BenchmarkingLab/BenchmarkDotNet/BenchmarkDotNet/BenchmarkDotNetLab.csproj#L34-L37). If you set Copy Local = **true**, it would work as VS would copy over the 3rd party dll for you (BusinessLogic.dll in your case) to the "..\Binaries" folder from "..\Binaries\Common".

I'm not sure this is a common scenario, @constructor-igor can you explain why you build your projects this way, especially why you have **Copy Local = false**?

**Comment by constructor-igor** [comment]
I build "test projects" to folder Compilation and "actual code projects" to Compilation\Common. It allows to separate "test" and "production" binaries.
Also "copy local = false" (if a solution has many projects/references) works faster than "copy local = true" (at least, when I checked compilation time several years ago).

**Comment by smudge202** [comment]
Late to the party, but my company has a similar approach to @constructor-igor with regards to test output locations and `copy local`.

**Comment by mattwarren** [comment]
@smudge202 and @constructor-igor thanks for the input.

I'll see what I can do to make BenchmarkDotNet work in these scenarios.
