### ISSUE TITLE
Generated code fails to build

### ISSUE THREAD

**Issue by thomaslevesque** [PerfDotNet/BenchmarkDotNet#42]
I tried to run a small benchmark from LINQPad, and the generated code fails to compile:
```
using System;
using System.Diagnostics;
using System.Threading;
using System.Runtime.CompilerServices;
using BenchmarkDotNet;
using BenchmarkDotNet.Tasks;
using ;
using System;



namespace BenchmarkDotNet.Autogenerated
{
    public class Program : UserQuery.CallStyleBenchmark
    {
        public static void Main(string[] args)
        {
...
```

This is caused by the empty `using` clause on line 7

**Comment by AndreyAkinshin** [comment]
@thomaslevesque, can you share a repro for the issue?

**Comment by thomaslevesque** [comment]
I think this is because LINQPad's UserQuery class is not in a namespace, but [the template expects a namespace](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Templates/BenchmarkProgram.txt#L7).

**Comment by thomaslevesque** [comment]
@AndreyAkinshin, just try to create *any* benchmark in LINQPad. Given the cause of the issue, I'm pretty sure it can be reproduced every time.

**Comment by thomaslevesque** [comment]
OK, I just tried to fix the code to handle this case, but there's another issue. BenchmarkDotNet seems to assume that all required assemblies are in the working directory, but it's not necessarily the case. In fact, it's definitely not the case when running a LinqPad query.

**Comment by AndreyAkinshin** [comment]
@thomaslevesque, ok, thanks for the investigation, I will try to fix it.

**Comment by mattwarren** [comment]
@thomaslevesque I'm just taking a look at this, sorry for the delay.

Just to make sure I'm testing in the same way as you, in LINQPad I assume you have your Benchmark setup something like this (sorry, I'm no LINQPad expert, so I don't know if this is the natural way to do it or not)?

![image](https://cloud.githubusercontent.com/assets/157298/11098988/894ea69e-88a0-11e5-811a-b3d6a23efb39.png)

![image](https://cloud.githubusercontent.com/assets/157298/11098964/5d1f5212-88a0-11e5-9a65-a9d78e8561e6.png)

**Comment by mattwarren** [comment]
Either way, I see the same problem, here's my output:

```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   Intro_00_Basic_Sleep (SingleRun_HostPlatform_HostJit_NET-HostFramework)
//   Thread.Sleep(100) (SingleRun_HostPlatform_HostJit_NET-HostFramework)

// **************************
// Benchmark: Intro_00_Basic_Sleep (SingleRun_HostPlatform_HostJit_NET-HostFramework)
// *** Generate *** 
// Result = Success
// DirectoryPath = C:\Program Files (x86)\LINQPad4\Intro_00_Basic_Sleep_SingleRun_HostPlatform_HostJit_NET-HostFramework

// *** Build ***
// Program.cs(7,7): error CS1001: Identifier expected
// Result = Failure


// **************************
// Benchmark: Thread.Sleep(100) (SingleRun_HostPlatform_HostJit_NET-HostFramework)
// *** Generate *** 
// Result = Success
// DirectoryPath = C:\Program Files (x86)\LINQPad4\Intro_00_Basic_SleepWithDescription_SingleRun_HostPlatform_HostJit_NET-HostFramework

// *** Build ***
// Program.cs(7,7): error CS1001: Identifier expected
// Result = Failure


// ***** BenchmarkRunner: Finish  *****

BenchmarkDotNet-Dev=v0.7.8.0+
OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz, ProcessorCount=8
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit 
There are no found benchmarks

Benchmarks with troubles:
  Intro_00_Basic_Sleep_SingleRun_HostPlatform_HostJit_NET-HostFramework
  Intro_00_Basic_SleepWithDescription_SingleRun_HostPlatform_HostJit_NET-HostFramework

// ***** BenchmarkRunner: End *****
```

**Comment by thomaslevesque** [comment]
> in LINQPad I assume you have your Benchmark setup something like this

Yes (assuming you also have a Main method that's not visible in your screenshot)

The namespace issue is easy to fix. To fix the missing assembly issue, I think the referenced assemblies will have to be copied.

**Comment by mattwarren** [comment]
> The namespace issue is easy to fix. To fix the missing assembly issue, I think the referenced assemblies will have to be copied.

I just checked in a fix that does exactly this, when you get a chance can you try it out?

**Comment by thomaslevesque** [comment]
> I just checked in a fix that does exactly this, when you get a chance can you try it out?

Sure, I'll do this ASAP. Is there a pre-release NuGet package available with the fix, or do I have to build it from source?

**Comment by AndreyAkinshin** [comment]
@thomaslevesque, for now you should build it from source (VisualStudio 2015 is required).

**Comment by thomaslevesque** [comment]
It works fine now :+1:

**Comment by AndreyAkinshin** [comment]
@thomaslevesque, cool! I will update the NuGet package on the weekend.

**Comment by mattwarren** [comment]
@thomaslevesque thanks for confirming the fix
