### ISSUE TITLE
Add support for benchmarking methods of generic classes

### ISSUE THREAD

**Issue by HellBrick** [PerfDotNet/BenchmarkDotNet#44]
At the moment `BenchmarkRunner` throws `InvalidOperationException` if the class that contains the benchmarked methods is generic. Unfortunately, it cripples code reuse if you want to create separate benchmarks for some generic method by using it with different type arguments. Here's an example of what I'd like to achieve:

```csharp
public abstract class AbstractBenchmark<T>
{
	private readonly T _value;
	private readonly Serializer1<T> _serializer1 = new Serializer1<T>();
	private readonly Serializer2<T> _serializer1 = new Serializer2<T>();

	protected AbstractBenchmark()
	{
		_value = CreateValue();
	}

	protected abstract T CreateValue();

	[Benchmark]
	public void SerializationLibrary1()
	{
		string text = _serializer1.Serialize( _value );
	}

	[Benchmark]
	public void SerializationLibrary2()
	{
		string text = _serializer2.Serialize( _value );
	}
}

public class FlatClassBenchmark : AbstractBenchmark<FlatClass>
{
	protected override FlatClass CreateValue() => new FlatClass() { Number = 42, Text = "64", TimeStamp = DateTime.UtcNow };
}

public class DoubleArrayBenchmark : AbstractBenchmark<double[]>
{
	protected override double[] CreateValue() => Enumerable.Repeat( 42.0, 100 * 1000 ).ToArray();
}

// etc.
```

Unless there's a compelling technical reason to prohibit similar scenarios, I believe lifting this ban on benchmarking generic classes would be quite convenient.

**Comment by AndreyAkinshin** [comment]
Thanks for the report, I will investigate the issue.

**Comment by mattwarren** [comment]
@AndreyAkinshin I have a check-in ready to go that removes the 2 calls to `AssertMethodIsNotDeclaredInGeneric(..)`, from [here](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/BenchmarkConverter.cs#L25) and [here](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/BenchmarkConverter.cs#L38).

I also have a passing integration test (based on the code above), that shows that removing this check is okay.

But I just wanted to check, what was your original motivation for putting this check in? 

Is there a correctness or performance reason that we should prevent Benchmarks declared in generic classes?

**Comment by AndreyAkinshin** [comment]
I found the commit with these asserts: https://github.com/PerfDotNet/BenchmarkDotNet/commit/d70b4cd339c3c40a3a1f7b996b4004ba59c25ff4
@krk, any comments?

**Comment by mattwarren** [comment]
I'm just going to check in the change, it's easy to back-out if we later find a problem.

I think all the other checks in d70b4cd are valid (`AssertBenchmarkMethodIsAccessible` and `AssertBenchmarkMethodIsNotGeneric`), but as shown by the code sample from @HellBrick `AssertBenchmarkMethodIsNotDeclaredInGeneric` prevents some valid scenarios.

**Comment by AndreyAkinshin** [comment]
@mattwarren, ok, let's remove these checks.

**Comment by hiradyazdan** [comment]
@AndreyAkinshin I hope my question doesn't sound too dumb, but why is there no support for only generic methods, and just assigning the generic type argument on the method itself than on the class?

**Comment by adamsitnik** [comment]
@hiradyazdan This is due to current BDN design. To achieve process level isolation and avoid some common benchmarking pitfalls, BenchmarkDotNet generates, builds and run a new project with some boilerplate code.

You can see our template here: https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Templates/BenchmarkType.txt

To tell the long story short, it was easier to implement it on a class rather than method level. If you would like to send a PR that implements support on method level, it would be great.

**Comment by hiradyazdan** [comment]
@adamsitnik I see, Thanks. I am not familiar enough with the implementations and reasonings behind, hence the question mark in my head :)
