### ISSUE TITLE
Benchmark method can't return inner classes

### ISSUE THREAD

**Issue by gluck** [PerfDotNet/BenchmarkDotNet#55]
When benchmark method returns an inner class (tested with a return type `Tuple<Foo.Bar, Foo>`), the generated `Program.cs` built doesn't compile as it references:

    private System.Tuple<Bar, Foo> value;

(complains that Bar doesn't exist)

The outer class qualifier is missing.

**Comment by AndreyAkinshin** [comment]
@mattwarren, can you investigate the issue?

**Comment by mattwarren** [comment]
Yeah I'll take a look (seems similar to #49) we need to be more clever in determining what the dependencies of the Benchmark really are.

**Comment by smudge202** [comment]
Wouldn't it be easier if that whole process was symbol based (not string)? Was there a reason for the current mechanism versus reflection and emission?

**Comment by mattwarren** [comment]
@gluck I've just checked in a fix for this, sorry for the long delay!

**Comment by gluck** [comment]
:+1: no worries, I should've mentioned that changing the return type to object was a fine workaround.

Thx !

**Comment by mattwarren** [comment]
> I should've mentioned that changing the return type to object was a fine workaround.

Oh yeah, I didn't think about that. But at least now it'll work OOTB without you having to resort to hacky workarounds.
