### ISSUE TITLE
# of GC Collections [Diagnostic/Diagnoser]

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#56]
While working on a Benchmark for a [dotnet/corefx issue](https://github.com/dotnet/corefx/issues/2102#issuecomment-160149357) that I was following, I did a quick hack to calculate the # of Gen0, Gen1 and Gen2 Collections during a Benchmark run/batch. At the moment it gives you results like so:
```
                                                                    | GC Collections per 1 million ops  |
    Method | StringLength |     AvrTime |    StdDev |          op/s |      Gen0 |      Gen1 |      Gen2 |
---------- |------------- |------------ |---------- |-------------- |-----------|-----------|-----------|
  Original |            1 |  42.4204 ns | 0.2792 ns | 23,573,547.49 |     10.17 |      0.00 |      0.00 |
  Improved |            1 |  34.2644 ns | 0.5882 ns | 29,185,409.98 |      0.00 |      0.00 |      0.00 |
  Original |            5 |  51.4178 ns | 0.5020 ns | 19,448,520.71 |     12.70 |      0.00 |      0.00 |
  Improved |            5 |  40.5619 ns | 0.4539 ns | 24,653,698.63 |      0.00 |      0.00 |      0.00 |
  Original |           10 |  65.3267 ns | 4.1725 ns | 15,307,753.00 |     15.25 |      0.00 |      0.00 |
  Improved |           10 |  53.0060 ns | 0.7845 ns | 18,865,819.59 |      0.00 |      0.00 |      0.00 |
  Original |           20 |  72.5353 ns | 3.3984 ns | 13,787,096.28 |     22.86 |      0.00 |      0.00 |
  Improved |           20 |  57.9108 ns | 0.6775 ns | 17,267,957.76 |      0.00 |      0.00 |      0.00 |
  Original |           50 | 239.1619 ns | 4.2924 ns |  4,181,363.40 |     40.61 |      0.00 |      0.00 |
  Improved |           50 | 222.7882 ns | 4.3712 ns |  4,488,568.45 |      0.00 |      0.00 |      0.00 |
```

What do you think about having this included in BenchmarkDotNet as a real feature? It's very useful for comparing 2 benchmarks, one that does allocations and one that is allocation free.

Questions:
  1. Could it go in core (rather than Diagnostics) as it only relies on `GC.CollectionCount(..)`?
  2. It would be nice to have the results integrated into the final result table (as above), rather than just output to the console, is this okay?

Just FYI, I have plans for a proper Memory Allocation Diagnostics, based on ETW events. But that requires more work and is for slightly different scenarios. It would give you the memory allocated per/line, something like this:

``` csharp
               [Setup]
               public void Setup()
               {
108.0K|            var stringToEncodeBuilder = new StringBuilder();
                   for (int i = 'a'; i < ('a' + StringLength); i++)
                   {
                       stringToEncodeBuilder.Append((char)i);
                   }
                   var stringToEncode = stringToEncodeBuilder.ToString();
                   UTF8Bytes = encoding.GetBytes(stringToEncode);
       
                   // From http://stackoverflow.com/a/537652/4500
                   unmanagedPointer = Marshal.AllocHGlobal(UTF8Bytes.Length);
                   Marshal.Copy(UTF8Bytes, 0, unmanagedPointer, UTF8Bytes.Length);
                   bytes = (byte *)unmanagedPointer.ToPointer();
    
                   // force StringBuilder to pre-allocate, so it doesn't have to grow during the benchmark runs
                   if (builder == null)
500.0M|                builder = new StringBuilder(250 * 1000 * 1000);
                   else
577.6M|                builder.Clear();
               }
```

**Comment by smudge202** [comment]
It's a really nice piece of information. My only question is, will it work with CoreCLR?

**Comment by mattwarren** [comment]
Good question, how/where do I check if `GC.CollectionCount(..)` is available?

**Comment by AndreyAkinshin** [comment]
LGTM, it is a very cool feature. 
I think, it should works fine with CoreCLR because it is basic .NET API. But I will check it tonight.
Some thoughts about implementation: I think, diagnosers should have special API that will add additional columns to the result table.

**Comment by smudge202** [comment]
With regards to adding columns to results column; I wonder if that could play into the suggestion I've made on #54? i.e. Not only provide DTO's for Import/Export, but allow the DTO's to be inherited and expanded upon? (i.e. each serializable/attributed property in the DTO would be a column in the results table when logging).

**Comment by mattwarren** [comment]
> Some thoughts about implementation: I think, diagnosers should have special API that will add additional columns to the result table.

yeah I agree, there's probably some *future* scenarios where we want extra columns in the results

**Comment by smudge202** [comment]
> Good question, how/where do I check if GC.CollectionCount(..) is available?

Personally I'd create a DNX Project: 
![dnx project](https://cloud.githubusercontent.com/assets/2247869/11472393/2125e604-9764-11e5-81ea-222cd80668a8.png)

Then add some TFM's to the `project.json`, along the lines of `dotnet1.1`, `dnxcore50`, `netcore45`, etc. and try to call `GC.CollectionCount(..)`. You'll need to bring in respective dependencies for the tfm's as per the error messages generated; the question is whether there are dependencies for each?

**Comment by mattwarren** [comment]
I think we're okay, just found the API list (assuming it's accurate). See http://dotnet.github.io/api/System.GC.html#System_GC_CollectionCount_System_Int32_

**Comment by xoofx** [comment]
Hi there!
@mattwarren is the GC report available on a fork somewhere? I'm looking exactly for this feature (GC.GetCollectionCount)

**Comment by mattwarren** [comment]
@xoofx not yet, but soon. See https://github.com/PerfDotNet/BenchmarkDotNet/blob/refactoring/BenchmarkDotNet.Diagnostics/GCDiagnoser.cs for the current WIP. At the moment it's logging the ETW events, but I haven't pushed the code that parses the events and displays the results. I plan to have it implemented within the next week.

Just one thing, I decided to go with ETW events as they give us more flexibility and more information compared to `GC.GetCollectionCount()`. For instance we can get an accurate `# of bytes allocated` which is hard when just using `GC.GetTotalMemory()`.

**Comment by xoofx** [comment]
GC ETW events will be just great, looking forward to this!

**Comment by mattwarren** [comment]
> GC ETW events will be just great, looking forward to this!

Cool, that's good to know.

**Comment by mattwarren** [comment]
This is finally done, see the recent commits in the "develop" branch https://github.com/PerfDotNet/BenchmarkDotNet/commits/develop

**Comment by xoofx** [comment]
That's great, thanks for this feature! I will come back here once I will have time to test it
