### ISSUE TITLE
Make Benchmark, Setup and Params attribute sealed in explicit way

### ISSUE THREAD

**Issue by smudge202** [PerfDotNet/BenchmarkDotNet#57]
In essence, the following two signatures are in contradiction with one another:

`GetCustomAttributes`: https://github.com/PerfDotNet/BenchmarkDotNet/blob/a2338ce6d6b971e0e7599ffc178fb90f2db1dacd/BenchmarkDotNet/Tasks/BenchmarkTask.cs#L25 (and line 27)

`BenchmarkTaskAttribute`:
https://github.com/PerfDotNet/BenchmarkDotNet/blob/a2338ce6d6b971e0e7599ffc178fb90f2db1dacd/BenchmarkDotNet/Tasks/BenchmarkTaskAttribute.cs#L6

The attribute is not sealed (can be inherited) but discovery will not find inherited attributes. We should pick one way or t'other.

@Metallium in gitter has been asking for a simple way to configure shorter/low load benchmarks, which @mattwarren suggest could be done as follows:

```c#
[BenchmarkTask(mode: BenchmarkMode.SingleRun, processCount: 1, warmupIterationCount: 1, targetIterationCount: 1)] 
\\i.e. "SingleRun"`
```

This could be made simpler still by inheriting from `BenchmarkTask` and predefining the above settings in the base .ctor.

Therefore, I recommend we go for keeping the attribute unsealed, and changing the `GetCustomAttribute` calls, as opposed to the other way around.

**Comment by adamsitnik** [comment]
I have checked the code, majority was using `inherit: false` with Benchmark, Params and Setup attributes. So I decided to go with sealed just to make it clear that these classes are non-inheritable.
