### ISSUE TITLE
Win32Exception when trying to benchmark

### ISSUE THREAD

**Issue by mumusan** [PerfDotNet/BenchmarkDotNet#6]
After updating to 0.7.* having exception when launching benchmark.

http://i.imgur.com/3srpxqo.png

**Comment by AndreyAkinshin** [comment]
I have [updated](https://github.com/mumusan/dotnetex/commit/f5545bc96998bcc8d33b80b1feda98e46980cb66) BenchmarkDotNet in [dotnetex](https://github.com/mumusan/dotnetex) to v0.7.4. Now it works fine on my computer. Please, check it.

**Comment by mumusan** [comment]
Nope, continuing failing with same error. Tried as Admin, result the same.

**Comment by AndreyAkinshin** [comment]
Do you have MSBuild in the `%PATH%` variable? If not, you should add it because BenchmarkDotNet use it for building each benchmark.

**Comment by AndreyAkinshin** [comment]
Is it works now?

**Comment by danilanv** [comment]
Had the same issue, but hen added MSBuild to %PATH% the problem with Win32Exception disapeared, but now a ihave another problem: when i run benchmark a i have next error:
Target competition: Crc16Bench
// ***** Competition: Start   *****
// Found benchmarks:
//   Crc16Bench_Data4_Throughput_X64_CurrentJit_NET-Current -w=5 -t=10
//   Crc16Bench_Data4_Throughput_X86_CurrentJit_NET-Current -w=5 -t=10

// **************************
// Benchmark: Crc16Bench_Data4 (Throughput_X64_CurrentJit_NET-Current) [-w=5 -t=10]
// Generated project: c:\Users\danila\Documents\Visual Studio 2013\Projects\Crc16Benchmark\Crc16Bench\bin\Release\Crc16Bench_Data4_Throughput_X64_CurrentJit_NET-Current

// Build:
Build failed
Fail

// Run, Process: 1 / 3
// Platform=X64 
// Run, Process: 2 / 3
// Platform=X64 
// Run, Process: 3 / 3
// Platform=X64 

AverageTime (ns/op): Median = 0; StdDev = Infinity; Min = 0; Max = 0;
OperationsPerSecond: Median = 0; StdDev = Infinity; Min = 0; Max = 0;

// **************************
// Benchmark: Crc16Bench_Data4 (Throughput_X86_CurrentJit_NET-Current) [-w=5 -t=10]
// Generated project: c:\Users\danila\Documents\Visual Studio 2013\Projects\Crc16Benchmark\Crc16Bench\bin\Release\Crc16Bench_Data4_Throughput_X86_CurrentJit_NET-Current

// Build:
Build failed
Fail

// Run, Process: 1 / 3
// Platform=X86 
// Run, Process: 2 / 3
// Platform=X86 
// Run, Process: 3 / 3
// Platform=X86 

AverageTime (ns/op): Median = 0; StdDev = Infinity; Min = 0; Max = 0;
OperationsPerSecond: Median = 0; StdDev = Infinity; Min = 0; Max = 0;

// ***** Competition: Finish  *****

// BenchmarkDotNet=v0.7.4.0
// OS=Microsoft Windows NT 6.1.7601 Service Pack 1
// Processor=Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz, ProcessorCount=4
// CLR=MS.NET 4.0.30319.18444, Arch=64-bit 
Common:  Type=Crc16Bench  Method=Data4  Mode=Throughput  Jit=CurrentJit  .NET=Current  

 Platform |     AvrTime |     StdDev | op/s |
--------- |------------ |----------- |----- |
      X64 | 0.000000 ns | Infinity s |    0 |
      X86 | 0.000000 ns | Infinity s |    0 |

// ***** Competition: End *****

**Comment by damageboy** [comment]
Same here...

**Comment by olsh** [comment]
@danilanv 
You have to remove white spaces, cyrillic symbols etc. in the solution path.
I suppose [the second argument](https://github.com/PerfDotNet/BenchmarkDotNet/blob/641c95140834aa726c39b19bc98b932bd3abcb61/BenchmarkDotNet/BenchmarkProjectGenerator.cs#L25) should be enclosed in quotes.

**Comment by damageboy** [comment]
@olsh @danilanv I solve my issue as well, for me it was actually the fact the benchmark class was an inner class, which caused BenchMarkDotNet to generate wierd class names with `+` in the class name...

**Comment by AndreyAkinshin** [comment]
@mumusan, @danilanv, @damageboy , @olsh 
I have implemented new build system via API from the Microsoft.Build assembly. Please, check version 0.7.5.

**Comment by danilanv** [comment]
version 0.7.5 - it works!

**Comment by damageboy** [comment]
Same for me, nicer integration with Life(tm)

**Comment by AndreyAkinshin** [comment]
@danilanv, @damageboy, great!
