### ISSUE TITLE
Missed BenchmarkDotNet.Diagnostics shouldn't throw an exception

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#63]
It is a normal situation (e.g. uses installed the library from NuGet), we shouldn't throw an exception.
Repro: just try to install the v0.8.0 from NuGet and run any benchmark.

**Comment by mattwarren** [comment]
sigh! 

Thanks for spotting that, (what's the actual error BTW?)

**Comment by AndreyAkinshin** [comment]
```
Error loading BenchmarkDotNet.Diagnostics.dll: Could not load file or assembly 'file:///D:\...\bin\Release\BenchmarkDotNet.Diagnostics.dll' or one of its dependencies.
```
