### ISSUE TITLE
Add a "Delta v. Baseline" column

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#64]
As per [this benchmark](https://github.com/IllyriadGames/ByteArrayExtensions), it would be nice if we could automatically produce the "% Delta v..." column, rather than users having to add it by hand.

![image](https://cloud.githubusercontent.com/assets/157298/11929930/0ab2456a-a7d7-11e5-9e45-571a50648198.png)

If could either be a '%' or an absolute value in ms/ns. Also the baseline benchmark would need to be specified, probably via an attribute, such as `[BenchmarkBaseline]` or maybe `[Benchmark(baseline: true)]`

**Comment by AndreyAkinshin** [comment]
@mattwarren, good idea, I like it.

**Comment by mattwarren** [comment]
This is now implemented, you use by adding `Baseline = true` to **one** benchmark in a class:

``` csharp
[Benchmark(Baseline = true)]
public void BenchmarkSlow()
{
	Thread.Sleep(100);
}

[Benchmark]
public void BenchmarkFast()
{
	Thread.Sleep(5);
}
```

Then you will get an output like so (note the added column "+/- Delta"):

![image](https://cloud.githubusercontent.com/assets/157298/12357085/e6943b72-bb9d-11e5-83d5-3e611f960d8e.png)
