### ISSUE TITLE
Differentiate visualy between runs wih different params

### ISSUE THREAD

**Issue by omariom** [PerfDotNet/BenchmarkDotNet#73]
Here is a motivating example: 

            Method | IntParam |       AvrTime |      StdDev |          op/s |
------------------- |--------- |-------------- |------------ |-------------- |
 **CharArrayEnumerate** |       **32** |    49.2961 ns |   3.6292 ns | 20,377,871.52 |
     SliceEnumerate |       32 |    62.9922 ns |   7.4198 ns | 16,095,370.12 |
 Old SliceEnumerate |       32 |   131.9806 ns |  14.2321 ns | 7,674,816.42 |
           SliceFor |       32 |    70.7580 ns |   8.0914 ns | 14,347,210.48 |
   SliceForOverCopy |       32 |    69.4842 ns |   8.2355 ns | 14,632,672.63 |
    StringEnumerate |       32 |    59.2151 ns |   7.2610 ns | 17,140,242.69 |
 **CharArrayEnumerate** |      **64** |    81.9880 ns |   9.6633 ns | 12,366,290.75 |
     SliceEnumerate |       64 |   111.9105 ns |  11.0659 ns |  9,038,154.79 |
 Old SliceEnumerate |       64 |   222.8495 ns |  27.2687 ns | 4,555,964.71 |
           SliceFor |       64 |   125.5091 ns |  25.6399 ns |  8,247,058.59 |
   SliceForOverCopy |       64 |   113.2226 ns |   9.1383 ns |  8,897,281.69 |
    StringEnumerate |       64 |    92.0331 ns |   9.1048 ns | 10,985,891.34 |
 **CharArrayEnumerate** |      **256** |   260.2960 ns |  27.8021 ns |  3,892,529.13 |
     SliceEnumerate |      256 |   376.1686 ns |  30.7678 ns |  2,678,382.81 |
 Old SliceEnumerate |      256 |   835.3019 ns |  59.0363 ns | 1,203,468.77 |
           SliceFor |      256 |   391.3873 ns |  46.6426 ns |  2,591,649.95 |
   SliceForOverCopy |      256 |   375.9711 ns |   4.4155 ns |  2,660,124.57 |
    StringEnumerate |      256 |   266.7515 ns |  28.5489 ns |  3,798,745.15 |

**Comment by AndreyAkinshin** [comment]
Ok, it is easy to add to the file with github report. But how it should look in the console log?
@mattwarren, what do you think?

**Comment by mattwarren** [comment]
Yeah it's a nice idea, it his hard to scan the results when you are using `[Params]`.

In the console we might have to use a different colour, rather than making it bold, unless we use http://colorfulconsole.com/?

**Comment by AndreyAkinshin** [comment]
I don't want to have any 3rd-party dependencies.

**Comment by mattwarren** [comment]
@omariom @AndreyAkinshin what do you think looks best in the console? In Markdown we pretty much have to do it using **bold text**, we can't use colours like this.

**Option 1:**

![image](https://cloud.githubusercontent.com/assets/157298/13060489/c4d72874-d429-11e5-9c6c-fa07ec7e1d96.png)

**Option 2:**

![image](https://cloud.githubusercontent.com/assets/157298/13060632/c3dfd802-d42a-11e5-8fc6-21bb7e8b0261.png)

Or something else? (FWIW I reckon Option 2 will work best, but feel free to disagree)

Also, should this be turned on be default for any benchmark with a `[Param]` or should it only be enabled with a flag?

**Comment by omariom** [comment]
Wow! 
Option 2 looks great :+1:

**Comment by mattwarren** [comment]
cool, @AndreyAkinshin are you happy with it being the default to have the rows coloured like this (when the benchmark has `[Params()]`?

![image](https://cloud.githubusercontent.com/assets/157298/13079420/07f1b2f4-d4bc-11e5-822c-17b258a20f78.png)

**Comment by AndreyAkinshin** [comment]
LGTM

**Comment by mattwarren** [comment]
Method |     Median |    StdDev |  B | C |
----------- |----------- |---------- |--- |-- |
 **BenchmarkA** | **10.8005 ms** | **0.0000 ms** | **10** | **1** |
 BenchmarkB | 10.8655 ms | 0.0000 ms | 10 | 1 |
 BenchmarkC | 10.7374 ms | 0.0000 ms | 10 | 1 |
 **BenchmarkA** | **11.1841 ms** | **0.0000 ms** | **10** | **2** |
 BenchmarkB | 11.7211 ms | 0.0000 ms | 10 | 2 |
 BenchmarkC | 11.8318 ms | 0.0000 ms | 10 | 2 |
 **BenchmarkA** | **12.8820 ms** | **0.0000 ms** | **10** | **3** |
 BenchmarkB | 12.9162 ms | 0.0000 ms | 10 | 3 |
 BenchmarkC | 12.6232 ms | 0.0000 ms | 10 | 3 |
 **BenchmarkA** | **13.2899 ms** | **0.0000 ms** | **10** | **4** |
 BenchmarkB | 13.5472 ms | 0.0000 ms | 10 | 4 |
 BenchmarkC | 13.9646 ms | 0.0000 ms | 10 | 4 |
 **BenchmarkA** | **14.9795 ms** | **0.0000 ms** | **10** | **5** |
 BenchmarkB | 14.7864 ms | 0.0000 ms | 10 | 5 |
 BenchmarkC | 14.8689 ms | 0.0000 ms | 10 | 5 |
 **BenchmarkA** | **20.9157 ms** | **0.0000 ms** | **20** | **1** |
 BenchmarkB | 20.9484 ms | 0.0000 ms | 20 | 1 |
 BenchmarkC | 20.1923 ms | 0.0000 ms | 20 | 1 |
 **BenchmarkA** | **22.0750 ms** | **0.0000 ms** | **20** | **2** |
 BenchmarkB | 22.0252 ms | 0.0000 ms | 20 | 2 |
 BenchmarkC | 21.9515 ms | 0.0000 ms | 20 | 2 |
 **BenchmarkA** | **22.9101 ms** | **0.0000 ms** | **20** | **3** |
 BenchmarkB | 22.1689 ms | 0.0000 ms | 20 | 3 |
 BenchmarkC | 22.6441 ms | 0.0000 ms | 20 | 3 |
 **BenchmarkA** | **24.0083 ms** | **0.0000 ms** | **20** | **4** |
 BenchmarkB | 23.8418 ms | 0.0000 ms | 20 | 4 |
 BenchmarkC | 23.2636 ms | 0.0000 ms | 20 | 4 |
 **BenchmarkA** | **24.8453 ms** | **0.0000 ms** | **20** | **5** |
 BenchmarkB | 25.0175 ms | 0.0000 ms | 20 | 5 |
 BenchmarkC | 24.3835 ms | 0.0000 ms | 20 | 5 |
 **BenchmarkA** | **31.1472 ms** | **0.0000 ms** | **30** | **1** |
 BenchmarkB | 30.9719 ms | 0.0000 ms | 30 | 1 |
 BenchmarkC | 30.7097 ms | 0.0000 ms | 30 | 1 |
 **BenchmarkA** | **31.0563 ms** | **0.0000 ms** | **30** | **2** |
 BenchmarkB | 32.0123 ms | 0.0000 ms | 30 | 2 |
 BenchmarkC | 31.9473 ms | 0.0000 ms | 30 | 2 |
 **BenchmarkA** | **33.0040 ms** | **0.0000 ms** | **30** | **3** |
 BenchmarkB | 32.9945 ms | 0.0000 ms | 30 | 3 |
 BenchmarkC | 32.8718 ms | 0.0000 ms | 30 | 3 |
 **BenchmarkA** | **33.1971 ms** | **0.0000 ms** | **30** | **4** |
 BenchmarkB | 33.9478 ms | 0.0000 ms | 30 | 4 |
 BenchmarkC | 33.5328 ms | 0.0000 ms | 30 | 4 |
 **BenchmarkA** | **34.9069 ms** | **0.0000 ms** | **30** | **5** |
 BenchmarkB | 34.7841 ms | 0.0000 ms | 30 | 5 |
 BenchmarkC | 34.4906 ms | 0.0000 ms | 30 | 5 |
