### ISSUE TITLE
Allow users to set gcAllowVeryLargeObjects for Runtime Settings

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#76]
See MSDN page: [Runtime Settings Schema](https://msdn.microsoft.com/en-us/library/0kk0kk35.aspx)
We can implement some logic that will specify some parameters (e.g. [gcAllowVeryLargeObjects](https://msdn.microsoft.com/en-us/library/yhwwzef8.aspx), [gcConcurrent](https://msdn.microsoft.com/en-us/library/yhwwzef8.aspx), [gcServer](https://msdn.microsoft.com/en-us/library/ms229357.aspx) look useful). We can define default values and allow to specify custom values via attributes.

**Comment by AndreyAkinshin** [comment]
@mattwarren, what do you think?

**Comment by mattwarren** [comment]
You know what, I was thinking about this the other day, but only the `gcConcurrent` and `gcServer` settings. So yes, I think it's a good idea.

I guess you are thinking of adding them to `[BenchmarkTask()]`, like the existing `BenchmarkPlatform` and `BenchmarkJitVersion` options?

**Comment by AndreyAkinshin** [comment]
We already have a lot of parameters in `BenchmarkTask`, it starts to look ugly. Maybe we can create another way to add new settings?

**Comment by mattwarren** [comment]
> We already have a lot of parameters in BenchmarkTask, it starts to look ugly. 

Yeah that's a good point

> Maybe we can create another way to add new settings?

I'm not sure what is a good way to do it though?

**Comment by adamsitnik** [comment]
I have just tried to rewrite [LinqOptimizer](https://github.com/nessos/LinqOptimizer) project benchmarks to use BDN and failed because they were using <gcAllowVeryLargeObjects enabled="true" /> ;)

So there is a need for this feature ;)

**Comment by AndreyAkinshin** [comment]
@adamsitnik, am I right that now we can close this issue?

**Comment by adamsitnik** [comment]
@AndreyAkinshin gcAllowVeryLargeObjects is missing, I will add it right away
