### ISSUE TITLE
Add Params attribute

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#8]

**Comment by mattwarren** [comment]
Quick question, if you have the following code:

``` csharp
[Params(1, 10, 100, 1000, 10000)]
public int SomeValue { get; set; }
```

##### Option 1
Should a single benchmark be generated with a `Program.cs` that looks something like this (i.e. with multiple different runs within a single execution):
``` csharp
public static void Main(string[] args)
{
	System.Console.WriteLine(BenchmarkDotNet.EnvironmentHelper.GetFullEnvironmentInfo());
	Program instance = new Program();
	var settings = BenchmarkSettings.Parse(args);
	for (int paramValue in new [] { 1, 10, 100, 1000, 10000 })
	{
		System.Console.WriteLine("// Running Benchmark with Param: " + paramValue);
		instance.SomeValue = paramValue;
		instance.RunBenchmark(settings);
	}
	System.Console.WriteLine("// Benchmark finished");
}
```

##### Option 2
Or should it produce a single Benchmark per param, i.e. you would end up with a `Program.cs` that looks like this (and another with `instance.SomeValue = 10`, `instance.SomeValue = 100`, etc):
``` csharp
public static void Main(string[] args)
{
	System.Console.WriteLine(BenchmarkDotNet.EnvironmentHelper.GetFullEnvironmentInfo());
	Program instance = new Program();
	var settings = BenchmarkSettings.Parse(args);	
	System.Console.WriteLine("// Running Benchmark with Param: " + 10);
	instance.SomeValue = 1;
	instance.RunBenchmark(settings);
	System.Console.WriteLine("// Benchmark finished");
}
```

With **Option 2** you then end up with the following folder structure:
![image](https://cloud.githubusercontent.com/assets/157298/9619065/db1b387c-5103-11e5-80c2-efeb5653fd3a.png)

What's the correct level of separation needed when using `Params`? 

I'm thinking about it from a *correctness* point-of-view, i.e. could we get incorrect results by doing all the runs within a single execution (as in **Option 1**)

**Comment by AndreyAkinshin** [comment]
> I'm thinking about it from a correctness point-of-view, i.e. could we get incorrect results by doing all the runs within a single execution (as in Option 1)

In the Option 1, the benchmarks will be incorrect, you can't do it. On the other hand, Option 2 looks awkward: I don't want to create a separate project per param.

My suggestion is the following: what if we create a single project that take the parameters from command line args (maybe with some default values)?

**Comment by mattwarren** [comment]
Just so I understand what you mean, we will have a single project, that then spawns a new process for each parameter, is that correct?

At the moment BenchmarkDotNet.exe itself compiles and spans a new process. After these changes BenchmarkDotNet.exe will still compile/spawn a single process, but that process will then spawn another process (1 per param) in which the actual benchmark is executed, right?

**Comment by AndreyAkinshin** [comment]
> Just so I understand what you mean, we will have a single project, that then spawns a new process for each parameter, is that correct?

Yep. But «for each parameter set», not «for each parameter» (we can have several Params attirbute).

> At the moment BenchmarkDotNet.exe itself compiles and spans a new process.

We don't have BenchmarkDotNet.exe, we have only BenchmarkDotNet.dll. Maybe BenchmarkDotNet.Samples.exe (or any other executable assembly that uses BenchmarkDotNet).

> After these changes BenchmarkDotNet.exe will still compile/spawn a single process, but that process will then spawn another process (1 per param) in which the actual benchmark is executed, right?

Look, now we have the following scheme:
1. BenchmarkDotNet takes some class (e.g. MyBenchmark) and generates new project (e.g. MyBenchmarkProject).
2. BenchmarkDotNet builds MyBenchmarkProject.
3. BenchmarkDotNet runs `MyBenchmarkProject.exe`

Now, if we have the `[Params(1, 10, 100)]` for a property, then we should implement the following scheme:
1. BenchmarkDotNet takes some class (e.g. MyBenchmark) and generates new project (e.g. MyBenchmarkProject).
2. BenchmarkDotNet builds MyBenchmarkProject.
3. BenchmarkDotNet runs `MyBenchmarkProject.exe 1`, `MyBenchmarkProject.exe 10`, `MyBenchmarkProject.exe 100`.

**Comment by mattwarren** [comment]
Woot, we have parametrised benchmarks!!

![image](https://cloud.githubusercontent.com/assets/157298/9768840/3cd84eae-571e-11e5-8152-2094ce102d4a.png)

**Comment by AndreyAkinshin** [comment]
Hooray!

**Comment by mattwarren** [comment]
yeah it took a while longer that expected, but I think it's a nice feature

**Comment by AndreyAkinshin** [comment]
Also we can think about nice plots for the results:

![plot](https://cloud.githubusercontent.com/assets/2259237/9784434/d8d24374-57b3-11e5-9d83-1f78254aebcb.png)

```ini
BenchmarkDotNet=v0.7.7.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz, ProcessorCount=8
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit  [RyuJIT]
Type=Array_HeapAllocVsStackAlloc  Mode=Throughput  Platform=HostPlatform  Jit=HostJit  .NET=HostFramework
```

         Method | Param |         AvrTime |         StdDev |          op/s |
--------------- |------ |---------------- |--------------- |-------------- |
      GetSquare |    10 |      12.5370 ns |      0.4266 ns | 79,764,128.15 |
      GetSquare |   510 |     468.7304 ns |     14.4115 ns |  2,133,426.53 |
      GetSquare |  1010 |     914.9831 ns |     24.1747 ns |  1,092,917.34 |
      GetSquare |  1510 |   1,346.1778 ns |      5.3642 ns |    742,843.94 |
      GetSquare |  2010 |   1,779.0378 ns |     35.1124 ns |    562,101.63 |
      GetSquare |  2510 |   2,194.4687 ns |      4.5396 ns |    455,691.17 |
      GetSquare |  3010 |   2,614.7658 ns |     15.2249 ns |    382,443.43 |
      GetSquare |  3510 |   3,028.0137 ns |      7.0767 ns |    330,249.50 |
      GetSquare |  4010 |   3,440.6094 ns |      8.5126 ns |    290,646.19 |
      GetSquare |  6000 |   5,107.0714 ns |     10.3547 ns |    195,806.94 |
      GetSquare | 16000 |  13,491.1058 ns |     35.4066 ns |     74,122.91 |
      GetSquare | 26000 |  45,330.2201 ns |  1,855.3126 ns |     22,060.34 |
      GetSquare | 36000 |  63,135.6546 ns |    532.5392 ns |     15,838.91 |
      GetSquare | 46000 |  80,201.6285 ns |  1,659.7624 ns |     12,468.58 |
      GetSquare | 56000 |  97,078.9371 ns |  3,451.0268 ns |     10,300.90 |
      GetSquare | 66000 | 121,122.6225 ns | 10,982.9110 ns |      8,256.10 |
      GetSquare | 76000 | 145,490.1507 ns | 17,985.8843 ns |      6,873.86 |
      GetSquare | 86000 | 181,074.9933 ns |  6,400.1038 ns |      5,522.61 |
      GetSquare | 96000 | 203,747.2294 ns | 10,505.7586 ns |      4,908.05 |
 GetSquareStack |    10 |      10.4851 ns |      0.3381 ns | 95,373,401.84 |
 GetSquareStack |   510 |     461.3096 ns |      6.3651 ns |  2,167,741.77 |
 GetSquareStack |  1010 |     900.4831 ns |     23.7974 ns |  1,110,515.00 |
 GetSquareStack |  1510 |   1,354.8679 ns |    100.3706 ns |    738,079.57 |
 GetSquareStack |  2010 |   1,718.2167 ns |     54.4427 ns |    581,998.89 |
 GetSquareStack |  2510 |   2,145.1850 ns |     48.7217 ns |    466,160.43 |
 GetSquareStack |  3010 |   2,572.9934 ns |     17.2488 ns |    388,652.37 |
 GetSquareStack |  3510 |   3,035.4653 ns |    206.4381 ns |    329,438.83 |
 GetSquareStack |  4010 |   3,464.5307 ns |     30.7925 ns |    288,639.38 |
 GetSquareStack |  6000 |   5,085.8505 ns |    209.7213 ns |    196,624.02 |
 GetSquareStack | 16000 |  14,059.3556 ns |    334.4103 ns |     71,127.04 |
 GetSquareStack | 26000 |  23,092.0605 ns |  1,227.8239 ns |     43,304.93 |
 GetSquareStack | 36000 |  32,287.1964 ns |    595.8731 ns |     30,972.03 |
 GetSquareStack | 46000 |  41,594.0736 ns |  1,958.4039 ns |     24,041.89 |
 GetSquareStack | 56000 |  51,116.6320 ns |  3,458.5698 ns |     19,564.36 |
 GetSquareStack | 66000 |  59,754.2053 ns |  2,796.8764 ns |     16,735.23 |
 GetSquareStack | 76000 |  68,753.1520 ns |  1,522.4262 ns |     14,544.79 |
 GetSquareStack | 86000 |  77,405.9552 ns |  1,278.5723 ns |     12,918.90 |
 GetSquareStack | 96000 |  86,070.4555 ns |    260.9588 ns |     11,618.39 |

**Comment by mattwarren** [comment]
Nice, how are you generating that graph, it looks way better than an excel graph?

BTW this is pretty useful because it shows that our Benchmark gives the same result as the original [hand-written one](http://blogs.microsoft.co.il/sasha/2013/10/17/on-stackalloc-performance-and-the-large-object-heap/). If you compare the graph from the blog post (below) with your one, they look the same!

![image](https://cloud.githubusercontent.com/assets/157298/9785176/3a03944c-57a8-11e5-91a2-fdeaf2bd6a1e.png)

**Comment by AndreyAkinshin** [comment]
I wrote small R-script:

```r
library(ggplot2)
sourceFile <- "Array_HeapAllocVsStackAlloc-report.csv"
df <- read.csv(file = sourceFile, head = TRUE, sep = ";")
ggplot(df, aes(x = Param, y = AvrTime, colour = Method)) + 
  geom_errorbar(aes(ymin = AvrTime - StdErr, ymax = AvrTime + StdErr)) +
  geom_line() +
  geom_point(size = 2) +
  xlab("ArraySize") +
  ylab("AvrTime (ns)") +
  ggtitle(df$Type[1])
```

**Comment by mattwarren** [comment]
cool, R has been on my list of things to look at for a while.

Maybe we could integrate it with BenchmarkDotNet so you could automatically get graphs (as well as .csv/.json)?

**Comment by AndreyAkinshin** [comment]
Yes, it is my plan =)
