### ISSUE TITLE
Top N of M runs

### ISSUE THREAD

**Issue by omariom** [PerfDotNet/BenchmarkDotNet#80]
Sometimes when I only do  in memory work (without multithreading or IO)  I want to see top N of M runs (or even top 1). I don't need  averages in such cases.

**Comment by AndreyAkinshin** [comment]
Can you write an example?

**Comment by omariom** [comment]
An example how it could be configured?

**Comment by AndreyAkinshin** [comment]
Yes. And how it should looks.

**Comment by omariom** [comment]
Semething like this

[BenchmarkTask(processCount: 1, targetIterationCount: 5, **takeTop: 2**)]

**Comment by omariom** [comment]
I've just noticed BenchmarkStatResultExtenders. Can the feature be implemented this way?

**Comment by AndreyAkinshin** [comment]
See usage example: https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet.IntegrationTests/Plugins/BenchmarkStatResultExtenderTests.cs
More documentation are coming.

But I am still not sure that I correctly understand your idea. Can you write an example of desired output?

**Comment by omariom** [comment]
All the results should be sorted desc and only top N of them are used in the stats calculations.

**Comment by AndreyAkinshin** [comment]
Hmm. Are you talking about these results:
```
Target 1: 4000 op, 1999162573.23 ns, 499.7906 us/op
Target 2: 4000 op, 1998628859.45 ns, 499.6572 us/op
Target 3: 4000 op, 1994555559.65 ns, 498.6389 us/op
Target 4: 4000 op, 1997694393.81 ns, 499.4236 us/op
Target 5: 4000 op, 1995667307.84 ns, 498.9168 us/op
Target 6: 4000 op, 1997021186.66 ns, 499.2553 us/op
Target 7: 4000 op, 1999407036.53 ns, 499.8518 us/op
Target 8: 4000 op, 1999490545.94 ns, 499.8726 us/op
Target 9: 4000 op, 1998865391.69 ns, 499.7163 us/op
Target 10: 4000 op, 1997894536.48 ns, 499.4736 us/op
```
?

**Comment by omariom** [comment]
Currently all the runs are used to calculate for example `op/s`. When asked to `takeTop: 4` only best 4 of them will be used to calculate average `op/s` which goes to the results table.

**Comment by AndreyAkinshin** [comment]
Ok, now I get it. But why do you need it?
In the next version, I want to implement automatic logic for choosing amount of target iteration (you will still be able to set fixed `targetIterationCount`, but auto mode will be default).

But yes, you can implement your idea via ResultExtenders.

**Comment by omariom** [comment]
> But why do you need it?

I want to exclude outliers caused by uncontrollable OS, network activities or other unfortunate conditions.

**Comment by AndreyAkinshin** [comment]
`StatSummary` [contains](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/BenchmarkDotNet/Statistic/StatSummary.cs#L66) the following property: 
```
public double[] Outlier { get; }
```
Maybe it will be useful for your.
I think, I can implement a standard ResultExtender that will be calculate `op/s` without outliers.

**Comment by AndreyAkinshin** [comment]
In `v0.9.0`, you can define own column and use all data from the summary to build any statistics based on any subset of measurements.
