### ISSUE TITLE
BenchmarkPlugin attribute

### ISSUE THREAD

**Issue by AndreyAkinshin** [PerfDotNet/BenchmarkDotNet#81]
The idea is the following: we can add plugin via attributes like this:
```cs
[BenchmarkPlugin(typeof(BenchmarkStatResultExtender))]
public class MyBenchmarkClass
```
@mattwarren, what do you think?

**Comment by mattwarren** [comment]
yeah great idea. 

I was beginning to wonder how we could best allow people to control all the different plugins. Having to do it only on the cmd line would get tedious, this is a great solution.

**Comment by AndreyAkinshin** [comment]
Also we can define an attribute for plugin set like
```cs
[BenchmarkPluginSet(typeof(BenchmarkDefaultPluginSet))]
public class MyBenchmarkClass
```
or
```cs
[BenchmarkPluginSet(typeof(BenchmarkEmptyPluginSet))]
public class MyBenchmarkClass
```
instead of `CreateDefault()` or `CreateEmpty()`.
