### ISSUE TITLE
Not an issue actually.. Just wanted to say..

### ISSUE THREAD

**Issue by omariom** [PerfDotNet/BenchmarkDotNet#88]
![thank-you_0](https://cloud.githubusercontent.com/assets/1781701/12722043/e4316e76-c913-11e5-9d2e-415e33e30370.jpg)

To @AndreyAkinshin, @mattwarren, @jskeet  and all other contributors.

**Comment by mattwarren** [comment]
cheers

**Comment by AndreyAkinshin** [comment]
Cheers.
