### ISSUE TITLE
TaskAttribute name is ambigous

### ISSUE THREAD

**Issue by azhmur** [PerfDotNet/BenchmarkDotNet#9]
With System.Threading.Tasks.Task. Yes, we can use full name like [TaskAttribute] or [BenchmarkDotNet.Tasks.Task], but it maybe better to rename attribute to resolve this frequently occurring naming conflict.

**Comment by AndreyAkinshin** [comment]
@azhmur Do you have any ideas about a better name for the `BenchmarkDotNet.Tasks.Task` class?

**Comment by mattwarren** [comment]
What about `BenchmarkTask`, that should less ambigous

**Comment by azhmur** [comment]
My idea was something like BenchmarkSuite, but BenchmarkTask is even better.

**Comment by AndreyAkinshin** [comment]
@mattwarren, @azhmur, LGTM. I will change it in the next version.

**Comment by azhmur** [comment]
Thanks, you library helped me greatly in researching what can be improved in .Net Tuple implementation.

https://github.com/azhmur/TupleBenchmark

**Comment by AndreyAkinshin** [comment]
@azhmur, you are welcome!
