### ISSUE TITLE
Results in the R graphs aren't displayed in a "Natural Sort Order"

### ISSUE THREAD

**Issue by mattwarren** [PerfDotNet/BenchmarkDotNet#92]
This means that if you have a benchmark with `[Params(1, 2, 3, 4, 5, 10, 15, 20)]` the results look like this:

![framework_stringconcatvsstringbuilder-barplot](https://cloud.githubusercontent.com/assets/157298/13083762/5298f440-d4ce-11e5-8226-b3ac8549e18d.png)

i.e. the order of the bars is `1, 10, 15, 2, 20, 3, 4, 5`, which is a bit misleading!!

~~I don't know enough about how we generate the graphs to know if it's a problem with R or the .csv file it reads the results from?~~ After a bit of digging around, I think that it's the `measurments.csv` file that has the data in the wrong order?

**Comment by AndreyAkinshin** [comment]
> I think that it's the measurments.csv file that has the data in the wrong order?

Yes. I think, you should just reorder lines in `CsvMeasurementsExporter` according to the natural sort order.

**Comment by mattwarren** [comment]
Thanks for fixing this, it works now

![framework_stringconcatvsstringbuilder-barplot](https://cloud.githubusercontent.com/assets/157298/13224926/9d91cad6-d982-11e5-8a84-cdda7e7f1034.png)
