### ISSUE TITLE
Put all the  generated artifacts in a separate folder

### ISSUE THREAD

**Issue by omariom** [PerfDotNet/BenchmarkDotNet#94]
Currently everything - from benchmarks to reports (including R ones) - is in `bin/Release`. 
Too many folders and files in one place. Difficult to find what you need.

**Comment by mattwarren** [comment]
Agree, I definitely agree that all the R images/pdfs should probably go in another folder.

It also get's a bit messy when you have lots of `[Param()]` values, as per #91

**Comment by adamsitnik** [comment]
@omariom @mattwarren Do you have any suggestions for the folder's name? Could it be just "artifacts"  or maybe "BenchmarkDotNet.Artifacts"?

**Comment by omariom** [comment]
BenchmarkDotNet.Artifacts sounds good.
Will it be divided further down to  folder for bins and exporters' results?

**Comment by adamsitnik** [comment]
@omariom I think that it would be good to split binaries from results.

- BenchmarkDotNet.Artifacts/results
- BenchmarkDotNet.Artifacts/binaries

**Comment by AndreyAkinshin** [comment]
@adamsitnik, I suggest to use `bin` instead of `binary`.

**Comment by adamsitnik** [comment]
@AndreyAkinshin Ok

**Comment by adamsitnik** [comment]
Ok so now it is:

- BenchmarkDotNet.Artifacts/results
- BenchmarkDotNet.Artifacts/bin
