### ISSUE TITLE
Results should preserve the order of param values definition

### ISSUE THREAD

**Issue by omariom** [PerfDotNet/BenchmarkDotNet#95]
```C#
[Params(1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024)]
public int spanLength;
```
             Method |      Median |    StdDev | spanLength |
------------------- |------------ |---------- |----------- |
 SequenceEqual byte |  18.2487 ns | 0.0000 ns |          1 |
 SequenceEqual byte | 297.9979 ns | 0.0000 ns |       1024 |
 SequenceEqual byte | 259.9845 ns | 0.0000 ns |        128 |
 SequenceEqual byte |  45.4490 ns | 0.0000 ns |         16 |
 SequenceEqual byte |  20.7629 ns | 0.0000 ns |          2 |
 SequenceEqual byte | 323.5553 ns | 0.0000 ns |        256 |
 SequenceEqual byte |  76.4659 ns | 0.0000 ns |         32 |
 SequenceEqual byte |  43.6363 ns | 0.0000 ns |          4 |
 SequenceEqual byte | 287.1553 ns | 0.0000 ns |        512 |
 SequenceEqual byte |  93.4799 ns | 0.0000 ns |         64 |
 SequenceEqual byte |  31.9761 ns | 0.0000 ns |          8 |

**Comment by mattwarren** [comment]
Which build are you using? I thought I fixed this?! 

Are they sorted correctly in the console output, or is that wrong as well?

**Comment by AndreyAkinshin** [comment]
@mattwarren, you fixed it in the `develop` branch, we still have `v0.9.1` with this bug as a last stable version on NuGet.

**Comment by mattwarren** [comment]
oh yeah, forgot about that!!

**Comment by omariom** [comment]
@mattwarren  
Does you change preserve the order of definition?

**Comment by mattwarren** [comment]
No it explicitly sorts them in Natural Sort Order, i.e. sorts the param values as int/long/double/etc, rather than as text as we were doing previously.

![image](https://cloud.githubusercontent.com/assets/157298/13232253/49c28b6a-d9a6-11e5-827e-7e6d50b01043.png)

Is there a scenario where you would want them sorted in definition order, rather than their actual order?

**Comment by omariom** [comment]
I just thought there could be a case when values are strings and the order is only meaningful for me )

But ordering by values is ok.
