### ISSUE TITLE
Implement enums as valid Param for test

### ISSUE THREAD

**Issue by Pzixel** [PerfDotNet/BenchmarkDotNet#96]
For example I have following declaration:
```csharp
public enum TestType
{
   Short,
   Int,
   Long    
}
```
and now I want to use it:

```csharp
[Params(TestType.Short, TestType.Int, TestType.Long)]
public TestType TestType { get; set; }
```
But I get multiple errors and test doesn't run. 

I think it's not hard to implement enums. But i'd like to use a type of enum and take all values as params, for example:

```csharp
[ParamsEnum(typeof(TestType)]
public TestType Example { get; set; }
```

**Comment by adamsitnik** [comment]
I know that this is just a workaround, but you can try something like this:

```
[Params((int)TestType.Short, (int)TestType.Int, (int)TestType.Long)]
public int TestType { get; set; }
```

**Comment by AndreyAkinshin** [comment]
I add enum support in 0.9.2, this feature requires a few lines of code.

**Comment by AndreyAkinshin** [comment]
Fixed in the develop branch.
