### ISSUE TITLE
Params changes an order

### ISSUE THREAD

**Issue by Pzixel** [PerfDotNet/BenchmarkDotNet#97]
Sample class:

```csharp
public class BencmarkBug
{
    [Params(3000, 5000, 8000, 10000)]
    public int Treshold { get; set; }

    [Benchmark]
    public object Foo()
    {
        return Treshold;
    }
}
```

Output:

![untitled](https://cloud.githubusercontent.com/assets/11201122/13281557/93a59d6c-daf5-11e5-9a2e-9439779ea5f9.png)

Expected output: 10000 will be at the last line.

**Comment by mattwarren** [comment]
FYI, this is already fixed in the GitHub source and will be in the next NuGet release
